<h1><?= $this->translate('woma_woma_images_headline') ?></h1>
<table class="table" id="bilder">
    <tr><td>Logo</td><td id="logoPicture"><?php if($this->woma->getLogo()): ?><img style="width:120px;" src="/img/womas/<?= $this->escape($this->woma->getLogo()->filename) ?>" alt=""><?php else: ?><input id="logoPictureupload" type="file" name="file" data-url="/woma/woma/pictures/" /><?php endif; ?></td><td><button id="deleteLogo" class="btn btn-danger" onclick="deleteShopPicture('logoPicture');"><?= $this->translate('misc_delete') ?></button></td></tr>
    <tr><td>Geschichte</td><td id="history"><?php if($this->woma->getHistoryPicture()): ?><img style="width:120px;" src="/img/womas/<?= $this->escape($this->woma->getHistoryPicture()->filename) ?>" alt=""><?php else: ?><input id="historyupload" type="file" name="file" data-url="/woma/woma/pictures/" /><?php endif; ?></td><td><button id="deleteHistory" class="btn btn-danger" onclick="deleteShopPicture('history');"><?= $this->translate('misc_delete') ?></button></td></tr>
    <tr><td>Herstellung</td><td id="procedure"><?php if($this->woma->getProcedurePicture()): ?><img style="width:120px;" src="/img/womas/<?= $this->escape($this->woma->getProcedurePicture()->filename) ?>" alt=""><?php else: ?><input id="procedureupload" type="file" name="file" data-url="/woma/woma/pictures/" /><?php endif; ?></td><td><button id="deleteProcedure" class="btn btn-danger" onclick="deleteShopPicture('procedure');"><?= $this->translate('misc_delete') ?></button></td></tr>
</table>

<script src="/js/libs/jquery.iframe-transport.js"></script>
<script src="/js/libs/jquery.fileupload.js"></script>
<script>
    $(document).ready(function(){
        initUpload();
    });

    function deleteShopPicture(type){
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "/woma/woma/deletepicture/",
            data: { type : type }
        }).done(function ( res ) {
            if(res.suc){
                $('#' + type).html('<input id="' + type + 'upload" type="file" name="file" data-url="/woma/woma/pictures/" />');
                initUpload();
            }

        });
    }

    function initUpload() {
        $('#logoPictureupload').fileupload({
            dataType: 'json',
            formData: {type: 'logo'},
            send: function(e, data){
                $('#logoPicture').html('<img src="/images/business/pic_loading.gif" alt="Bitte warten..."/> Bitte warten...');
            },
            done: function (e, data) {
                if(data){
                    $('#logoPicture').html(data.result.data);
                }
                else{
                    alert('Upload nicht erfolgreich');
                }
            }
        });
        $('#historyupload').fileupload({
            dataType: 'json',
            formData: {type: 'history'},
            send: function(e, data){
                $('#history').html('<img src="/images/business/pic_loading.gif" alt="Bitte warten..."/> Bitte warten...');
            },
            done: function (e, data) {
                if(data){
                    $('#history').html(data.result.data);
                }
                else{
                    alert('Upload nicht erfolgreich');
                }
            }
        });
        $('#procedureupload').fileupload({
            dataType: 'json',
            formData: {type: 'procedure'},
            send: function(e, data){
                $('#procedure').html('<img src="/images/business/pic_loading.gif" alt="Bitte warten..."/> Bitte warten...');
            },
            done: function (e, data) {
                if(data){
                    $('#procedure').html(data.result.data);
                }
                else{
                    alert('Upload nicht erfolgreich');
                }
            }
        });


    };    

</script>
