<h1>Bewertung hinzufügen / editieren</h1>
<?= $this->form; ?>

<script type="text/javascript">
    $(document).ready(function(){
        $('#rating-label').raty(
            { 
                path: '/img/raty/',
                width: false,
                click: function(score, evt) {
                    $('#rating').val(score);
                }
<?php if($this->form->getValue('rating')): ?>
                ,score: <?= $this->form->getValue('rating') ?>
<?php endif; ?>
            }
        ).prepend('Bewertung: ');
    });      
</script>
