<div class="row">
    <div class="col-2 bg-light border m-3">
	<?php if($this->shop->getLogo()): ?>
	    <a href="<?= $this->shop->getLink() ?>"><img class="img-thumbnail" src="/img/shops/<?= $this->escape($this->shop->getLogo()->filename) ?>" alt="<?= $this->escape($this->shop->name) ?>" /></a>
	<?php endif; ?>
	<p><a href="<?= $this->shop->getLink() ?>" title="<?= $this->shop->getLink() ?>"><?= $this->escape($this->shop->name) ?></a></p>
	<p><?= $this->escape($this->shop->city) ?><br /><?= $this->escape($this->shop->getCountry()->name) ?></p>
	<p><a href="<?= $this->shop->getLink() ?>" title="">Besuchen Sie unseren Shop</a></p>
	<ul>
		<li>
			<a href="mailto:<?= $this->shop->getUser()->email ?>" title="Kontakt">Kontakt</a>	
		</li>
		<li>
			<a href="<?= $this->shop->getLink() ?>agb" title="AGB">AGB</a>
		</li>
		<li>
			Datenschutz
		</li>
		<li>
			<a href="<?= $this->shop->getLink() ?>impressum" title="Impressum">Impressum</a>		
		</li>		
	</ul>
    </div>
    <div class="col bg-light border m-3">
<h2>Datenschutzbestimmungen von <?= $this->escape($this->shop->name) ?></h2>
			
			<p>Liebe Kundeninnen und Kunden,<br/>
wir, <?= ($this->shop->company) ? $this->escape($this->shop->company) : $this->escape($this->shop->name) ?>  verpflichten uns, Ihre Privatsphäre und Ihre persönlichen Daten zu schützen und personenbezogene Daten ausschließlich nach den strengen Vorschriften des deutschen Datenschutzrechts zu erheben, zu nutzen und zu verarbeiten.<br/>
<br/>
<strong>Datenerhebung</strong><br/>
Wir erheben Daten beim Anbahnen, beim Abschluss, beim Abwickeln und beim Rückabwickeln eines Kaufvertrages. Diese Daten werden von uns erhoben, gespeichert und verarbeitet.<br/>
<br/>
Ihr Besuch auf unseren Webseiten wird protokolliert. Erfasst werden im Wesentlichen die aktuell von Ihrem PC verwendete IP-Adresse, Datum und Uhrzeit, der Browsertyp und das Betriebssystem Ihres PC sowie die von Ihnen betrachteten Seiten. Ein Personenbezug ist uns im Regelfall nicht möglich und auch nicht beabsichtigt.<br/>
<br/>
<strong>Datenverwendung und -weitergabe</strong><br/>
Die personenbezogenen Daten, die Sie uns z.B. bei einer Bestellung oder per E-Mail mitteilen (z.B. Ihr Name und Ihre Adresse oder Ihre E-Mail-Adresse), werden nur zur Korrespondenz mit Ihnen und nur für den Zweck verarbeitet, zu dem Sie uns die Daten zur Verfügung gestellt haben.<br/>
<br/>
Wir geben Ihre Daten nur an die mit der Lieferung beauftragten Transportdienstleister weiter, sofern Sie die Sachspendenbörse- Transportbörse nutzen. Zur Abwicklung bei anfallenden Versandkosten geben wir Ihre Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut weiter. In diesen Fällen geben wir Ihre Daten nur unter der Voraussetzung weiter, dass sich diese uns gegenüber durch Vertrag zur Beachtung des Schutzes Ihrer Daten verpflichten.<br/>			
<br/>
Um Ihnen wiederholte Eingaben Ihrer Daten zu ersparen, speichern wir in Ihrem Account Daten wie Adressen, E-Mail-Adressen, Name, Passwort, Zahlungsarten, Bestellhistorien.<br/>
Ebenfalls speichern wir Ihre Daten um den Einkauf für Sie soweit als möglich zu personalisieren und Ihnen kompetente Fachberatung geben zu können, z.B. indem wir Ihnen Produkte vorschlagen anhand Ihrer Käufe und Besuche oder Ihre Einkaufszettel mit den früheren Bestellungen zum erneutem Kauf anbieten. Oder um Sie über neue Produkte und Dienstleistungen zu informieren.<br/>
<br/>
Wir versichern, dass wir Ihre personenbezogenen Daten im übrigen nicht an Dritte weitergeben, es sei denn, dass wir dazu gesetzlich verpflichtet wären oder Sie uns vorher Ihre Zustimmung gegeben haben. Soweit wir zur Durchführung und Abwicklung von Verarbeitungsprozessen Dienstleister in Anspruch nehmen, werden die Vertragsverhältnisse nach den Bestimmungen des Bundesdatenschutzgesetzes geregelt.<br/>
<br/>
<strong>Einwilligung und Widerruf</strong><br/>
Mit Absenden der Bestellung erklären Sie sich damit einverstanden, dass Ihre Daten wie beschrieben von uns erhoben, verarbeitet und genutzt werden Wenn Sie uns personenbezogene Daten überlassen haben, können Sie diese jederzeit wieder löschen. Daten für Abrechnungs- und buchhalterische Zwecke sind von einer Kündigung/einem Widerruf bzw. von einer Löschung nicht berührt.<br/>
<br/>
<strong>Speicherdauer</strong><br/>
Personenbezogene Daten, die uns über unsere Website mitgeteilt worden sind, werden nur so lange gespeichert, bis der Zweck erfüllt ist, zu dem sie uns anvertraut wurden. Soweit handels- und steuerrechtliche Aufbewahrungsfristen zu beachten sind, kann die Speicherdauer zu bestimmten Daten bis zu 10 Jahre betragen.<br/>
<br/>
<strong>Kundenkonto</strong><br/>
Wenn Sie ein Kundenkonto eröffnen, willigen Sie damit ein, dass Ihre Bestandsdaten wie Name, Adresse, E-Mailadresse, und Bankverbindung sowie Ihre Nutzungsdaten (Benutzername, Passwort) gespeichert werden. Dadurch haben Sie die Möglichkeit, mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort auf dem Internet-Marktplatz und in unserem Online Shop zu bestellen.<br/>
<br/>
<strong>Newsletter</strong><br/>
Mit der Anmeldung zum Newsletter werden Ihr Vorname, Ihr Nachname und Ihre E-Mail-Adresse mit Ihrer Einwilligung für eigene Werbezwecke genutzt. Der Versand des Newsletters erfolgt durch unser Partnerunternehmen Epelia (Warenhandel Gattinger), hierzu erfolgt die Weitergabe Ihrer Daten.<br/>
<br/>
Die Einwilligung zum Empfang eines Newsletters per E-Mail ist jederzeit widerrufbar. In jedem Newsletter finden Sie dazu einen Link, mit dem Sie Ihre Einwilligung widerrufen können.<br/>
<br/>
<strong>Ihre Rechte</strong><br/>
Sollten Sie mit der Speicherung Ihrer personenbezogenen Daten nicht mehr einverstanden oder diese unrichtig geworden sein, werden wir auf eine entsprechende Weisung hin die Löschung oder Sperrung Ihrer Daten veranlassen oder die notwendigen Korrekturen vornehmen (soweit dies nach dem geltendem Recht möglich ist). Auf Wunsch erhalten Sie unentgeltlich Auskunft über alle personenbezogenen Daten, die wir über Sie gespeichert haben.<br/>
<br/>
Bei Fragen zur Erhebung, Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, bei Auskünften, Berichtigung, Sperrung oder Löschung von Daten wenden Sie sich bitte an:<br/>
<br/>
 <?= ($this->shop->company) ? $this->escape($this->shop->company) : $this->escape($this->shop->name) ?> <br/>
<br/>
<strong>Verwendung von Cookies</strong><br/>
Eine Nutzung des Angebotes von unseres Shops erfolgt mit dem Einsatz eines Cookies. Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Browsereinstellungen aktiviert haben.<br/>
<br/>
In dem Cookie wird ein zufällig generierter Session-Code und gegebenenfalls Ihre Kunden-ID gespeichert. Damit ist es möglich, Sie als registrierter Kunden zu erkennen.<br/>
<br/>
Zusätzlich speichert Epelia, falls vorhanden, eine Affiliate-ID und die Seite, von der aus Sie auf unsere Seiten gekommen sind.<br/>
<br/>
Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Einstellungen aktiviert haben.<br/>
<br/>
<strong>Änderungen dieser Erklärung</strong><br/>
Soweit wir neue Produkte oder Dienstleistungen einführen, Internet-Verfahren ändern oder wenn sich die Internet- und EDV-Sicherheitstechnik weiterentwickelt, ist die Datenschutzerklärung zu aktualisieren. Wir behalten uns deshalb das Recht vor, die Erklärung nach Bedarf zu ändern oder zu ergänzen. Die Änderung werden wir an dieser Stelle veröffentlichen. Daher sollten Sie diese Website regelmäßig aufrufen, um sich über den aktuellen Stand der Datenschutzerklärung zu informieren.</p>
    </div>
</div>
