<div id="content_buy">
    <h1 style="margin-bottom:0px;"><?= $this->translate('wholesale_show_all_headline') ?></h1>
    <div class="content_buy_categories">
<?php foreach($this->mainCategories as $cat): 
    if(!$cat->getGroups(false, false, true)):
        continue;
    endif; ?>
        <?= $this->partial('partials/groupgrid.phtml', array('groupTitle' => $this->translate($cat->name), 'groups' => $cat->getGroups(false, false, true), 'onlyBio' => false, 'onlyDiscount' => false, 'onlyWholesale' => true)) ?>
<?php endforeach; ?>        
    </div>
    <p class="clear"></p>
</div>
