<div class="row">
    <div class="col bg-light border m-3">
        <?php if($this->region): ?>
            <h2><?= $this->translate('regions_selected_headline') ?> <?= $this->region->name ?></h2>
            <h3><?= $this->translate('regions_selected_subheadline') ?></h3>
            <p><?= $this->translate('regions_selected_text_1') ?></p>
            <p><?= $this->translate('regions_selected_text_2') ?></p>
        <?php else: ?>
            <h2><?= $this->translate('regions_choose_headline') ?></h2>
            <p><?= $this->translate('regions_choose_text_1') ?></p>
            <p><?= $this->translate('regions_choose_text_2') ?></p>
        <?php endif; ?>

        <form id="regionForm" class="m-3">
            <div class="row">
                <div class="col">
                      <input type="text" class="form-control" id="plz" placeholder="PLZ">
                </div>
                <div class="col">
                    <select class="form-control" id="country">
                        <option value=""><?= $this->translate('misc_choose_country') ?></option>
                        <?php foreach($this->availableRegions as $region): ?>
                        <option value="<?= $region->id ?>"><?= $region->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary"><?= $this->translate('misc_search_for_region') ?></button>
                </div>
            </div>
            <div class="alert alert-success mt-2 collapse" id="found"></div>
            <div class="alert alert-danger mt-2 collapse" id="error"></div>
            <div class="alert alert-warning mt-2 collapse" id="warning"></div>
        </form>

    </div>
</div>

<script type="text/javascript">
    $("#regionForm").submit(function(e) {
        e.preventDefault(); // avoid to execute the actual submit of the form.
        $('#error').hide();
        $('#warning').hide();
        $('#found').hide();

        var plz = $("#plz").val();
        var country = $("#country").val();
        if(plz && country) {
            choseRegion(plz, country);
        } else{
            $('#error').html('<?= $this->translate('misc_plz_country_validation') ?>').show();
        }
    });

    function choseRegion(plz, country){
        $.ajax({
            type: "POST",
            url: "/ajax/selectregion/",
            dataType: 'json',
            data:{
                plz: plz,
                country: country
            },
        }).done(function(ret){
            if(!ret.suc) {
                if(ret.message == 'No region found') {
                    $('#warning').html('<?= $this->translate('misc_no_region_found') ?>').show();
                }
            } else {
                $('#found').html('Region gefunden: ' + ret.data.name + ' <a class="btn btn-success" href="/regions/changeregion/' + ret.data.id + '"><?= $this->translate('misc_choose_region') ?></a>').show();
            }
        });
    };

</script>
