<div class="row">
    <div class="col bg-light border m-3">
    <h2>Allgemeine Geschäftsbedingungen</h2>
            <div class="relevant_content">
                <p><h3>Allgemeine Geschäftsbedingungen der OpenFoodBank, Fairdirect e.V., für gemeinnützige Organisationen</h3><br/>
        <h4>0. Präambel</h4>1. Die nachfolgenden AGB gelten ausschließlich für die Geschäftsbeziehungen der OpenFoodBank Spender mit ihren Kunden. Kunden sind ausschließlich gemeinnützige Organisationen nach §52 (AO) und bei frischen Lebensmittel bzw. nur sehr kurz haltbaren Lebensmitettel zertifizierte Secondfood- Produzenten.<br/>
        <br/>
        <h4>1. Vertragsschluss</h4>1. Bei Bestellungen auf OpenFoodBank.net kommt der Vertrag mit dem jeweiligen Spender zustande.<br/>
        Fairdirect e.V. (Vorstand Micha Gattinger und Matthias Ansorg, Konrad-Becker-Str. 11, 35102 Lohra, E-Mail mail@fairdirect.org, Steuernummer 031 250 52117) wird nicht Vertragspartner.<br/>
        2. Die vom Spender gesendete Bestellung ist ein bindendes Angebot, an das dieser zwei Wochen gebunden ist. Der Vertrag kommt durch eine Bestätigungsemail oder spätestens mit Erhalt der bestellten Ware zustande. Der Erhalt einer Bestellbestätigung stellt noch keine Annahme des Angebots dar.<br/>
        3. Abweichende Regelungen gelten nur, soweit sie von uns im Einzelfall ausdrücklich und schriftlich anerkannt wurden.<br/>
        <br/>
        <h4>2. Versand</h4> 1. Alle gesetzlich geforderten Pflichten zur ordnungsgemäßen Behandlung (z.B. Einhaltung/ Nachweis der lückenlosen Kühlkette etc.) der Spenden gehen zum Zeitpunkt der Abholung/ des Versandes der Spende bei dem Spender vom Spender an den Kunden über.<br/>
        2. Kann der Kunde die Spende nicht selbst beim Spender abholen, ist er verpflichtet sich selbst um den Versand zu kümmern. Die OpenFoodBank stellt hierfür, als eine kostengünstige Option, eine Transportbörse bereit.<br/>
        3. Alternativ kann der Spender einen eigenen, kostenpflichtigen Versand der Spende anbieten. Diese Versandkosten werden im Bestellprozess eingebunden und sind nach der Bestellbestätigung vorab vom Kunden zu zahlen. Sind keine Versandkosten hinterlegt, ist immer der Kunde für die Abholung/ den Versand der Spende verantwortlich.<br/>     
        <br/>
        <h4>3. Eigentumsvorbehalt</h4> Bis zur Abholung/ dem Versand der Spende bleibt diese Eigentum des Spenders. Vor Übergang des Eigentums darf der Kunde nicht über die Spende verfügen.<br/>
        <br/>
        <h4>4. Widerrufrecht>/h4> Alle Spender sowie alle Spendenempfänger auf der OpenFoodBank sind nach §14BGB Unternehmer. Daher entfällt das Widerrufsrecht.
        <h4>4. Mängelgewährleistung</h4>Ansprüche des Kunden wegen Sachmängeln der Ware verjähren entsprechend den gesetzlichen Bestimmungen.<br/>
        <br/>
        <h4>5. Haftung</h4> 1. Aufgrund der unentgeltlichen Abgabe gilt in der Regel Schenkungsrecht. Schadensersatz für Sachmängel ist hiernach vom, seinen gesetzlichen Vertretern und seinen Erfüllungsgehilfen bei arglistigem Verschweigen eines Fehlers zu leisten (§§ 516, 524 BGB).<br/>
        3. Unabhängig vom Grad des Verschuldens bleibt eine etwaige Haftung im Falle arglistigen Verschweigen eines Mangels, aus der Übernahme einer Garantie oder nach dem Produkthaftungsgesetz unberührt.<br/>
        <br/>
        <h4>6. Schlussbestimmungen</h4>1. Es findet ausschließlich deutsches Recht unter Ausschluss des UN-Kaufrechts Anwendung.<br/>
        2. Gerichtsstand ist der angegebene Erfüllungsort der Spender auf OpenFoodBank.net.<br/>
        3. Änderungen und Ergänzungen dieser AGB bedürfen zu ihrer Wirksamkeit der Schriftform. Dies gilt auch für Aufhebung, Änderung und Ergänzung dieser Schriftformklausel.<br/>
        4. Soweit einzelne Bestimmungen dieser AGB ganz oder teilweise unwirksam sind, wird hierdurch die Wirksamkeit dieser AGB im Übrigen nicht berührt. Die Parteien verpflichten sich die unwirksame Klausel durch eine Regelung zu ersetzen, welche der gewollten wirtschaftlich am nächsten kommt.</p>
            </div>

        </div>
</div>
