<div class="row">
    <div class="col bg-light border m-3">
    <h2>Bestellen bei Epelia</h2>

        <h3>Warum sollte ich bei Epelia bestellen?</h3>
        <p>Epelia ermöglicht dass Anbieter und Kunden in der jeweiligen Region zusammen finden. Statt aufwändig nach Anbieter und deren Produkten in der Region zu suchen, finden Kunden hier alles an einem Platz. Anbietern ermöglicht Epelia, ohne Umwege gemeinsam und direkt an Kunden zu verkaufen und durch die Gründung einer Versandzelle gemeinschaftlich auch zu versenden. Kunden können so entscheiden ob sie ihre Einkäufe online vorbestellen und vor Ort abholen oder diese bequem und versandkostensparend angeliefert bekommen. Übrigens im regionalen Liefergebiet innerhalb weniger Stunden.</p>
        <h3>Wie kann ich bei Epelia bestellen?</h3>
        <p>Sie wählen die Produkte aus, die Ihnen gefallen, legen sie in den Warenkorb und entscheiden ob Sie diesen als Einkaufszettel einfach und unverbindlich ausdrucken oder diesen online bestellen möchten. Während des gesamten Bestellprozesses können Sie Bestellmengen ändern oder Produkte entfernen und hinzufügen. Mit einem Bestellvorgang können Sie Produkte von verschiedenen Anbietern bestellen und bezahlen. Sie können im Bestellprozess auch wählen ob Sie die bestellten Einkäufe vor Ort abholen oder diese angeliefert haben möchten.</p>
        <h3>Was passiert mit meinen persönlichen Daten?</h3>
        <p>Bei der Bestellung müssen Sie E-Mail Adresse und eine Versand- bzw. Rechnungsadresse angeben. Das ist notwendig, damit Ihnen die Ware zugestellt werden kann. Ihre E-Mail Adresse benötigen wir, damit wir Sie kontaktieren können, falls es einmal zu Schwierigkeiten bei der Lieferung kommen sollte.<br />
        Seien Sie bitte nicht besorgt, dass Ihre persönlichen Daten in die falschen Hände kommen. Wir gehen sehr sorgsam mit diesen Daten um und befolgen die strengen Richtlinien des deutschen Datenschutzgesetzes.</p>
        <h3>Gibt es einen Mindestbestellwert?</h3>
        <p>Nein, alle Verkäufer verkaufen ohne Mindestbestellwert.</p>
        <h3>Kann ich meine Bestellung nachträglich ändern oder stornieren?</h3>
        <p>Wenn Sie Angaben oder Mengen zu Ihrer Bestellung ändern möchten, dann lassen Sie es uns umgehend wissen. Schreiben Sie eine E-Mail an mail@epelia.com oder rufen Sie uns unter Tel. 01803 465283 ("0180 EINKAUF"; 9 ct/min aus dem Deutschen Festnetz; aus Mobilfunknetzen können abweichende Preise gelten) an. Wir bemühen uns Ihre Bestellung nach Ihren Wünschen zu bearbeiten.</p>
        <h3>Wie melde ich Schwierigkeiten mit einer Bestellung?</h3>
        <p>Sie können sich jederzeit an unseren Kundenservice unter der Telefon Nr. 01803 465283 ("0180 EINKAUF"; 9 ct/min aus dem Deutschen Festnetz; aus Mobilfunknetzen können abweichende Preise gelten) oder per E-Mail an mail@epelia.com wenden.</p>
        <h3>Kann ich auch per E-Mail, Fax oder telefonisch bestellen?</h3>
        <p>Falls es Ihnen nicht möglich ist, online über den Epelia Marktplatz zu bestellen, können Sie uns gerne anrufen oder eine E-Mail bzw. ein Fax an 06426-967338 senden.</p>
        <h3>Kann ich aus dem Ausland bestellen?</h3>
        <p>Ja, fast alle Anbieter bieten internationalen Versand an. Lieferland und -kosten finden Sie in den jeweiligen Shops unter Lieferung &amp; Versand.</p>        
    </div>
</div>
