<div class="row">
    <div class="col bg-light border m-3">
    <h2>FAQ zur OpenFoodBank</h2>

        <h3>Was ist das OpenFoodBank- Netzwerk</h3>
        <p>Das OpenFoodBank- Netzwerk ist ein offener Ort um Lebensmittelüberschüsse zu Spenden statt zu entsorgen. Viel zu viele Lebensmittel werden achtlos weggeworfen. Über das OpenFoodBank- Netzwerk werden diese meist noch guten Überschüsse an gemeinnützige Organisationen vermittelt. Diese wiederum verteilen diese Überschüsse an Bedürftige weltweit.</p>
        <h3>Wer kann über das OpenFoodBank- Netzwerk Spenden bekommen?</h3>
        <p>Das OpenFoodBank- Netzwerk ist ausschließlich eine Vermittlungsplattform zwischen spendenden Akteuren entlang der kompletten Wertschöpfungskette "Lebensmittel" als Spender und gemeinnützigen Organisationen als Spendenempfänger.</p>
        <h3>Was passiert mit meinen persönlichen Daten?</h3>
        <p>Bei der Bestellung müssen Sie E-Mail Adresse und eine Versand- bzw. Rechnungsadresse angeben. Das ist notwendig, damit Ihnen die Ware zugestellt werden kann. Ihre E-Mail Adresse benötigen wir, damit wir Sie kontaktieren können, falls es einmal zu Schwierigkeiten bei der Lieferung kommen sollte.<br />
        Seien Sie bitte nicht besorgt, dass Ihre persönlichen Daten in die falschen Hände kommen. Wir gehen sehr sorgsam mit diesen Daten um und befolgen die strengen Richtlinien des deutschen Datenschutzgesetzes.</p>
        <h3>Kann ich als Privatperson Lebensmittel über das OpenFoodBank- Netzwerk spenden?</h3>
        <p>Ja, viele gemeinnützige Organisationen stellen Spendengesuche mit den benötigten Lebensmittelkategorien in dem für jedermann offenen Bereich ein.In den Anzeigen finden Sie die Adresse der Annahmestelle incl. Öffnungszeiten.</p>
        <h3>Kann ich meine Bestellung nachträglich ändern oder stornieren?</h3>
        <p>Wenn Sie Angaben oder Mengen zu Ihrer Bestellung ändern möchten, dann lassen Sie es uns umgehend wissen. Schreiben Sie eine E-Mail an mail@fairdirect.org oder rufen Sie uns unter Tel.+49 6426 8630364 an. Wir bemühen uns Ihre Bestellung nach Ihren Wünschen zu bearbeiten.</p>
        <h3>Wie melde ich Schwierigkeiten mit einer Bestellung?</h3>
        <p>Sie können sich jederzeit an uns unter der Telefon oder per Email wenden.</p>
        <h3>Kann ich auch per E-Mail, Fax oder telefonisch bestellen?</h3>
        <p>Falls es Ihnen als gemeinnützige Organisation nicht möglich ist, online über die OpenFoodBank zu bestellen, können Sie uns gerne anrufen oder eine E-Mail bzw. ein Fax an +49 6426 967338 senden.</p>
        <h3>Was kostet eine Teilnahme?</h3>
        <p>Eine Teilnahme an dem OpenFoodBank- Netzwerk ist komplett und für alle Teilnehmer, egal ob Spender oder Spendenempfänger kostenlos. Auch sind alle angebotene Spenden immer kostenlos. Ist eine kostenlose Abholung der Spende bei dem Spender durch den Spendenempfänger nicht möglich, fallen Transportkosten an.</p>        
    </div>
</div>
