<div class="row">
    <div class="col bg-light border m-3">
    <h2>Zahlungsmöglichkeiten</h2>
        <h3>Welche Zahlungsarten bietet Epelia an?</h3>
        <table class="" cellpadding="0" cellspacing="0">
            <tr>
                <td class="method">Vorkasse</td>
                <td class="description">Nach Abschluss der Bestellung bei Epelia erhalten Sie eine Bestätigungsmail über den Eingang Ihrer Bestellung. In dieser E-Mail sind alle Daten zur Bestellung und die Zahlungsinformationen hinterlegt. Bitte überweisen Sie dann den angegebenen Betrag; nach Zahlungseingang wird Ihre Ware umgehend versendet.</td>
            </tr>
            <tr>
                <td class="method">Sofortüberweisung</td>
                <td class="description">Wenn Sie über einen Online-Banking Zugang zu Ihrem Konto verfügen, können Sie sehr einfach und bequem per Sofortüberweisung zahlen. Sofortüberweisung bedeutet, dass Sie das Überweisungsformular für den Bestellwert innerhalb des Bestellprozesses ausfüllen und online absenden. Diese Zahlungsart ist TÜV-zertifziert und bietet die TÜV geprüfter Transaktionssicherheit.</td>
            </tr>
            <tr>
                <td class="method">Bankeinzug</td>
                <td class="description">Bei Bankeinzug buchen wir den Rechnungsbetrag von Ihrem Konto ab. <br/>
    Diese Bezahlart steht Epelia Kunden mit einem deutschen Konto ab der 3. Bestellung zur Verfügung.</td>
            </tr>
        </table>
        <h3>Wie sicher ist die Online-Bestellung bei Epelia?</h3>
        <p>Sehr sicher, bei Bestellungen werden Daten ausschließlich über eine SSL gesicherte Verbindung übertragen. Niemand Drittes erhält Zugriff auf Ihre Daten. Die Epelia GmbH erfüllt die strengen Gesetzes des deutschen Datenschutzes.</p>
    </div>
</div>
