<div class="row">
    <div class="col bg-light border m-3">
        <h2>Datenschutzbestimmungen OpenFoodBank</h2>
        <h3>Datenschutzerklärung</h3>
        <p>Liebe(r) Nutzer*in,<br/>
            OpenFoodBank ist ein Angebot von Fairdirect e.V, Konrad- Becker- Strasse 11 in 35102 Lohra. Wir verpflichten uns, Ihre Privatsphäre und Ihre persönlichen Daten zu schützen und personenbezogene Daten ausschließlich nach den strengen Vorschriften des deutschen Datenschutzrechts zu erheben, zu nutzen und zu verarbeiten.</p>
        <h3>Datenerhebung</h3>
        <p>Wir erheben Daten beim Anbahnen, beim Abschluss und beim Abwickeln der Vermittlung von Sachspenden über den digitalen Marktplatz www.openfoodbank.net. Diese Daten werden von uns erhoben, gespeichert und verarbeitet. <br/>
        Ihr Besuch auf den Webseiten von OpenFoodBank wird protokolliert. Erfasst werden im Wesentlichen die aktuell von Ihrem PC verwendete IP-Adresse, Datum und Uhrzeit, der Browsertyp und das Betriebssystem Ihres PC sowie die von Ihnen betrachteten Seiten. Ein Personenbezug ist uns im Regelfall nicht möglich und auch nicht beabsichtigt.<br/>
        Der Datensammlung und -speicherung kann jederzeit mit Wirkung für die Zukunft widersprochen werden. Diese Daten werden nur für Zwecke der Datensicherheit und zur Optimierung unseres Webangebots erhoben. </p>
        <h3>Datenverwendung und -weitergabe</h3>
        <p>Die personenbezogenen Daten, die Sie uns z.B. bei einer Spenvermittlung oder per E-Mail mitteilen (z.B. Ihr Name und Ihre Adresse oder Ihre E-Mail-Adresse), werden nur zur Korrespondenz mit Ihnen und nur für den Zweck verarbeitet, zu dem Sie uns die Daten zur Verfügung gestellt haben. <br/>
        Wir geben Ihre Daten nur an die mit der Lieferung beauftragten Transportdienstleister weiter, sofern Sie die OpenFoodBank- Transportbörse nutzen. Zur Abwicklung bei anfallenden Versandkosten geben wir Ihre Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut weiter. In diesen Fällen geben wir Ihre Daten nur unter der Voraussetzung weiter, dass sich diese uns gegenüber durch Vertrag zur Beachtung des Schutzes Ihrer Daten verpflichten.<br/>
        Um Ihnen wiederholte Eingaben Ihrer Daten zu ersparen, speichern wir in Ihrem Account Daten wie Adressen, E-Mail-Adressen, Name, Passwort, Zahlungsarten, Bestellhistorien.<br/>
        Ebenfalls speichern wir Ihre Daten um die Abwicklung von Sachspenden für Sie soweit als möglich zu personalisieren und Ihnen kompetente Fachberatung geben zu können, z.B. indem wir Ihnen Produkte vorschlagen anhand Ihrer Spendenbezüge und Besuche oder Ihre Einkaufszettel mit den früheren Bestellungen zu einem erneuten Spendenbezug anbieten. Oder um Sie über neue Produkte und Dienstleistungen zu informieren.<br/>
        Wir versichern, dass wir Ihre personenbezogenen Daten im übrigen nicht an Dritte weitergeben, es sei denn, dass wir dazu gesetzlich verpflichtet wären oder Sie uns vorher Ihre Zustimmung gegeben haben. Soweit wir zur Durchführung und Abwicklung von Verarbeitungsprozessen Dienstleister in Anspruch nehmen, werden die Vertragsverhältnisse nach den Bestimmungen des Bundesdatenschutzgesetzes geregelt. </p>
        <h3>Einwilligung und Widerruf</h3>
        <p>Mit Absenden der Spendenbestellung erklären Sie sich damit einverstanden, dass Ihre Daten wie  beschrieben von uns erhoben, verarbeitet und genutzt werden  Wenn Sie uns personenbezogene Daten überlassen haben, können Sie diese jederzeit wieder löschen. Daten für Abrechnungs- und buchhalterische Zwecke sind von einer Kündigung/einem Widerruf bzw. von einer Löschung nicht berührt. </p>
        <h3>Speicherdauer</h3>
        <p>Personenbezogene Daten, die uns über unsere Website mitgeteilt worden sind, werden nur so lange gespeichert, bis der Zweck erfüllt ist, zu dem sie uns anvertraut wurden. Soweit handels- und steuerrechtliche Aufbewahrungsfristen zu beachten sind, kann die Speicherdauer zu bestimmten Daten bis zu 10 Jahre betragen.</p>
        <h3>Kundenkonto</h3>
        <p>Wenn Sie auf www.openfoodbank.net ein Kundenkonto eröffnen, willigen Sie damit ein, dass Ihre Bestandsdaten wie Name, Adresse, E-Mailadresse, und Bankverbindung sowie Ihre Nutzungsdaten (Benutzername, Passwort) gespeichert werden. Dadurch haben Sie die Möglichkeit, mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort auf www.openfoodbank.net und den dort angeschlossenen Online- Spendenshops zu bestellen. </p>
        <h3>Newsletter</h3>
        <p>Mit der Anmeldung zum Newsletter werden Ihr Vorname, Ihr Nachname und Ihre E-Mail-Adresse mit Ihrer Einwilligung für eigene Werbezwecke genutzt. Der Versand des Newsletters erfolgt durch das Unternehmen Epelia. <br />
        Die Einwilligung zum Empfang eines Newsletters per E-Mail ist jederzeit widerrufbar. In jedem Newsletter finden Sie dazu einen Link, mit dem Sie Ihre Einwilligung widerrufen können.</p>
        <h3>Ihre Rechte</h3>
        <p>Sollten Sie mit der Speicherung Ihrer personenbezogenen Daten nicht mehr einverstanden oder diese unrichtig geworden sein, werden wir auf eine entsprechende Weisung hin die Löschung oder Sperrung Ihrer Daten veranlassen oder die notwendigen Korrekturen vornehmen (soweit dies nach dem geltendem Recht möglich ist). Auf Wunsch erhalten Sie unentgeltlich Auskunft über alle personenbezogenen Daten, die wir über Sie gespeichert haben.<br/>
        Bei Fragen zur Erhebung, Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, bei Auskünften, Berichtigung, Sperrung oder Löschung von Daten wenden Sie sich bitte an:<br/>
            Fairdirect e.V., Telefon: +49 6426 8630364, E-Mail: mail@fairdirect.org</p>
        <h3>Verwendung von Cookies</h3>
        <p>Eine Nutzung des Angebotes von OpenFoodBank erfolgt mit dem Einsatz eines Cookies. Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Browsereinstellungen aktiviert haben. <br/>
        In dem Cookie wird ein zufällig generierter Session-Code und gegebenenfalls Ihre Kunden-ID gespeichert. Damit ist es möglich, Sie als registrierter Kunden zu erkennen.<br/>
        Zusätzlich speichert OpenFoodBank, falls vorhanden, eine Affiliate-ID und die Seite, von der aus Sie auf unsere Seiten gekommen sind.<br/>
        Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Einstellungen aktiviert haben.</p>
        <h3>Änderungen dieser Erklärung</h3>
        <p>Soweit wir neue Produkte oder Dienstleistungen einführen, Internet-Verfahren ändern oder wenn sich die Internet- und EDV-Sicherheitstechnik weiterentwickelt, ist die Datenschutzerklärung zu aktualisieren. Wir behalten uns deshalb das Recht vor, die Erklärung nach Bedarf zu ändern oder zu ergänzen. Die Änderung werden wir an dieser Stelle veröffentlichen. Daher sollten Sie diese Website regelmäßig aufrufen, um sich über den aktuellen Stand der Datenschutzerklärung zu informieren.</p>
    </div>
</div>
