<div class="row">
    <div class="col bg-light border m-3">
        <h2>Gesetzliche Bestimmungen</h2>
        <h3>Vertragsschluss und Speicherung der Bestellung</h3>
        <p>Bei Bestellungen in unserem Onlineshop kommt der Vertrag zustande mit den jeweiligen Spendern, bei denen Sie bestellen.</p>
        <p>Die Sachspendenbörse bzw. dessen Betreiber (Fairdirect e.V., Konrad-Becker-Str. 11, 35102 Lohra) wird nicht Vertragspartner hinsichtlich der über die Onlineshops der Spender oder über das Spendenportal sachspendenbörse.org bestellten Spenden. Die Sachspendenbörse nimmt im Namen der Spender lediglich die Spendenvermittlung vor.</p>
        <p>Ihre Bestellung stellt ein Angebot an das jeweilige Unternehmen zum Abschluss eines Kaufvertrags dar. Nach Eingang der Bestellung wird die Sachspendenbörse Sie über den Eingang Ihrer Bestellung per E-Mail informieren (Bestellbestätigung) und nimmt Ihr Angebot namens und in Vollmacht des Spenders an. Der Spender kann das Angebot innerhalb von zwei Wochen ab Eingang des Angebots des Bestellers auf der Sachspendenbörse annehmen.</p>
        <p>Bei der Bestellung über die Onlineshops auf dem Sachspendenbörse- Marktplatz umfasst der Bestellvorgang insgesamt 6 Schritte. Wenn Sie bereits die Bedingungen für ein Sachspendenbörse-Bestellkonto erfüllt haben und dieses von Sachspendenbörse freigeschaltet wurde, können Sie sich mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort anmelden.</p>
        <p>Im zweiten Schritt geben Sie Ihre Kundendaten einschließlich Rechnungsanschrift und ggf. abweichender Lieferanschrift ein. Im dritten Schritt wählen Sie, wie Sie bezahlen möchten (optionaler Versand). Im Schritt 4 haben Sie unter "Prüfen und Bestellen" die Möglichkeit, sämtliche Angaben (z.B. Name, Anschrift, Zahlungsart, bestellter Artikel) nochmals zu überprüfen und ggf. zu ändern, bevor Sie Ihre Bestellung durch Betätigen des Buttons "Jetzt bestellen" an uns versenden. </p>
        <p>Sie haben optional die Möglichkeit, ein Kundenkonto ohne Bestellmöglichkeit anzumelden. Dadurch können Sie mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort Newsletter von der Sachspendenbörse bestellen und den Newsletterstatus bearbeiten</p>
        <p>Bei der telefonischen Bestellung werden wahlweise einige Daten Ihres Sachspendenbörse- Bestellkontos mündlich bei Ihnen abgefragt und anschließend der Eingang der Bestellung per E-Mail an Ihre angegebene E-Mailadresse bestätigt. </p>
        <h3>Zahlungsbedingungen</h3>
        <p>Fallen optionale Versandkosten an, werden diese mit Abschluss des Kaufvertrages zur Zahlung fällig. </p>
        <p>Die Zahlung erfolgt über den Treuhandservice der Sachspendenbörse, per Vorkasse durch Vorab-Überweisung, per Kreditkarte, per Sofortüberweisung oder per Lastschrifteinzug. Wir behalten uns vor, einzelne Zahlungsarten auszuschließen. Bei Wahl der Zahlungsart Vorkasse nennen wir Ihnen die Bankverbindung des Treuhandservices der Sachspendenbörse in der Bestellbestätigung.</p>
        <p>Für den Fall der Nichteinlösung oder Rückgabe einer Lastschrift macht die Sachspendenbörse einen Schadenersatz in Höhe von EUR 15,00 geltend. Dem Besteller steht der Nachweis frei, dass ein Schaden nicht oder wesentlich niedriger entstanden ist. </p>
        <p>Der Besteller ermächtigt seine Bank außerdem unwiderruflich, der Sachspendenbörse seinen Namen und seine aktuelle Anschrift mitzuteilen. </p>
        <p>Mit Eintritt des Zahlungsverzugs sind die Versandkosten während des Verzuges in Höhe von 5% über dem Basiszinssatz zu verzinsen. Wir behalten uns vor, einen höheren Verzugsschaden nachzuweisen und geltend zu machen.</p>
        <p>Ein Recht zur Aufrechnung steht Ihnen nur dann zu, wenn Ihre Gegenansprüche rechtskräftig gerichtlich festgestellt oder unbestritten sind oder schriftlich durch uns anerkannt wurden.</p>
        <p>Sie können ein Zurückbehaltungsrecht nur ausüben, soweit die Ansprüche aus dem gleichen Vertragsverhältnis resultieren.</p>
    </div>
</div>
