<div class="row">
    <div class="col bg-light border m-3">
        <h2>Impressum</h2>
        <p>Sachspendenbörse<br/>
        Fairdirect e.V.<br/>
        Konrad-Becker-Str. 11<br/>
        35102 Lohra<br/>
        Deutschland</p>
        <p>Vorstand: Micha Gattinger, Matthias Ansorg (ladungsfähige Adresse ist bei allen Vorstandsmitgliedern die Adresse des Vereinssitzes – siehe oben)<br/>
        Inhaltlich Verantwortlicher gemäß § 6 MD und § 55 Abs. 2 RStV: Micha Gattinger<br/>
        Datenschutzbeauftragter: Matthias Ansorg<br/>
        Registergericht: Amtsgericht Marburg<br/>
        Registernummer: VR5321<br/>
        Steuernummer: 031 250 52117</p>
        Fairdirect e.V. ist als gemeinnützig anerkannt. Die Einhaltung der satzungsgemäßen Voraussetzungen nach §§ 51, 59, 60 und 61 AO wurde vom Finanzamt Marburg mit Bescheid vom 08.11.2016 und 28.09.2020 festgestellt.<br/>
        <p>Kontakt<br/>
        E-Mail: mail@Fairdirect.org<br/>
        Telefon: +49 6426 8630364</p>
        <p>Weitere Hinweise<br/>
        Die Informationen auf dieser Website werden regelmäßig überprüft und aktualisiert. Trotz aller Sorgfalt können sich Informationen geändert haben. Eine Haftung oder Garantie für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung gestellten Informationen kann daher nicht übernommen werden. Gleiches gilt auch für alle anderen Webseiten, auf die mittels Hyperlink verwiesen wird. Sachspendenbörse ist für den Inhalt der Webseiten, die aufgrund einer solchen Verbindung erreicht werden, nicht verantwortlich. Des weiteren behalten wir uns das Recht vor, Änderungen oder Ergänzungen der bereitgestellten Informationen vorzunehmen.</p>
        <p>Inhalt und Struktur dieser Webseiten sind geschützt. Die Vervielfältigung von Informationen oder Daten, insbesondere die Verwendung von Texten, Textteilen oder Bildmaterial, bedarf der vorherigen Zustimmung durch uns.</p>
        <p>&copy; Sachspendenbörse <?= date('Y', time()) ?>. Alle Rechte vorbehalten.</p>
    </div>
    
</div>
