<div class="row">
    <div class="col bg-light border m-3">
        <h2>Impressum</h2>
        <p>Epelia<br/>
        Warenhandel Gattinger<br/>
        Konrad-Becker-Str. 11<br/>
        35102 Lohra<br/>
        Deutschland</p>
        <p>Geschäftsführer: Micha Gattinger<br/>
        Inhaltlich Verantwortlicher gemäß § 6 MDStV: Micha Gattinger<br/>
        Datenschutzbeauftragte: Matthias Ansorg<br/>
        Umsatzsteuer-Ident-Nr.: DE-163752546</p>
        <p>Kontakt<br/>
        E-Mail: mail@epelia.com<br/>
        Telefon: 01803 465283 ("0180 EINKAUF") (9 ct/min aus dem Deutschen Festnetz; aus Mobilfunknetzen können abweichende Preise gelten)</p>
        <p>Weitere Hinweise<br/>
        Die Informationen auf dieser Website werden regelmäßig überprüft und aktualisiert. Trotz aller Sorgfalt können sich Informationen geändert haben. Eine Haftung oder Garantie für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung gestellten Informationen kann daher nicht übernommen werden. Gleiches gilt auch für alle anderen Webseiten, auf die mittels Hyperlink verwiesen wird. Epelia ist für den Inhalt der Webseiten, die aufgrund einer solchen Verbindung erreicht werden, nicht verantwortlich. Des weiteren behalten wir uns das Recht vor, Änderungen oder Ergänzungen der bereitgestellten Informationen vorzunehmen.</p>
        <p>Inhalt und Struktur dieser Webseiten sind geschützt. Die Vervielfältigung von Informationen oder Daten, insbesondere die Verwendung von Texten, Textteilen oder Bildmaterial, bedarf der vorherigen Zustimmung durch uns.</p>
        <p>&copy; Epelia <?= date('Y', time()) ?>. Alle Rechte vorbehalten.</p>
    </div>
    
</div>
