<div class="row">
    <div class="col bg-light border m-3">
        <h2>Kontakt</h2>
        <p><b>Sie erreichen Epelia für Ihre telefonische Anfrage</b><br/>
        von Montag bis Freitag<br/>
        in der Zeit von 9.00 Uhr bis 18.00 Uhr<br/>
        unter Telefon 01803 465283 ("0180 EINKAUF"). (9 ct/min aus dem Deutschen Festnetz; aus Mobilfunknetzen können abweichende Preise gelten).<br/>
        <br/>
        <b>Oder kontaktieren Sie uns per E-Mail</b><br/>
        E-Mail Adresse:  mail@epelia.com</p>
    </div>
</div>
