<div class="row">
    <div class="col bg-light border m-3">
        <h2>Kontakt</h2>
        <p><b>Sie erreichen OpenFoodBank für Ihre telefonische Anfrage</b><br/>
        von Montag bis Freitag<br/>
        in der Zeit von 16.00 Uhr bis 18.00 Uhr<br/>
        unter Telefon +49 6426 8630364.<br/>
        <br/>
        <b>Oder kontaktieren Sie uns per E-Mail</b><br/>
        E-Mail Adresse:  mail@fairdirect.org</p>
    </div>
</div>
