<div class="row">
    <div class="col bg-light border m-3">
        <h2>Nutzungsbedingungen</h2>
        <h3>Präambel</h3>
        <p>Diese Nutzungsbedingungen regeln abschließend das Rechtsverhältnis zwischen Fairdirect e.V. (nachfolgend "OpenFoodBank") und den Kunden, welche den Internet Marktplatz unter OpenFoodBank.Net nutzen und Spenden vermitteln. <br/>
        Das Vertragsverhältnis zwischen der OpenFoodBank und den Spendern wird durch einen eigenen Vertrag geregelt. <br/>
        Schenkungsverträge, welche über den Internet-Marktplatz OpenFoodBank.Net zustande kommen, gelten ausschließlich zwischen dem Spender und dem Spendenempfänger. <br/>
        Die OpenFoodBank wird nicht Partei dieser Verträge. Der OpenFoodBank erwachsen keinerlei Verpflichtungen im Hinblick auf die Erfüllung der zwischen den Spendern und Spendenempfängern zustande gekommenen Verträge</p>
        <h3>Registrierung</h3>
        <p>1. Die Nutzung von der OpenFoodBank zur Vermittlung von Spenden ist nur Nutzern möglich, welche von der OpenFoodBank freigegeben sind. <br/>
        2. Für verschiedene Funktionen, wie das Speichern von Artikeln auf der Merkliste, das Kontaktieren von anderen Mitgliedern, die Kommentar- und Produktbewertungsfunktion sowie das Kaufen von Artikeln ist eine Registrierung als Mitglied erforderlich.<br/>
        3. Die Registrierung ist nur juristischen Personen und unbeschränkt geschäftsfähigen natürlichen Personen erlaubt. Minderjährigen ist eine Anmeldung untersagt. <br/>
        4. Die Anmeldung einer juristischen Person darf nur von einer vertretungsberechtigten natürlichen Person vorgenommen werden, die namentlich genannt werden muss. Bei der Anmeldung dürfen nur einzelne Personen als Inhaber des Mitgliedskontos angegeben werden.<br/>
        5. Die bei der Anmeldung abgefragten Daten sind vollständig und wahrheitsgemäß anzugeben. Spezielle Nachweise wie z.B. Freistellungsbescheide sind durch Nutzer stets auf dem neuesten Stand zu halten.<br/>
        6. Bei der Anmeldung wählt das Mitglied einen Benutzernamen und ein Passwort. Das Mitglied darf sein Passwort nicht an Dritte weitergeben. <br/>
        7. Ein Mitgliedskonto ist nicht übertragbar.<br/>
        8. Die OpenFoodBank behält sich das Recht vor, ein Mitgliedskonto zu löschen, insbesondere bei Missbrauch, widerholt nicht abgenommener Bestellungen oder einem Verfallen der Zugangsberechtigung (z.B. Wegfall der Gemeinnützigkeit),<br/>
        im Fall der Verwendung von Benutzernamen, welche gegen gesetzliche Verbote, die Rechte Dritter oder die guten Sitten verstoßen oder im Fall einer unvollständigen Anmeldung (z.B. bei nicht eingegebenem Bestätigungscode).</p>
        <h3>Haftung</h3>
        <p>1. Die OpenFoodBank haftet für Vorsatz und grobe Fahrlässigkeit seiner Organe, Mitarbeiter und Erfüllungsgehilfen uneingeschränkt, für leichte Fahrlässigkeit jedoch nur bei der Verletzung vertragswesentlicher Pflichten. Die Haftung bei Verletzung einer solchen vertragswesentlichen Pflicht ist auf den vertragstypischen Schaden begrenzt, mit dessen Entstehen Epelia bei Vertragsabschluss auf Grund der im Zeitpunkt des Vertragschluss bekannten Umstände rechnen musste. Unberührt hiervon ist die Haftung wegen Verzugs.<br/>
        2. Die OpenFoodBank haftet nicht für die Richtigkeit der durch den Spender eingestellten Angaben zum Spendengegenstand.<br/>
        3. Für nicht zu vertretende Störungen innerhalb des Leitungsnetzes übernimmt die OpenFoodBank keine Haftung.<br/>
        4. Für den Verlust von Daten haftet die OpenFoodBank nur dann, wenn ein solcher Verlust durch angemessene Datensicherungsmaßnahmen seitens des Nutzers nicht vermeidbar gewesen wäre.<br/>
        5. Wegen der von Zeit zu Zeit erforderlichen Wartungsarbeiten am Internet Marktplatz kann die OpenFoodBank nicht gewährleisten, dass der Zugang zu OpenFoodBank.Net jederzeit und ohne Unterbrechungen möglich ist. Hieraus können gegen die OpenFoodBank keine Ansprüche hergeleitet werde.<br/>
        6. Die vorgenannten Haftungsausschlüsse und Beschränkungen gegenüber Nutzer gelten nicht im Fall der Übernahme ausdrücklicher Garantien durch die OpenFoodBank und für Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit sowie im Fall zwingender gesetzlicher Regelungen.</p>
        <h3>Änderung der Nutzungsbedingungen</h3>
        <p>Die OpenFoodBank behält sich das Recht vor, diese Nutzungsbedingungen jederzeit und ohne Nennung von Gründen zu ändern. Die OpenFoodBank wird den Nutzern per E-Mail spätestens zwei Wochen vor ihrem Inkrafttreten die Änderungen mitteilen. Widerspricht ein Nutzer der Geltung der neuen Nutzungsbedingungen nicht innerhalb von zwei Wochen nach Empfang der E-Mail, gelten die geänderten Nutzungsbedingungen als angenommen. Die OpenFoodBank wird die Mitglieder in der E-Mail, die die geänderten Bestimmungen enthält, auf die Bedeutung dieser Zweiwochenfrist gesondert hinweisen.</p>
        <h3>Schlussbestimmungen</h3>
        <p>1. Erklärungen gegenüber der OpenFoodBank bedürfen der Textform. Mündliche Willenserklärungen sind unwirksam.<br/>
        2. Es gilt das Recht der Bundesrepublik Deutschland unter Ausschluss des UN-Kaufrechts. Ausschließlicher Gerichtsstand für alle Streitigkeiten aus dem Nutzungsverhältnis ist Marburg.<br/>
        3. Sollten einzelne Bestimmungen dieser Nutzungsbedingungen unwirksam sein oder werden und/oder den gesetzlichen Regelungen widersprechen, so wird hierdurch die Wirksamkeit der Bedingungen im Übrigen nicht berührt. Die unwirksame Klausel gilt durch eine Regelung ersetzt, welche der unwirksamen wirtschaftlich am nächsten kommt.</p>
    </div>
</div>
