<div class="row">
    <div class="col bg-light border m-3">
        <h2>Versand und Lieferung</h2>
        <div class="relevant_content">
            <h3>Wie erfolgt die Lieferung?</h3>
            <p>Ihre Bestellung über Epelia geht sofort zum Anbieter. In der Regel packt dieser Ihr Paket noch am selben, spätestens jedoch am darauffolgenden Tag. Der Versand erfolgt im regionalen Liefergebiet innerhalb weniger Stunden nach Versandbereitschaft des Paketes, außerhalb des regionalen Liefergebietes dauert der Versand je nach Logistikunternehmen 1-2 Werktage. Ihre Produkte werden immer direkt vom Anbieter an Sie versendet.</p>
            <h3>Wie wird Frischware versendet?</h3>
            <p>Kühlpflichtige Produkte werden in speziellen Kühlkartons mit Kühlelementen versendet. Diese halten Ihre Ware garantiert bis zu Ihrer Ankunft bei Ihnen frisch.</p>
            <h3>Wie hoch sind die Versandkosten?</h3>
            <p>Jeder Anbieter bzw. jede Versandzelle kalkuliert die Versandkosten selbst. Sie finden die Höhe der Versandkosten im jeweiligen Shop bzw. in der jeweiligen Versandzelle unter Lieferung &amp; Versand.<br />
    Viele Anbieter bzw. Versandzellen bieten einen bestimmten Betrag an, ab dem die Versandkosten für Sie entfallen. Die Information finden Sie ebenfalls unter Lieferung &amp; Versand des jeweiligen Anbieters bzw. der jeweiligen Versandzelle.</p>
            <h3>Was sind Epelia Versandzellen?</h3>
            <p>Unsere <a href="/womas/musterwochenmarkt1/">regionalen Versandzellen</a> bieten Kunden die Möglichkeit, bei mehreren Anbietern einzukaufen, aber nur einmal Versand zu bezahlen.<br/>
            Egal ob Supermarkt, Einkaufscenter, Wochenmarkt oder auch Fußgängezonen oder Innenstädte, überall haben sich Händler zu einer Zweckgemeinschaft an einem Ort zusammengefunden. Eine historisch gewachsene Struktur, ein bewährtes System.<br/>
            Anders als bei einem reinen Onlinshop möchten wir diese Strukturen nutzen und so unterstützen. So können Kunden Waren vorbestellen und vor Ort abholen, komplett online einkaufen bei den ihnen bekannten Anbietern, oder nach einem Einkauf vor Ort ihre Einkäufe bequem nach Hause liefern lassen.</p>
            <h3>Was ist die Tramit-Versandlösung von Epelia?</h3>
            <p>Tramit ist eine marktreife Innovation von Epelia, um regionale Lieferungen am selben Tag und besonders kosteneffizient abwickeln zu können. Tramit ist unsere Logistiklösung für die regionalen Versandzellen von Epelia. Lieferanfragen werden in Echtzeit an registrierte Dienstleister weitergegeben und bei Bedarf von diesen angenommen. Dienstleister können so gezielt Leerfahrten ihrer bestenden Touren minimieren und Fahrten besser auslasten. Optional kann unsere Tramit-Lösung mit dem kombinierten Versand der regionalen Versandzellen von Epelia kombiniert werden Das spart eigene Besorgungsfahrten, entlastet die Straßen in den Innenstädten, und macht den regionalen Handel auch online zu einer echten Alternative.</p>
        </div>
    </div>
</div>
