<div class="row">
    <div class="col bg-light border m-3">
        <h2>Versand und Lieferung</h2>
        <div class="relevant_content">
            <h3>Wie erfolgt die Lieferung?</h3>
            <p>Alle Spendenangebote auf der Sachspendenbörse sind standardmäßig Click and Collect.</p>
            <h3>Was ist die Sachspendenbörse- Transportbörse?</h3>
            <p>Ist eine Abholung vor Ort nicht möglich, bietet die Sachspendenbörse eine Transportbörse auf Basis von Leerfahren von Transportdienstleistern an.</p>
            <h3>Kann der Spender auch einen Versand anbieten?</h3>
            <p>Manchmal verfügen spendende Firmen z.B. mit einen eigenen Fuhrpark über eine eigene Transportmöglichkeit. In diesem Fall beiet der Spender einen kostenpflichtigen Versand im ansonsten kostenlosen Spendenangebot mit an. Dieser kann vom Spendenempfänger im Bestellprozess optional zur Selbstabholung gewählt werden.<br/>
            <h3>Was sind Sachspendenbörse Versandzellen?</h3>
            <p>Hier können mehrere Spender eine gemeinschaftliche Abholmöglichkeit bzw. Versandmöglichkeit anbieten. Ideal um z.B. übrige Lebsnmittel vom Markttag gemeinschaftlich zu spenden<br/>
         </div>
    </div>
</div>
