<style>
    label{
        display:inline-block;
    }

    label input{
        display:inline;
        float:left;

    }

    input[type="checkbox"]{
        margin:2px;
    }

</style>
<div class="row">
    <div class="col bg-light border m-3">
        <h1><?= $this->translate('business_product_edit_headline') ?></h1>
        <?= $this->form; ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){

        switch($('#producttype').val()) {
            case 'offer':
                $('#wholesale_1-element').show();
                $('#price_normal_1-element').hide();
                break;
            case 'request':
                $('#wholesale_1-element').hide();
                $('#price_normal_1-element').show();
                break;
            default:
                $('#price_normal_1-element').hide();
                $('#wholesale_1-element').hide();
        }

        if($('#unlimited_stock').attr('checked')){
            $('#stock').attr('disabled', 'disabled');
        }
    });
    $('#producttype').change(function(){
        switch($('#producttype').val()) {
            case 'offer':
                $('#wholesale_1-element').show();
                $('#price_normal_1-element').hide();
                break;
            case 'request':
                $('#wholesale_1-element').hide();
                $('#price_normal_1-element').show();
                break;
            default:
                $('#price_normal_1-element').hide();
                $('#wholesale_1-element').hide();
        }
    });
    $('#type').change(function(){ 
        $.ajax({ 
            url: '/ajax/getgroups/type/' + $('#type').val(), 
            datatype: 'html', 
            success: function(data){ 
                $('#group_id').empty().html(data); 
                $('#category_id').empty(); 
            } 
        }); 
    });
    $('#group_id').change(function(){
        $.ajax({
            url: '/ajax/getcategories/group/' + $('#group_id').val(),
            datatype: 'html',
            success: function(data){
                $('#category_id').empty().html(data);
            }
        });
    });
    $('#unlimited_stock').click(function(){
        if($('#unlimited_stock').is(':checked')){
            $('#stock').attr('disabled', 'disabled');
        }
        else{
            $('#stock').removeAttr('disabled');
        }
    });
</script>