<div class="row">
    <div class="col bg-light border m-3">
        <h1><?= $this->translate('business_products_headline') ?></h1>
        <a href="/business/products/edit/"><?= $this->translate('business_products_new') ?></a>
        <h2><?= $this->translate('business_products_headline') ?></h2>
        <table id="productTable" class="table table-striped table-bordered">
            <thead>
                <tr><th><?= $this->translate('business_products_name') ?></th><th><?= $this->translate('misc_type') ?></th><th><?= $this->translate('business_products_active') ?></th><th><?= $this->translate('business_products_amount') ?></th><th><?= $this->translate('business_products_creation') ?></th><th><?= $this->translate('misc_actions') ?></th></tr>
            </thead>
            <tbody>
        <?php
        foreach($this->products as $product):
        ?>
                <tr>
                    <td><?= $this->escape($product->name) ?></td>
                    <td><?= ($product->producttype == 'request') ? $this->translate('misc_request') : $this->translate('misc_offer') ?></td>
                    <td><?= ($product->active) ? $this->translate('misc_yes') : $this->translate('misc_no') ?></td>
                    <td><?= ($product->producttype == 'request' || is_null($product->stock)) ? $this->translate('misc_unlimited') : $this->escape($product->stock) ?></td>
                    <td><?= date('d.m.Y' , strtotime($product->created)) ?></td>
                    <td>
                        <a href="/business/products/edit/id/<?= $this->escape($product->id) ?>"><?= $this->translate('misc_edit') ?></a><br />
                        <a href="/business/products/pictures/id/<?= $this->escape($product->id) ?>/"><?= $this->translate('misc_pictures') ?></a><br />
        <?php if($product->active): ?>
                        <a href="/business/products/deactivate/id/<?= $this->escape($product->id) ?>/" title="<?= $this->translate('misc_deactivate') ?>"><?= $this->translate('misc_deactivate') ?></a>
        <?php else: ?>
                        <a href="/business/products/activate/id/<?= $this->escape($product->id) ?>/"  title="<?= $this->translate('misc_activate') ?>"><?= $this->translate('misc_activate') ?></a>
        <?php endif; ?>
                        <br />
                        <a href="/business/products/delete/id/<?= $this->escape($product->id) ?>/"><?= $this->translate('misc_delete') ?></a>
                    </td>
                </tr>
        <?php
        endforeach;
        ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#productTable').dataTable({
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                { "bSortable": false, bSearchable: false }
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
           
</script>
