<h1><?= $this->translate('business_products_pictures_headline') ?></h1>
<input id="fileupload" type="file" name="file" data-url="/business/products/pictures/" /><span id="please_wait" style="display:none;"><img src="/images/business/pic_loading.gif" alt="Bitte warten..."/> Bitte warten...</span>
<table class="table" id="bilder">
    <thead>
        <tr><td>Auswahl</td><td></td><td>Standard-Bild?</td></tr>
    </thead>
    <tbody>
        
<?php foreach($this->product->getPictures() as $pic): ?>
    <tr><td><input class="check_delete_pic" type="checkbox" name="imagesDelete[]" value="<?= $this->escape($pic->id) ?>" /></td><td><img style="width:120px;" src="/img/products/174x136/<?= $this->escape($pic->filename) ?>" alt=""></td><td><input type="checkbox" name="is_default" class="check_default" value="<?= $pic->id ?>" onclick="setDefaultPic('<?= $pic->id ?>')"<?php if($this->product->main_picture_id == $pic->id): ?> checked="checked"<?php endif; ?> /></td></tr>
<?php endforeach; ?>
    </tbody>
</table>
<button class="btn" id="delete_pictures"><?= $this->translate('business_products_pictures_delete') ?></button>

<script src="/js/libs/jquery.iframe-transport.js"></script>
<script src="/js/libs/jquery.fileupload.js"></script>
<script>
    $(document).ready(function(){
        $('#delete_pictures').click(function(){
            $('.check_delete_pic').filter(':checked').each(function(){
                var pic = $(this);
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "/business/products/deletepicture/",
                    data: { id: pic.val() }
                }).done(function( res ) {
                    if(res.suc){
                        pic.parent().parent().remove();
                    }
                });
            });
        });
    });

    function setDefaultPic(picId){
        $.ajax({
            type: "POST",
            dataType: 'json',
            url: "/business/products/setdefaultpicture/",
            data: {
                id : picId,
                product_id : <?= $this->product->id ?>
            }
        }).done(function(res){
            if(res.suc){
                $('.check_default').each(function(){
                    if($(this).val() != picId){
                        $(this).attr('checked', false);
                    }
                });
            }
            else{
                alert('Fehler: ' + res.msg);
            }
        });
    }

    $(function () {
        $('#fileupload').fileupload({
            dataType: 'json',
            formData: {id: <?= $this->escape($this->product->id) ?>},
            send: function(e, data){
		$('#please_wait').show();
            },
            done: function (e, data) {
		$('#please_wait').hide();
                if(data){
                    $('#bilder').append(data.result.data);
                }
                else{
                    alert('Upload nicht erfolgreich');
                }
            }
        });
    });    

</script>
