<h1 style="margin-bottom:5px;">Einheiten</h1>
<a href="/admin/units/edit/">Neue Einheit anlegen</a>
<table class="table" id="unitTable">
    <thead>
    <tr><th>Einzahl</th><th>Mehrzahl</th><th>Aktionen</th></tr>
    </thead>
    <tbody>
<?php foreach($this->units as $unit): ?>
        <tr><td><?= $this->escape($unit->singular) ?></td><td><?= $this->escape($unit->plural) ?></td><td><a href="/admin/units/edit/id/<?= $this->escape($unit->id) ?>">Editieren</a></td></tr>
<?php
endforeach;
?>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        $('#unitTable').dataTable({
            "aoColumns": [
                null,
                null,
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
           
</script>
