<div id="content_business">  
    <div id="rightcontent" class="account">        
        <p class="clear">&nbsp;</p>     
        <h1 class="business_h1">Condizioni generali di contratto Epelia</h1>
        <p class="clear">&nbsp;</p>
        <p style="font-size:13px; line-height:21px;">
<h4>0. Preambolo</h4>1. Il commercio di prodotti Micha Gattinger (successivamente Epelia) gestisce il portale web www.epelia.de, sul quale gli imprenditori ai sensi dell’articolo §14 del codice civile e le persone giuridiche del diritto privato (successivamente venditori) hanno la possibilità, in conformità alle direttive di queste condizioni generali di contratto, di distribuire prodotti alimentari sul negozio online della piattaforma Epelia. www.epelia.de è concepito come piattaforma di mercato in Internet, sulla quale tutte le attività di acquisto del cliente per tutti i negozi web aderenti vengono gestite centralmente attraverso un carrello.<br/>
<br/>
2. In conclusione, tali condizioni generali di contratto contengono le condizioni vigenti tra Epelia e i venditori. Modifiche a riguardo possono essere fatte esclusivamente da Epelia, in forma scritta.<br/>
<br/>
<h4>1. Prestazioni Epelia</h4>1. Epelia mette a disposizione dei commercianti per le proprie attività di commercio un negozio online standardizzato sulla piattaforma Epelia. Nel processo di vendita, Epelia esercita la funzione di offerente, il quale realizza misure di marketing, si assume il disbrigo dei pagamenti, e offre supporto personale nei processi d’ordine, spedizione e reso.<br/>
<br/>
2. Sulla piattaforma Epelia gli articoli di tutti i venditori vengono organizzati in diverse categorie e pubblicizzati in diversi modi, soprattutto attraverso il collegamento ad altri siti web, pubblicazione sui media, e pubblicità di offerte via E-mail ai membri della community Epelia.<br/>
<br/>
3. Epelia si riserva il diritto di modificare o estendere i contenuti e la struttura della piattaforma Epelia e la relativa interfaccia venditore, quando ciò non pregiudica, o non pregiudica in modo considerevole, la realizzazione degli obiettivi del contratto concluso con il cliente. Epelia provvederà ad informare i venditori della piattaforma Epelia riguardo a eventuali modifiche. Epelia è autorizzato a ridurre temporaneamente e in misura ragionevole le proprie prestazioni, in caso ciò fosse necessario all’attuazione di misure tecniche e all’esecuzione di lavori di manutenzione. I venditori verranno informati in anticipo riguardo ai suddetti lavori.<br/>
<br/>
<h4>2. Autorizzazione all’utilizzo</h4>1. La condizione necessaria per l’utilizzo della piattaforma Epelia è l’autorizzazione concessa da Epelia al venditore.<br/>
<br/>
2. La procedura per l’autorizzazione all’utilizzo è regolata in conformità all’allegato 2. L’ammissione avviene attraverso l’abilitazione del negozio online e o attraverso l’invio di un’autorizzazione via E-mail. Con l’autorizzazione viene concluso un contratto di prestazione tra Epelia e il relativo venditore.<br/>
<br/>
3. Fino all’abilitazione dello shop online Epelia, non sussiste alcun diritto alla vendita di articoli sulla piattaforma Epelia.<br/>
<br/>
4. Il venditore garantisce che le dichiarazioni fatte nell’ambito della richiesta di autorizzazione sono vere e complete. Si impegna a comunicare ad Epelia eventuali modifiche o cambiamenti futuri riguardanti le informazioni rilasciate. Prova le qualità imprenditoriali attraverso gli opportuni documenti.<br/>
<br/>
<h4>3. Obblighi del venditore</h4>1. Con la richiesta di autorizzazione, il venditore si impegna a regolare la vendita in conformità all’allegato 2 e tutte le operazioni di pagamento in conformità all’allegato 3., e di non eludere le regolamentazioni di queste condizioni generali di contratto o di integrarle attraverso regolamentazioni modificate o altre regolamentazioni.<br/>
<br/>
2. Il venditore si impegna inoltre a gestire tutte le attività sulla piattaforma Epelia mediante l’utilizzo esclusivo dello shop online messo a disposizione da Epelia, e di non apportare cambiamenti o modifiche al suddetto.<br/>
<br/>
3. Il venditore si impegna a vendere sulla piattaforma Epelia esclusivamente prodotti alimentari e beni di prima necessità, in conformità all’allegato 1.<br/>
<br/>
4. Il venditore è obbligato a mantenere segreti i dati di Login e Password, e di proteggerli dall’accesso ingiustificato di terzi. Se dovesse sorgere il sospetto di usurpazione da parte di terzi, il venditore ha l’obbligo di informare immediatamente Epelia a riguardo. Non appena Epelia sarà a conoscenza dell’utilizzo non autorizzato, provvederà a bloccare l’accesso del venditore non autorizzato. Epelia si riserva il diritto di modificare il Login e la Password di un venditore; in tal caso Epelia provvederà ad informare immediatamente il venditore a riguardo.<br/>
<br/>
5. Il venditore acconsente che la conferma di autorizzazione, indicazioni riguardo ad eventuali adattamenti del Software Epelia-Shop, e modifiche del contratto avvengano via E-mail.<br/>
<br/>
<h4>4. Violazioni degli obblighi del venditore</h4>1. Nel caso dovesse esserci un sospetto ragionevole riguardo alla violazione del contratto o di queste condizioni generali di contratto da parte del venditore, Epelia provvederà ad ammonire il venditore e darà lui la possibilità di rimediare alla violazione del contratto. Nel caso in cui non si rimedi alla violazione di contratto entro i termini prestabiliti, Epelia è autorizzato a revocare l’autorizzazione e a bloccare l’accesso alla piattaforma Epelia.<br/>
<br/>
2. Epelia si riserva il diritto di cancellare offerte e di rimuoverle dalla piattaforma Epelia, anche quando l’offerta di tali articoli non è contraria al regolamento di legge.<br/>
<br/>
<h4>5. Indennità</h4>1. L’iscrizione e la creazione di un negozio virtuale su Epelia sono gratuite.<br/>
<br/>
2. Epelia impone al venditore una commissione sui contratti di vendita conclusi sulla piattaforma Epelia. L’ammontare della commissione varia in base alle attuali condizioni di prezzo. Si applica un tasso di commissioni par al 4% del valore lordo, più IVA.<br/>
<br/>
3. Il venditore acconsente alla compensazione della commissione derivata dal saldo del prezzo di vendita.<br/>
<br/>
4. Obiezioni alla detrazione delle commissioni possono essere indirizzate a Epelia in forma scritta entro sei settimane dalla fattura. Alla scadenza del suddetto termine la detrazione viene considerata come approvata dal venditore.<br/>
<br/>
5. Il venditore approva il salvataggio dei dati di conto a scopo dimostrativo e/o nel quadro del dovere legale di conservazione, e acconsente alla trasmissione dei conti in formato elettronico tramite Epelia.<br/>
<br/>
<h4>6. Durata del contratto, recesso</h4>1. Il contratto basato su queste condizioni è un contratto a tempo determinato.<br/>
<br/>
2. Il contratto può essere disdetto in ogni momento da Epelia o dal venditore con un anticipo di due settimane e in forma scritta.<br/>
<br/>
3. Il diritto alla disdetta per motivi importanti è sempre garantito. Un motivo importante è, per Epelia, soprattutto:<br/>
- La violazione delle disposizioni delle condizioni generali di contratto da parte del venditore, alla quale non viene posto rimedio dopo aver fissato la scadenza;<br/>
- L’atto delittuoso da parte di un venditore, o il tentativo da parte di questi, es. truffa;<br/>
- Un ritardo del venditore nell’adempire gli obblighi di pagamento superiore a sei settimane.<br/>
<br/>
<h4>7. Responsabilità</h4>1. Epelia, il suo sostituto legale e i suoi ausiliari sono responsabili in caso di intenzione o grave negligenza, solo fin dove non si tratti di violazione di un dovere contrattuale, o di lesione alla vita, al corpo o alla salute solo per quanto concerne i prevedibili. Nei casi di negligenza più lieve, però, solo per violazione di una scadenza contrattuale, tuttavia limitata ai danni prevedibili.<br/>
<br/>
2. Le responsabilità decadono completamente se il venditore procede all’attuazione di modifiche o integrazioni non autorizzate al negozio online, alle istruzioni revocabili, alle dichiarazioni relative alla protezione dei dati personali e alle condizioni generali di contratto del negozio.<br/>
<br/>
3. Epelia risponde della perdita di dati solo quando tale perdita sia risultata inevitabile nonostante le efficienti misure di protezione dei dati personali messe in atto dal cliente.<br/>
<br/>
4. Epelia non risponde dei danni alla rete di distribuzione se questi non sono causati direttamente da Epelia<br/>
<br/>
5. La responsabilità di Epelia si estende solo all’uso contrattuale delle prestazioni fornite dalla piattaforma Epelia.<br/>
<br/>
6. Epelia non risponde dell’accessibilità, della giacenza o della sicurezza delle banche dati, o dei servizi di terzi, e del contenuto dei suddetti. In particolare, Epelia non risponde della loro legalità, correttezza dei contenuti, completezza e attualità.<br/>
<br/>
<h4>8. Modifica di queste condizioni generali di contratto</h4>Epelia si riserva il diritto di modificare in ogni momento e senza bisogno di spiegazioni queste condizioni generali di contratto. Le modifiche sono comunicate al venditore via E-mail. Nel caso in cui il venditore non si opponga a tali modifiche entro due settimane dall’avvenuta comunicazione, le suddette vengono considerate concordate. Si rimanda il venditore al diritto di opposizione e alle conseguenze legali del silenzio.<br/>
	<br/>
<h4>9. Disposizioni finali</h4>1. Vengono applicate esclusivamente le norme del diritto tedesco, escludendo le normative sul commercio dell’ONU. Il luogo d’adempimento e l’esclusivo foro competente per tutte le vertenze giudiziarie è Marbung.<br/>
<br/>
2. Modifiche e integrazioni a queste condizioni generali di contratto devono avvenire in forma scritta. La stessa cosa vale nel caso di soppressione, modifica o integrazione di queste clausole.<br/>
<br/>
3. Nel caso in cui singole disposizioni di queste condizioni generali di contratto vengano annullate in parte o completamente, l’efficacia di queste condizioni generali di contratto non viene compromessa. Le parti in causa si impegnano a sostituire le clausole nulle per mezzo di regolazione, che economicamente si avvicini il più possibile alla loro volontà comune.<br/>
<br/>
<h4>10. Allegato 1: Articoli consentiti e non consentiti</h4>1. I venditori possono offrire sulla piattaforma Epelia solo prodotti alimentari e beni di prima necessità che<br/>
- documentino chiaramente il produttore o la ditta produttrice (non: prodotto per ecc.)<br/>
- non siano marche commerciali di grandi catene alimentari<br/>
- provengano direttamente dal produttore/ditta produttrice o che non vengano da questi direttamente acquistati<br/>
- prodotti alimentari che non vengano prodotti industrialmente su vasta scala<br/>
<br/>
2. Il venditore è inoltre obbligato a fornire prodotti con restrizione di età (es. alcol o prodotti contenenti alcol) nel rispetto della restrizione di età imposta dalla legge.<br/>
<br/>
3. Il venditore si impegna a offrire sulla piattaforma Epelia prodotti che possono essere offerti solo su dimostrazione prescritta dalla legge, solo nel caso in cui la documentazione sia stata inserita nella descrizione dell’offerta.<br/>
<br/>
4.  Sulla piattaforma Epelia, al venditore è proibito offrire prodotti la cui vendita ha violato, secondo l’ordinamento giuridico determinante il contratto, disposizioni legali, norme amministrative o le buone usanze. A questi appartengono in particolare i seguenti articoli:<br/>
- articoli che ledono i diritti di marchi o diritti di autori estranei;<br/>
- articoli che contengono droga, farmaci, medicinali o sostanze proibite.<br/>
<br/>
<h4>11. Allegato 2: Allestimento e attività del negozio online</h4>1. Il negozio virtuale messo a disposizione viene gestito dal sottodominio Epelia. La scelta del sottodominio Epelia avviene tramite la coordinazione da parte di Epelia. Epelia è libero di richiedere delle modifiche al sottodominio.<br/>
<br/>
2. Per accedere alle prestazioni offerte da Epelia, il venditore deve registrarsi. Con la registrazione il venditore invia una domanda di ammissione. Egli ottiene un codice di verifica via E-mail, con il quale la registrazione viene confermata. Inserendo il codice di verifica sul sito www.epelia.de al venditore viene concesso un accesso provvisorio al sistema, che gli permette l’allestimento di un proprio negozio virtuale. Una volta terminato l’allestimento, Epelia verifica la qualità e l’idoneità del negozio secondo i canoni di Epelia. Segue l’autorizzazione attraverso l’abilitazione del negozio o l’invio di una conferma di autorizzazione via E-mail. Attraverso l’autorizzazione si stabilisce un contratto di servizio tra Epelia e il relativo venditore.<br/>
<br/>
3. Il venditore si impegna a mettere in vendita esclusivamente prodotti di cui dispone liberamente e che può trasferire al cliente.<br/>
Il prezzo di un prodotto offerto su Epelia non può oltrepassare il prezzo dello stesso prodotto offerto sullo shop online del venditore.<br/>
<br/>
4. Il venditore si impegna a rispondere alle domande del cliente relative ad un prodotto o altre domande entro due giorni lavorativi.<br/>
<br/>
<h4>12. Allegato 3: Esecuzione delle operazioni di pagamento</h4>1. Il venditore acconsente al regolamento fiduciario delle operazioni di pagamento tra venditore e cliente attraverso Epelia e i suoi partner di pagamento. Epelia si fa carico delle eventuali spese da ciò risultanti.<br/>
<br/>
2. Epelia mette in conto le entrate dei pagamenti per ogni negozio il giorno 10 del mese seguente, e procede immediatamente a versare al venditore i contributi pervenuti.<br/>
<br/>
3. Il venditore può sollevare obiezioni relative alle detrazioni effettuate da Epelia entro sei settimane dal giorno in cui è stato fatto il calcolo e in forma scritta. Dopo la scadenza del suddetto termine, il calcolo viene considerato accettato dal venditore. Epelia provvederà, in particolare, ad inviare le fatture al venditore via E-mail, a prova del proprio comportamento.<br/>
<br/>
4. Epelia prenderà provvedimenti che mantengano i mancati pagamenti, ad esempio i riaddebiti, estremamente bassi. Si dovesse poi verificare un caso di mancato pagamento, Epelia si assumerà tutte le spese da esso risultanti (es. commissioni bancarie e provvigione Epelia). Il venditore si fa unicamente carico dei mancati pagamenti dei propri prodotti e delle spese di commissione.<br/>
<br/>
5. Il venditore approva il sistema di addebito e all’inoltro dei pagamenti in formato elettronico attraverso Epelia.<br/>
<br/>
6. Al venditore è proibito aggirare la struttura di provvigione di Epelia e di fare i conti direttamente con il cliente.</p>
        <p class="clear">&nbsp;</p>
    </div>
</div>

