<div id="content_static" class="">
    
    <h2>Ordinare su Epelia</h2>


    <div class="relevant_content">
    
        <h3>Perché ordinare su Epelia?</h3>
        
        <p>Epelia permette a produttori e clienti di incontrarsi. Invece di cercare in modo dispendioso il produttore di beni alimentari desiderato, i clienti hanno la possibilità di trovare tutto su questo portale. Epelia permette ai produttori di mettersi direttamente in contatto con i clienti.</p>
        
        <p class="clear space"></p>
    
        <h3>Chi può ordinare su Epelia?</h3>
        
        <p>Scegliete i prodotti che più vi piacciono, metteteli nel cestino, e andate alla cassa. Durante l’ordine potrete modificare la quantità della merce, eliminare o aggiungere prodotti al cestino. Con un solo processo d’ordine potrete ordinare e pagare prodotti di produttori diversi. Ogni venditore invierà prodotti dal proprio stabilimento a casa vostra.</p>
        
        <p class="clear space"></p>
        
        <h3>Come vengono trattati i dati personali?</h3>
        
        <p>Nel processo d’ordine dovrete vi sarà richiesto di inserire indirizzo e-mail e un indirizzo di spedizione, o meglio, di fatturazione. Abbiamo bisogno del vostro indirizzo e-mail in modo da potervi contattare nel caso in cui ci siano problemi nella spedizione. Non abbiate paura che i vostri dati personali possano finire nelle mani sbagliate: li trattiamo scrupolosamente e seguiamo le linee direttive della legge tedesca sulla protezione dei dati.</p>
        
        <p class="clear space"></p>
        
        <h3>È necessario un importo minimo per poter ordinare?</h3>
        
        <p>No, tutti i produttori spediscono la propria merce senza che ci sia bisogno di raggiungere importo minimo.</p>
        
        <p class="clear space"></p>
        
        <h3>È successivamente possibile modificare o annullare l’ordine?</h3>
        
        <p>Nel caso voleste modificare la quantità o le informazioni relative all’ordine fatecelo sapere immediatamente inviando una e-mail all’indirizzo mail@epelia.com o chiamando il numero tel.  01803 465283 ("0180 EINKAUF"; 9 ct/min dalla rete fissa tedesca; sulla rete mobile potrebbero essere applicate tariffe differenti). Ci adopereremo per  modificare l’ordine secondo le vostre richieste.</p>
        
        <p class="clear space"></p>

        <h3>Come segnalare problemi inerenti all’ordine?</h3>
        
        <p>È possibile contattare in ogni momento il servizio clienti al numero 01803 465283 ("0180 EINKAUF"; 9 ct/min dalla rete fissa tedesca; sulla rete mobile potrebbero essere applicate tariffe differenti) o  via e-mail all’indirizzo mail@epelia.com. </p>
        
        <p class="clear space"></p>
        
        <h3>È possibile ordinare via fax, e-mail o per telefono?</h3>
        
        <p>Nel caso non vi fosse possibile ordinare sulla piattaforma online Epelia, potete telefonarci o inviarci un fax o una e-mail.</p>
        
        <p class="clear space"></p>
        
        <h3>È possibile effettuare un ordine dall’estero?</h3>
        
        <p>Sì, quasi tutte le manifatture offrono l’opzione spedizione internazionale. Trovate le informazioni relative ai paesi e ai costi di spedizione nella pagina del rispettivo venditore sotto “Spedizione e consegna”.</p>        
        
    </div>

    
<div style="float:right; width:235px;">
<?= $this->partial('partials/helpbox.phtml') ?>
</div>  

</div>
