<div id="content_static" class="">
    
    <h2>Modalità di pagamento</h2>


    <div class="relevant_content">
        
        <h3>Quali metodi di pagamento offre Epelia?</h3>
        
        <table class="" cellpadding="0" cellspacing="0">
            <tr>
                <td class="method">Pagamento anticipato</td>
                <td class="description">Dopo aver concluso l’ordine su Epelia riceverete una e-mail di conferma della ricezione dell’ordine. Tale e-mail contiene tutti i dati relativi all’ordine e le informazioni relative al pagamento. Procedete quindi al versamento della somma indicata. In seguito al ricevimento del pagamento la merce verrà immediatamente spedita.</td>
            </tr>
            <tr>
                <td class="method">Bonifico istantaneo</td>
                <td class="description">Se disponete di un accesso al vostro conto attraverso online-banking potete pagare facilmente e comodamente con bonifico istantaneo. Ciò significa che riempirete e invierete il modulo di bonifico relativo al valore dell’ordinazione durante il processo di ordine. Questa modalità di pagamento è certificata TÜV e offre la sicurezza della transazione certificata TÜV.</td>
            </tr>
            <tr>
                <td class="method">Esazione bancaria</td>
                <td class="description">Con l’esazione bancaria addebitiamo l’importo sul vostro conto.<br/>
Questo tipo di pagamento è a disposizione dei clienti Epelia in possesso di un conto tedesco a partire dal terzo ordine.</td>
            </tr>
        </table>
        
        <p class="clear" style="padding-bottom:12px;"></p>
        
        <h3>Quanto è sicuro ordinare online su Epelia?</h3>
        
        <p>L’ordine avviene in tutta sicurezza. Il trasferimento di dati avviene esclusivamente attraverso una connessione sicura SSL, e questi sono al sicuro dall’accesso di terzi. Epelia GmbH adotta la severa legge tedesca sulla protezione dei dati.</p>
                
    </div>

    
<div style="float:right; width:235px;">
<?= $this->partial('partials/helpbox.phtml') ?>
</div>  

</div>

