<div id="content_static">

    <h2>Disposizioni in materia di protezione dei dati</h2>
    
    <div class="relevant_content">
        <p>
            <h4>Informativa sulla protezione dei dati</h4>

Cari clienti,<br/>
L’impresa Epelia e tutte le aziende presenti/rappresentate da Epelia si impegnano a proteggere la vostra sfera privata e i vostri dati personali e di raccogliere, utilizzare e elaborare i dati personali esclusivamente secondo la severa normativa sulla protezione dei dati.<br/>
<br/>
<strong>Raccolta dei dati</strong><br/>
Raccogliamo dati nel momento dell’avviamento, della conclusione, del regolamento e dello scioglimento del contratto d’acquisto. Tali dati saranno da noi raccolti, salvati ed elaborati.<br/>
<br/>
La vostra visita alla pagine di Epelia sarà protocollata. Praticamente saranno registrati l’indirizzo IP utilizzato attualmente dal vostro PC, la data, l’ora, il tipo di browser, il sistema operativo del vostro PC, così come le pagine web da voi contemplate. Normalmente un’identificazione personale non è possibile e nemmeno intenzionale.<br/>
Oltre a ciò, sulle pagine web vengono raccolti e registrati dati anonimizzati attraverso un software di Google Inc., normalmente da GoogleAnalytics (http://www.google.de/analytics/de-DE/), a fini commerciali e di ottimizzazione. A partire da questi dati verranno creati profili di consumatori con l’impiego di pseudonimi. Di conseguenza potrebbero essere utilizzati cookies, che raccolgono e registrano dati esclusivamente in forma anonima/con l’utilizzo di pseudonimi. I dati non vengono utilizzati per identificare l’utente e non vengono integrati con i dati riguardanti il portatore dello pseudonimo. La raccolta e il salvataggio dei dati possono essere contestati in qualsiasi momento senza effetto retroattivo. Tali dati sono rilevati per una maggiore sicurezza dei dati e per ottimizzare la nostra offerta.<br/>
<strong>Utilizzo e diffusione dei dati, valutazione del rischio</strong><br/>
I dati personali comunicati, ad esempio, nel corso di un ordine o via e-mail (es. il vostro nome, indirizzo e indirizzo e-mail) saranno trattati solo durante una corrispondenza con voi o ai fini per i quali voi avete messo i vostri dati a disposizione.<br/>
I vostri dati saranno trasmessi alla ditta incaricata della spedizione solo laddove siano necessari alla spedizione. Nel trattamento dei pagamenti, i dati di pagamento vengono trasmessi all’istituto di credito incaricati del pagamento.<br/>
Per evitarvi di ripetere ogni volta l’inserimento dei dati, salviamo i vostri dati, come indirizzi, indirizzi e-mail, nome, password, metodo di pagamento e cronologia degli ordini. Procediamo al salvataggio dei dati per permettervi, per quanto possibile, di personalizzare il vostro acquisto e per potervi fornire una competente consulenza specializzata, ad esempio, consigliandovi prodotti in base agli acquisti da voi effettuati e alle vostre ricerche o proponendovi, al nuovo acquisto, la vostra lista della spesa e i vostri ordini. O per informarvi dell’uscita di nuovi prodotti o di nuove prestazioni di servizio.<br/>
Garantiamo inoltre che i vostri dati personali non verranno trasmessi a terzi, salvo che non ne siamo obbligati legalmente o che abbiate precedentemente dato il vostro consenso. Nella misura in cui ricorriamo all’esecuzione e al disbrigo del processo di elaborazione dei servizi, i rapporti contrattuali saranno regolati secondo le disposizioni della legge federale sulla protezione dei diritti.<br/>
<br/>
<strong>Consenso e revoca</strong><br>
Inviando l’ordine accettate che i vostri dati vengano da noi rilevati, elaborati e utilizzati. I dati personali da voi comunicati possono essere eliminati in qualsiasi momento. I dati a fini di compensazione e contabilità non saranno  colpiti da una disdetta/revoca o da una cancellazione.<br/>
<strong>Memoria dei dati</strong><br/>
I dati personali comunicati attraverso il nostro sito web vengono memorizzati solo fino a quando necessario allo scopo per il quale ci sono stati affidati. Nella misura in cui si osservano i termini di conservazione di diritto commerciale e tributario, la durata di salvataggio di determinati dati può arrivare fino a 10 anni.<br/>
<strong>Conto clienti</strong><br/>
Quando aprite un conto clienti, acconsentite che i vostri dati stock, come nome, indirizzo, indirizzo e-mail e coordinate bancarie, così come i vostri dati utilizzo (username e password) vengano registrati. In tal modo, utilizzando l’username e la password che avete scelto, avrete la possibilità di effettuare ordini sulla piattaforma commerciale epelia.com e nei negozi convenzionati.<br/>
<strong>Newsletter</strong><br/>
Con l’iscrizione alla newsletter il vostro nome, cognome e indirizzo e-mail saranno utilizzati, con il vostro consenso, a scopo promozionale. L’invio della newsletter avviene attraverso l’imprenditore Epelia.<br/>
Il consenso alla ricezione della newsletter è revocabile in qualsiasi momento via e-mail. In ogni newsletter troverete un link attraverso il quale sarà possibile revocare il vostro consenso.<br/>
<strong>I vostri diritti</strong><br/>
Nel caso in cui non doveste più essere d’accordo con il salvataggio dei dati o nel caso in cui questi siano diventati inesatti, provvederemo, su vostra richiesta, ad eliminare o bloccare i vostri dati, o ad effettuare modifiche (per quanto ciò sia possibile in conformità alle norme vigenti). È possibile, su richiesta, ricevere informazioni sui vostri dati personali da noi registrati.<br/>
Nel caso di domande relative al rilevamento, all’elaborazione e all’utilizzo dei vostri dati personali, per informazioni, modifiche, blocco o eliminazione dei dati, siete pregati di rivolgervi a:<br/>
Epelia, telefono: 0180 EINKAUF (9 ct/min da rete fissa tedesca; sulla rete mobile potrebbero essere applicate tariffe differenti), e-mail: mail@epelia.com<br/>
<strong>Utilizzo di cookie</strong><br/>
L’utilizzo di Epelia avviene attraverso l’utilizzo di cookie, presupponendo che abbiate attivato i cookie nelle impostazioni del browser.<br/>
Nel cookie viene salvato un codice generato casualmente in tale sessione e eventualmente il vostro ID cliente. In tal modo è possibile riconoscervi come cliente registrato.<br/>
La premessa a tutto ciò è che abbiate attivato i cookie nelle impostazioni del vostro browser.<br/>
<strong>Modifiche a questa dichiarazione</strong>
Nel caso in cui nuovi prodotti o prestazioni di servizi venissero introdotti, le procedure di internet modificate, o se le tecniche internet e tecniche EDV si sviluppassero ulteriormente, l’informativa sulla privacy dovrà essere modificata. Ci riserviamo quindi il diritto di modificare o integrare tale dichiarazione se necessario. Le modifiche saranno pubblicate in questo spazio. È quindi necessario controllare regolarmente questo sito web per essere informati sullo stato attuale dell’informativa sulla privacy.</p>
    </div>
    
</div>
