<div id="content_static" class="">

    <h2>Disposizioni giuridiche</h2>
    
    <div class="relevant_content">
        <p>
<h4>Conclusione del contratto e salvataggio dell’ordine</h4>
Al momento dell’ordine sul nostro negozio online viene ad esistenza il contratto con le manifatture da cui effettuate l’ordine.<br/>
<br/>
L’imprenditore Epelia (Commercio di prodotti Gattinger, Konrad-Becker-Str. 11, 35102 Lohra, Telefono 01803 465283, Partita Iva DE-163752546) non diventa parte contrattuale per quanto riguarda i negozi online delle manifatture o i prodotti acquistati sul portale epelia.com. Epelia effettua, in nome delle manifatture, solo il processo d’ordine e di pagamento.<br/>
<br/>
Il vostro ordine rappresenta ,per il rispettivo imprenditore, una proposta per la conclusione di un contratto. Dopo l’emissione dell’ordine Epelia  vi informerà dell’emissione dell’ordine via e-mail (conferma dell’ordine) e accetta la vostra offerta a nome e per procura del venditore. La manifattura può accettare entro due settimane dall’emissione dell’ordine l’offerta dell’acquirente a Epelia.<br/>
<br/>
Nell’ordinazione nei negozi online del portale Epelia, il processo d’ordine comprende in tutto 6 fasi. Se avete già aperto un account-cliente su Epelia, potete accedervi inserendo il vostro indirizzo e-mail e la password da voi scelta. È tuttavia possibile ordinare da noi anche senza la creazione di un account-cliente.<br/>
<br/>
Nella seconda fase inserite i vostri dati, compreso l’indirizzo di fatturazione e eventualmente l’indirizzo di spedizione.  Nella terza fase scegliete le modalità di pagamento. Nella quarta fase, sotto “Verificare e Ordinare”, avrete la possibilità di controllare di nuovo e, eventualmente, modificare le informazioni inserite (es. nome, indirizzo, metodo di pagamento, articoli da ordinare), prima di inviarci il vostro ordine cliccando sul pulsante “Ordina adesso”.<br/>
<br/>
Avrete poi la possibilità di creare un account-cliente. In tal modo potrete effettuare ordini  sul portale epelia.com  e su altri negozi affiliati semplicemente inserendo il vostro indirizzo e-mail e la password.<br/>
<br/>
In caso l’ordine avvenga telefonicamente, vi saranno domandati i dati oralmente e, dopo il ricevimento dell’ordine, vi sarà inviata una e-mail  all’indirizzo da voi comunicato.<br/>
<br/>
<h4>Condizioni di pagamento</h4>
Il prezzo d’acquisto è dovuto alla chiusura del contratto d’acquisto.<br/>
<br/>

Il pagamento avviene attraverso il servizio fiduciario di Epelia, con pagamento anticipato tramite bonifico bancario anticipato, carta di credito, bonifico immediato, o tramite addebito diretto. Ci riserviamo il diritto di escludere alcuni metodi di pagamento. Nel caso sceglieste il pagamento anticipato come metodo di pagamento, nella conferma dell’ordine vi saranno comunicate le coordinate bancarie del servizio fiduciario di Epelia.<br/>
<br/>
In caso di mancata riscossione o di restituzione di un addebito Epelia rivendica un risarcimento di 15,00 EUR. È a discrezione del committente provare che non è risultato alcun danno o che è risultato un danno notevolmente più basso.<br/>
<br/>
Il committente autorizza inoltre la propria banca a comunicare irrevocabilmente il proprio nome e il proprio recapito.<br/>
<br/>
Se dovesse verificarsi un ritardo nel pagamento il prezzo di acquisto, a causa della mora, subirà un aumento del 5% oltre al tasso di base. Ci riserviamo la facoltà di segnalare e rivendicare un danno di mora superiore.<br/>
<br/>
Avrete diritto di compensazione solo nel caso in cui le vostre controrivendicazioni siano state accertate giudiziariamente quali legalmente valide o siano incontestate o siano state da noi accettate per iscritto.<br/>
<br/>
Potete esercitare il diritto di ritenzione solo qualora tale diritto risulti dallo stesso rapporto contrattuale.</p>        
</div>

