<div id="content_static" class="">

    <h2>Colophon</h2>
    
    <div class="relevant_content">
        <p>Epelia<br/>
Warenhandel Gattinger<br/>
Konrad-Becker-Str. 11<br/>
35102 Lohra<br/>
Germania<br/>
<br/>
Amministratore: Micha Gattinger<br/>
Responsabile dei contenuti in conformità a § 6 MDStV: Micha Gattinger<br/>
Garante della protezione dei dati: Matthias Ansorg<br/>
Nr identificativo di imposta sulle vendite: DE-163752546<br/>
<br/>
Contatti<br/>
E-Mail: mail@epelia.com<br/>
Telefono: 01803 465283 ("0180 EINKAUF") (9 ct/min dalla rete fissa tedesca; sulla rete mobile potrebbero essere applicate tariffe differenti)<br/>
<br/>
Ulteriori indicazioni<br/>
Le informazioni disponibili su questo sito web vengono regolarmente verificate e aggiornate. Nonostante la diligenza dimostrata alcune informazioni possono essere state modificate. Non possiamo quindi assumerci la responsabilità o garantire l’attualità, l’esattezza e la completezza delle informazioni messe a disposizione. La stessa cosa vale per i siti web a cui si è rimandati attraverso collegamento ipertestuale. Epelia non è responsabile del contenuto dei siti web raggiungibili attraverso tale collegamento. Ci riserviamo inoltre il diritto di effettuare modifiche o integrazioni alle informazioni messe a disposizione.<br/>
<br/>
Il contenuto e la struttura di questa pagina sono protetti. La riproduzione di informazioni o dati, in particolare l’utilizzo di testi, parti di testo, o di materiale illustrativo richiede la previa autorizzazione da parte nostra.<br/>
<br/>
© 2011 Epelia. Tutti i diritti riservati.</p>
    </div>
    
</div>

