<div id="content_static" class="">

    <h2>Contatti</h2>    
        
    <div class="relevant_content">
        <p><b>Potete contattare Epelia telefonicamente</b><br/>
da lunedì a venerdì<br/>
dalle 9 alle 18<br/>
Al numero 01803 465283 ("0180 EINKAUF") (9 ct/min da rete fissa tedesca; sulla rete mobile potrebbero essere applicate tariffe differenti).<br/>
<br/>
<b>O contattateci via e-mail</b><br/>
Indirizzo e-mail: mail@epelia.com</p>
    </div>  

</div>

