<div id="content_static">

    <h2>Condizioni di utilizzo</h2>
    
    <div class="relevant_content">
        <p>
            <h4>Preambolo</h4><br/>
Queste condizioni di utilizzo regolano i rapporti giuridici tra l’imprenditore Epelia, commercio Gattinger (seguente “Epelia”) e gli acquirenti che utilizzano la piattaforma di mercato online epelia.com per acquistare prodotti.<br/>
Il rapporto contrattuale tra Epelia e i venditori è disciplinato da un apposito contratto.<br/>
I contratti di vendita stipulati sulla piattaforma commerciale epelia.com sono validi esclusivamente tra il venditore e l’acquirente. Epelia non è parte in tale contratto. Ad Epelia non risulta alcun obbligo in considerazione dell’adempimento del contratto stipulato tra i venditori e gli acquirenti.<br/>
<br/>
<h4>Registrazione</h4><br/>
1. L’utilizzo di Epelia per la ricerca di prodotti, negozi e membri della community è possibile senza registrazione.<br/>
2. Per altre funzioni, come ad esempio il salvataggio di articoli sulla lista della spesa, mettersi in contatto con altri iscritti, la funzione che permette di valutare un prodotto o inserire un commento, e per effettuare un acquisto è necessaria la registrazione come socio.<br/>
3. La registrazione è possibile solo per persone giuridiche e persone fisiche con illimitata capacità di agire. La registrazione è vietata ai minori.<br/>
4. La registrazione di una persona giuridica può essere effettuata solo da una persona fisica avente diritto di rappresentanza, che deve essere nominativamente indicata. Nella registrazione solo una persona può essere designata come possessore del conto dei membri della community Epelia.<br/>
5. I dati comunicati al momento della registrazione devono essere completi e veritieri, e devono sempre essere aggiornati dal cliente.<br/>
6. Al momento della registrazione il futuro membro sceglie un username e una password. La password non deve essere comunicata a terzi.<br/>
7. L’account dei membri della community non è trasferibile.<br/>
8. Epelia si riserva il diritto di eliminare un account, in particolare nel caso dell’utilizzo di username che violino divieti legislativi, i diritti di terzi o che siano contrari al buon costume, o in caso di una dichiarazione incompleta (es. nel caso di mancato inserimento del codice di conferma).<br/>
<br/>
<h4>Responsabilità</h4><br/>
1. Epelia è completamente responsabile della condotta dolosa e colpa grave dei suoi organi, collaboratori o agenti; nei casi di negligenza più lieve però solo per violazione di doveri contrattuali. La responsabilità per la violazione di un tale obbligo contrattuale essenziale è limitata ai danni contrattuali tipicamente prevedibili. Questi dovranno essere messi in conto alla conclusione del contratto in base alle circostanze note al momento della conclusione dell’accordo.<br/>
2. Epelia non è responsabile della veridicità delle informazioni fornite dai venditori riguardo ai prodotti.<br/>
3. Epelia non risponde dei danni alla rete di distribuzione se questi non sono causati direttamente da Epelia.<br/>
4.  Epelia risponde della perdita di dati solo quando tale perdita sia risultata inevitabile nonostante le efficienti misure di protezione dei dati personali messe in atto dal cliente.<br/>
5. A causa dei lavori di manutenzione alla piattaforma commerciale di tanto in tanto necessari, Epelia non può garantire che l’accesso a epelia.com sia possibile in ogni momento e senza interruzioni. Da ciò, non può essere fatta valere alcuna pretesa nei confronti di Epelia.<br/>
6. Le summenzionate deroghe di responsabilità e limitazioni nei confronti di imprese e utenti non sono valide nel caso dell’esplicita concessione di garanzie da parte di Epelia e nel caso di lesione alla vita, al corpo e alla salute o in caso di norme di legge cogenti.<br/>
<br/>
<h4>Modifiche alle condizioni di utilizzo</h4><br/>
Epelia si riserva il diritto di modificare in ogni momento e senza bisogno di spiegazioni queste condizioni utilizzo. Epelia provvederà ad informare i membri via e-mail riguardo alle modifiche al più tardi due settimane prima dell’entrata in vigore delle suddette. Nel caso in cui l’iscritto non si opponga a tali modifiche entro due settimane dall’avvenuta comunicazione, le suddette vengono considerate concordate. Epelia richiamerà l’attenzione sulle scadenze nell’e-mail che contiene le modifiche alle disposizioni.<br/>
<br/>
<h4>Disposizioni finali</h4><br/>
1. Le dichiarazioni contro Epelia devono essere presentate in forma scritta. Dichiarazioni di volontà in forma orale non sono valide.<br/>
2. Valgono le leggi della Repubblica federale di Germania, con esclusione della normativa sul commercio dell’ONU. Nel caso in cui l’acquirente fosse un commerciante, le controversie relative alle condizioni di utilizzo sono di competenza esclusiva di Berlino. In tal caso, Epelia autorizza inoltre a rivolgersi anche al foro competente dell’acquirente.<br/>
3. Nel caso in cui alcune disposizioni di queste condizioni di utilizzo dovessero essere o diventare nulle o siano in contraddizione con la regolarizzazione legale, ciò non compromette la validità delle restanti disposizioni. La clausola inefficace viene sostituita attraverso una regolazione che più si avvicina economicamente a quella inefficace.</p>        
    </div>
    
</div>
