<div id="content_static" class="">

    <h2>Epelia</h2>

    <div class="relevant_content">
        
        <h3>Che cos’è Epelia?</h3>
        
        <p>Epelia è una piattaforma di mercato centrale su cui produttori, manifatture e importatori diretti da Germania, Europa e dal resto del mondo vendono direttamente al cliente 1442 prodotti. I prodotti in vendita su questa piattaforma non sono disponibili nel normale commercio al dettaglio. Tutti i prodotti verranno spediti direttamente dal venditore, senza intermediari, e arriveranno freschi a casa vostra.<br/>
<br/>
Nei negozi online della piattaforma Epelia trovate sempre il prezzo migliore. I negozi online vengono gestiti direttamente dai venditori, come fossero i loro negozi online, e quando ordinate su Epelia, ordinate direttamente al venditore.</p>
        
        <p class="clear space"></p>
        
        <h3>Chi c’è dietro Epelia?</h3>
        
        <p>143 produttori, manifatture e importatori diretti, che vendono sulla piattaforma Epelia attraverso il proprio negozio online. Epelia offre ai propri clienti la possibilità di acquistare direttamente in 143 negozi diversi, utilizzando un cestino e con un account cliente. Sulla nostra piattaforma scoprirete nuovi prodotti, curiose specialità, e potrete leggere le recensioni di altri clienti della community Epelia.</p>
        
        <p class="clear space"></p>
        
        <h3>Perché esiste Epelia?</h3>
        
        <p>Mettiamo che siate clienti che vogliono acquistare mozzarella di bufala, olio di oliva di Creta, e tè biologico e siate alla ricerca di una piattaforma dove possiate acquistare questi beni alimentari direttamente dai rispettivi produttori. Normalmente, dovreste consultare moltissimi negozi online, cercare prodotti, comunicare il vostro indirizzo e pagare separatamente in ogni negozio.<br/>
<br/>
Epelia vi facilita l’acquisto: potrete mettere tutti i prodotti che desiderate, venduti da produttori diversi, in un cestino centrale. Lascerete il vostro indirizzo una volta sola e pagherete tutto in un’unica operazione. Epelia trasmette il pagamento effettuato ai venditori, i quali provvederanno a inviare i prodotti direttamente a casa vostra.</p>
        
    </div>

    
<div style="float:right; width:235px;">
<?= $this->partial('partials/helpbox.phtml') ?>
</div>  

</div>


