<div id="content_static" class="">
    
    <h2>Spedizione e consegna</h2>


    <div class="relevant_content">
        
        <h3>Come ha luogo la consegna?</h3>
        
        <p>Il vostro ordine su Epelia viene subito trasmesso al produttore. Di regola questi procede a imballare la propria merce il giorno stesso, al più tardi il giorno seguente. La spedizione dura 1-2 giorni. I prodotti ordinati vengono sempre inviati direttamente dal produttore stesso.</p>
        
        <p class="clear space"></p>
        
        <h3>Come vengono inviati i prodotti freschi?</h3>
        
        <p>I prodotti che richiedono una specifica temperatura vengono inviati in speciali confezioni di cartone refrigerante con elementi refrigeranti. Questi garantiscono la freschezza dei prodotti fino alla consegna.</p>
        
        <p class="clear space"></p>
        
        <h3>A quanto ammontano i costi di spedizione?</h3>
        
        <p>Ogni produttore calcola da sé i costi di spedizione. Trovate i prezzi di spedizione nei rispettivi negozi sotto “Spedizione e consegna”.<br/>
Molti venditori offrono un importo al di sopra del quale la spedizione è gratuita. Trovate tutte le informazioni a riguardo sotto “Spedizione e consegna” dei rispettivi produttori.</p>
                
    </div>

    
<div style="float:right; width:235px;">
<?= $this->partial('partials/helpbox.phtml') ?>
</div>  

</div>
