<div class="row">
    <div class="col bg-light border m-3">
       <h2><?= $this->translate('checkout_headline') ?></h2>
            <table class="table">
                <thead>
                    <tr>
                        <th><?= $this->translate('checkout_product') ?></th>
                        <th><?= $this->translate('checkout_amount') ?></th>
                        <th><?= $this->translate('checkout_single_price') ?></th>
                        <th><?= $this->translate('checkout_total_price') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->products as $shopID => $products):
                    $counter = 0;
                    $sum = 0;
                ?>
<?php   foreach($products as $item):
    $counter++;
    $product = $item['product'];
    $price = $item['product_price'];
    $quantity = $item['quantity'];
    $sum += $quantity * $price->value;
?>
                    <tr>
                        <td>
                            <a href='/products/<?= $this->escape($product->id) ?>/'><img src='/img/products/90x68/<?= $this->escape($product->getDefaultPicture()->filename) ?>' alt='<?= $this->escape($product->name) ?>' /></a><br />
                            <a href='/products/<?= $this->escape($product->id) ?>/' class='hiddenlink'><?= $this->escape($product->name) ?></a><br />
                            <?= $price->quantity ?> <?= ($price->quantity == 1) ? $this->escape($price->getUnitType()->singular) : $this->escape($price->getUnitType()->plural) ?> &agrave; <?= $this->escape($price->contents) ?> <?= $this->escape($price->getContentType()->name) ?><br />
                            <?= $this->translate('checkout_seller') ?> <a href='<?= $this->escape($product->getShop()->getLink()) ?>' class='hiddenlink'><?= $this->escape($product->getShop()->name) ?></a>
                        </td>
                        <td><?= $this->escape($quantity) ?></td>
                        <td><?= number_format($price->value, 2, ',', '') ?> &euro;</td>
                        <td><?= number_format($quantity * $price->value, 2, ',', '') ?> &euro;</td>
                    </tr>
<?php   endforeach; ?>

<?php endforeach; ?>
                </tbody>
            </table>
            <p>Mit Ihrer Bestellung erkl&auml;ren Sie sich mit den <a href="/hilfe/agb/" title="Allgemeinen Geschäftsbedingungen" target="_blank">allgemeinen Gesch&auml;ftsbedingungen</a><br />
                und den <a href="/hilfe/datenschutz/" target="_blank" title="Datenschutzbestimmungen">Datenschutzbestimmungen</a> von Epelia einverstanden.</p>

            <table class="table">
                <tr>
                    <td><strong><?= $this->translate('checkout_payment_type') ?>:</strong></td>
                    <td><?= $this->escape($this->paymentType) ?></td>
                    <td><a class="btn btn-primary" href="/shoppingcart/payment/" title="<?= $this->translate('checkout_edit') ?>"><?= $this->translate('checkout_edit') ?></a></td>
                </tr>
                <tr>
                    <td><strong><?= $this->translate('shoppingcart_addresses_invoice') ?></strong></td>
                    <td><?= $this->partial('partials/address.phtml', array('address' => $this->billingAddress)) ?></td>
                    <td><a class="btn btn-primary href="/shoppingcart/addresses/" title="<?= $this->translate('checkout_edit') ?>"><?= $this->translate('checkout_edit') ?></a></td>
                </tr>
                <tr>
                    <td><strong><?= $this->translate('shoppingcart_addresses_delivery') ?></strong></td>
                    <td>
                        <?php if(!$this->is_self_collecting): ?>
                            <?= $this->partial('partials/address.phtml', array('address' => $this->deliveryAddress)) ?>
                        <?php else: ?>
                            Selbstabholung
                        <?php endif; ?>
                    </td>
                    <td><a class="btn btn-primary" href="/shoppingcart/addresses/" title="<?= $this->translate('checkout_edit') ?>"><?= $this->translate('checkout_edit') ?></a></td>
                </tr>
            </table>
    </div>
</div>
<div class="row">
    <div class="col bg-light border m-3">
        <h2><?= $this->translate('checkout_total') ?></h2>
        <table class="table">
            <tr class="text-right">
                <td><?= $this->translate('checkout_single_sum') ?></td>
                <td><?= number_format($this->total, 2, ',', '') ?> &euro;</td>
            </tr>
            <tr class="text-right">
                <td><?= $this->translate('checkout_delivery') ?></td>
                <td><?= number_format($this->shippingCosts, 2, ',', '') ?> &euro;</td>
            </tr>
            <tr class="text-right">
                <td><?= $this->translate('checkout_total') ?></td>
                <td><?= number_format($this->total + $this->shippingCosts, 2, ',', '') ?> &euro;</td>
            </tr>
            <tr>
                <td colspan="2" style="height:34px;"></td>
            </tr>
            <tr class="text-right">
                <td class="td_label" colspan="2">
                    <a class="btn btn-success" title="<?= $this->translate('checkout_order') ?>" href="/shoppingcart/conclude/"><?= $this->translate('checkout_order') ?></a>
               </td>
           </tr>
        </table>
    </div>
</div>