<div class="row">
    <div class="col bg-light border m-3">
        <h2><?= $this->translate('payment_headline') ?></h2>
        <form id="payment_frm" method="POST" name="payment_frm" style="display:inline">
            <input type="hidden" name="sendform" id="sendform" value="1" />
            <table class="table">
                <tr>
                    <td>
                        <input id="pay_methode_2" type="radio" name="method" class="paymethod_select" value="directtransfer" />
                    </td>
                    <td>
                        <label for="pay_methode_2">Sofortüberweisung</label>
                    </td>
                    <td>
                        <p>Zahlen Sie bequem und sicher online per Sofortüberweisung.</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input id="pay_methode_1" type="radio" name="method" class="paymethod_select"  value="prepayment" />
                    </td>
                    <td>
                        <label for="pay_methode_1"><?= $this->translate('payment_prepay') ?></label>
                    </td>
                    <td>
                            <ul>
                                <li><?= $this->translate('payment_prepay_1') ?></li>
                                <li><?= $this->translate('payment_prepay_2') ?></li>
                                <li><?= $this->translate('payment_prepay_3') ?></li>
                            </ul>
                    </td>
                </tr>
            </table>
        </form>
        <a id="id_send_button" href="" class="btn btn-success mb-3" title="<?= $this->translate('payment_continue') ?>"><?= $this->translate('payment_continue') ?></a>
        <div class="alert alert-danger collapse" id="noPaymentError"></div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.paymethod_select').click(function(e){
            $('#id_send_button').attr('href', '/shoppingcart/checkout/paymenttype/' + e.target.value + '/');
        });

        $('#id_send_button').click(function(e){
            e.preventDefault();
            if(!$('#id_send_button').attr('href')){
                $('#noPaymentError').html('<?= $this->translate('shoppingcart_nopayment_error') ?>').show();
                return false;
            }
            else{
                $('#noPaymentError').html('').hide();
                window.location = e.currentTarget.href;
                return true;
            }
        });
    });
</script>
