<div class="row">
    <div class="col bg-light border m-3">
        <h2><?= $this->translate('checkout_success_headline') ?></h2>
<?php if($this->cart->status == 'ordered'): ?>
        <h3><?= $this->translate('checkout_success_ordered') ?></h3>
        <table class="table">
            <tr>
<?php 
switch($this->cart->payment_type){
    case 'prepayment':
        $payment = 'Vorkasse';
        break;
}
?>
                <td><?= $this->translate('checkout_payment_type') ?>:</td>
                <td><?= $this->escape($this->payment) ?></td>
            </tr>
            <tr>
                <td><?= $this->translate('checkout_total') ?>:</td>
                <td><?= number_format($this->total, 2, ',', '') ?> &euro;</td>
            </tr>
            <tr>
                <td><?= $this->translate('orders_number') ?>:</td>
                <td><?= $this->escape($this->cart->getCartId()) ?></td>
            </tr>
            <tr>
                <td><?= $this->translate('checkout_success_prepay_1') ?></td>
                <td>
                    <?= $this->translate('checkout_success_prepay_2') ?><br />
                    <?= $this->translate('checkout_success_prepay_3') ?><br />
                    <?= $this->translate('checkout_success_prepay_4') ?><br />
                    <?= $this->translate('checkout_success_prepay_5') ?><br />
                    <?= $this->translate('checkout_success_prepay_6') ?> <?= $this->escape($this->cart->getCartId()) ?>
                </td>
            </tr>
            <tr>
                <td><?= $this->translate('checkout_success_prepay_7') ?></td>
                <td>
                    IBAN: DE24513610210004647483<br />
                    BIC: GENODE51HHE
                </td>
            </tr>
        </table>
                    
<?php else: ?>
    <p class="boxtitle"><?= $this->translate('checkout_success_accepted') ?></p>
<?php endif; ?>
    </div>
</div>