<div id="content-search">
    <div class="sidewrapper">
        <div class="block">
            <ul class="categoryList">
                <li class="filter_bio" style="padding-bottom:5px;">
                    <input id="i_bio" type="checkbox" class="filter" value="bio" name="only_bio"<?php if($this->onlyBio): ?> checked="checked"<?php endif; ?> />
                    <label style="display:inline" for="i_bio"><a><?= $this->translate('filter_bio') ?></a></label>
                </li>
                <li class="filter_discount" style="padding-bottom:5px;">
                    <input id="i_discount" type="checkbox" class="filter" value="discount" name="only_discount"<?php if($this->onlyDiscount): ?> checked="checked"<?php endif; ?> />
                    <label style="display:inline" for="i_discount"><a><?= $this->translate('filter_discount') ?></a></label>
                </li>
            </ul>
        </div>
    </div>
    <div class="search-products">
        <h2 class="clear"><?= $this->escape($this->attribute->name) ?></h2>
<?= $this->partial('partials/productgrid.phtml', array('products' => $this->attribute->getProducts(9, ($this->page > 1) ? (9 * $this->page - 9) : null, $this->onlyBio, $this->onlyDiscount))) ?>        
<?php if($this->productCount): ?>            
            <?= $this->partial('partials/pagination.phtml', array('type' => 'attributes', 'id' => $this->attribute->id, 'page' => $this->page, 'productCount' => $this->productCount, 'onlyBio' => $this->onlyBio, 'onlyDiscount' => $this->onlyDiscount, 'onlyWholesale' => $this->onlyWholesale)); ?>
<?php endif; ?>

      
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function(){
        $('.filter').change(function(){
            var bio = ($('#i_bio').is(':checked'));
            var discount = ($('#i_discount').is(':checked'));
            var pathnameAttr = $(location).attr('pathname').split('/');
            if(!bio && !discount){
                location.href = '/' + pathnameAttr[1] + '/' + pathnameAttr[2] + '/';
            }
            else{
                if(!pathnameAttr[5]) pathnameAttr[5] = 'all';
                pathnameAttr[6] = 1;
                location.href = '/' + pathnameAttr[1] + '/' + pathnameAttr[2] + '/' + ((bio) ? 'bio' : 'all') + '/' + ((discount) ? 'discount': 'all') + '/' + pathnameAttr[5] + '/' + pathnameAttr[6] + '/';
            }
        });
    });

</script>
