<h1 style="margin-bottom:5px;">Hauptkategorien</h1>
<a href="/admin/maincategories/edit/">Neue Hauptkategoie anlegen</a>
<table class="table" id="mainCategoriesTable">
    <thead>
    <tr><th>Name</th><th>Aktionen</th></tr>
    </thead>
    <tbody>
<?php foreach($this->mainCategories as $cat): ?>
    <tr><td><?= $this->escape($cat->name) ?></td><td><a href="/admin/maincategories/edit/id/<?= $this->escape($cat->id) ?>">Editieren</a><br /><a href="/admin/maincategories/delete/id/<?= $this->escape($cat->id) ?>">Löschen</a></td></tr>
<?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        $('#mainCategoriesTable').dataTable({
            "aoColumns": [
                null, 
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
           
</script>
