<div id="content_buy" class="tpl_bio">  
    <h1><?= $this->translate('bio_headline') ?></h1>
    <div> 
        <p class="textblock"><?= $this->translate('bio_intro') ?></p>               
        <p class="clear"></p><br />           
        <a href="/bio/showall/" title="<?= $this->translate('bio_show_all') ?>"><?= $this->translate('bio_show_all') ?></a>                
        <p class="clear border"></p>              
        <p class="title"><?= $this->translate('bio_sub_1') ?></p>        
        <p class="textblock"><?= $this->translate('bio_list_intro') ?></p>        
        <ul class="list-bios" style="margin-top:0px;">
            <li><?= $this->translate('bio_list_1') ?></li>
            <li><?= $this->translate('bio_list_2') ?></li>
            <li><?= $this->translate('bio_list_3') ?></li>
            <li><?= $this->translate('bio_list_4') ?></li>
            <li><?= $this->translate('bio_list_5') ?></li>
            <li><?= $this->translate('bio_list_6') ?></li>
            <li><?= $this->translate('bio_list_7') ?></li>
        </ul>        
        <p class="textblock" style="margin-top:20px;"><?= $this->translate('bio_list_outro') ?></p>        
    </div>    
</div>
