<div class="row">
    <div class="col bg-light border m-3">

        <h2><?= $this->translate('orders_headline') ?></h2>
        <h3><?= $this->translate('myepelia_orders_waiting') ?></h3>
        <table class="table table-striped table-bordered" id="orderedTable">
            <thead>
                <tr><th><?= $this->translate('orders_date') ?></th><th><?= $this->translate('orders_number') ?></th><th><?= $this->translate('orders_price_products') ?></th><th><?= $this->translate('orders_delivery_costs') ?></th><th><?= $this->translate('orders_price') ?></th><th><?= $this->translate('orders_products') ?></th><th></th></tr>
            </thead>
            <tbody>
        <?php
            foreach($this->orderedCarts as $cart):
        ?>
                <tr><td><?= date('d.m.Y', strtotime($cart->created)) ?></td><td><?= $this->escape($cart->getCartId()) ?></td><td><?= number_format($cart->getPrice(), 2, ',', '') ?> EUR</td><td><?= number_format($cart->getShippingCosts(), 2, ',', '') ?> EUR</td><td><?= number_format($cart->getPriceTotal(), 2, ',', '') ?> EUR</td><td><?php foreach($cart->getProducts() as $item): ?><?= $this->escape($item['product_name']) ?><br /><?php endforeach; ?></td><td><a href="/shoppingcart/success/cartid/<?= $this->escape($cart->id) ?>/">Details</a></td></tr>
        <?php
            endforeach;
        ?>
            </tbody>
        </table>

        <h3><?= $this->translate('myepelia_orders_in_process') ?></h3>
        <table class="table table-striped table-bordered" id="acceptedTable">
            <thead>
                <tr><th><?= $this->translate('orders_date') ?></th><th><?= $this->translate('orders_number') ?></th><th><?= $this->translate('orders_price_products') ?></th><th><?= $this->translate('orders_delivery_costs') ?></th><th><?= $this->translate('orders_price') ?></th><th><?= $this->translate('orders_products') ?></th></tr>
            </thead>
            <tbody>
        <?php
            foreach($this->openOrders as $order):
                $orderProducts = $order->getProducts();
                $products = array();
                $total = 0;
                foreach($orderProducts as $item){
                    $product = Model_Product::find($item['product_id']);
                    $products[] = $product;
                    $total += $item['value'] * $item['quantity'];
                }
        ?>
                <tr><td><?= date('d.m.Y', strtotime($order->created)) ?></td><td><?= $this->escape($order->order_number) ?></td><td><?= number_format($total, 2, ',', '') ?> EUR</td><td><?= number_format($order->shipping, 2, ',', '') ?> EUR</td><td><?= number_format($total + $order->shipping, 2, ',', '') ?> EUR</td><td><?php foreach($products as $product): ?><?= $this->escape($product->name) ?><br /><?php endforeach; ?></td></tr>
        <?php
            endforeach;
        ?>
            </tbody>
        </table>

        <h3><?= $this->translate('myepelia_orders_complete') ?></h3>
        <table class="table table-striped table-bordered" id="completeTable">
            <thead>
                <tr><th><?= $this->translate('orders_date') ?></th><th><?= $this->translate('business_orders_sent_date') ?></th><th><?= $this->translate('orders_number') ?></th><th><?= $this->translate('orders_price_products') ?></th><th><?= $this->translate('orders_delivery_costs') ?></th><th><?= $this->translate('orders_price') ?></th><th><?= $this->translate('orders_products') ?></th></tr>
            </thead>
            <tbody>
        <?php
            foreach($this->completeOrders as $order):
                $orderProducts = $order->getProducts();
                $products = array();
                $total = 0;
                foreach($orderProducts as $item){
                    $product = Model_Product::find($item['product_id']);
                    $products[] = $product;
                    $total += $item['value'] * $item['quantity'];
                }
        ?>
                <tr><td><?= date('d.m.Y', strtotime($order->created)) ?></td><td><?= date('d.m.Y', strtotime($order->send_date)) ?></td><td><?= $this->escape($order->order_number) ?></td><td><?= number_format($total, 2, ',', '') ?> EUR</td><td><?= number_format($order->shipping, 2, ',', '') ?> EUR</td><td><?= number_format($total + $order->shipping, 2, ',', '') ?> EUR</td><td><?php foreach($products as $product): ?><?= $this->escape($product->name) ?><br /><?php endforeach; ?></td></tr>
        <?php
            endforeach;
        ?>
            </tbody>
        </table>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function() {
        $('#orderedTable').dataTable({
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                null,
                { "bSortable": false }
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
 
    $(document).ready(function() {
        $('#acceptedTable').dataTable({
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                null
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });

    $(document).ready(function() {
        $('#completeTable').dataTable({
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });



</script>
