<div class="row">
    <div class="col bg-light border m-3">
        <h2><?= $this->translate('ratings_open') ?></h2>
        <table class="table table-striped table-bordered" id="openRatingsTable">
            <thead>
            <tr><th><?= $this->translate('ratings_product') ?></th><th><?= $this->translate('ratings_buy_date') ?></th><th></th></tr>
            </thead>
            <tbody>
        <?php
            foreach($this->unratedProducts as $orderedProdukt):
                $product = Model_Product::find($orderedProdukt['product_id']);
        ?>
                <tr></td><td><?= $this->escape($product->name) ?></td><td><?= $this->escape(date('d.m.Y', strtotime($product->created))) ?></td><td><a href="/meinepelia/createrating/productid/<?= $this->escape($product->id) ?>/">Jetzt Bewertung abgeben</a></td></tr>
        <?php
            endforeach;
        ?>
            </tbody>
        </table>

        <h2><?= $this->translate('ratings_rated') ?></h2>
        <table class="table table-striped table-bordered" id="ratingsTable">
            <thead>
            <tr><th><?= $this->translate('ratings_rating') ?></th><th><?= $this->translate('ratings_text') ?></th><th><?= $this->translate('ratings_product') ?></th><th><?= $this->translate('ratings_rating_date') ?></th></tr>
            </thead>
            <tbody>
        <?php foreach($this->productRatings as $rating): ?>
                <tr><td><?= $this->escape($rating->rating) ?></td><td><?= $this->escape($rating->comment) ?></td><td><a href="/products/<?= $this->escape($rating->getProduct()->id) ?>/"><?= $this->escape($rating->getProduct()->name) ?></a></td><td><?= $this->escape(date('d.m.Y', strtotime($rating->created))) ?></td></tr>
        <?php
        endforeach;
        ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#openRatingsTable').dataTable({
            "aoColumns": [
                null,
                null,
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });

        $('#ratingsTable').dataTable({
            "aoColumns": [
                null,
                null,
                null,
                null
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });


    });
           
</script>
