<div class="row">
    <div class="col bg-light border m-3">
        <h1 style="margin-bottom:5px;">Produkte</h1>
        <a href="/admin/products/edit/">Neues Produkt anlegen</a>
        <h2>Produkte</h2>
        <table class="table" id="productTable">
            <thead>
            <tr><th>ID</th><th>Shopname</th><th>Name</th><th>Aktiv</th><th>Vorrat</th><th>Erstellung</th><th>Aktionen</th></tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        var productTable = $('#productTable').dataTable({
            "bFilter": true,
            "bSort": false,
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "/admin/products/ajaxgetproducts/",

            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                null,
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen (ID, Produktname, Shop-Name, E-Mail)",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });

        $('#filterActivated').change(function(){
            productTable.fnFilter($(this).val(), 3);
        });
    });
           
</script>
