<div id="content-search">
    <div class="sidewrapper">
        <div class="block">
            <ul class="categoryList">
<?php foreach($this->woma->getAttributes() as $attr): ?>
                <li><a <?php if($this->attribute->id == $attr->id): ?>class="current_item" <?php endif; ?>href="<?= $this->woma->getLink() ?>attributes/<?= $this->escape($attr->id) ?>/" title="<?= $this->escape($attr->name) ?>"><?= $this->escape($attr->name) ?></a></li>
<?php endforeach;
$this->attribute->clearProducts(); // getting count sets _products, need to clear before calling getProducts()
?>
                <li class="filter_bio" style="padding-bottom:5px;">
                    <input id="i_bio" type="checkbox" class="filter" value="bio" name="only_bio"<?php if($this->onlyBio): ?> checked="checked"<?php endif; ?> />
                    <label style="display:inline" for="i_bio"><a><?= $this->translate('filter_bio') ?></a></label>
                </li>
                <li class="filter_discount" style="padding-bottom:5px;">
                    <input id="i_discount" type="checkbox" class="filter" value="discount" name="only_discount"<?php if($this->onlyDiscount): ?> checked="checked"<?php endif; ?> />
                    <label style="display:inline" for="i_discount"><a><?= $this->translate('filter_discount') ?></a></label>
                </li>
            </ul>
        </div>
    </div>
    <div class="search-products">
        <h2 class="clear"><?= $this->escape($this->attribute->name) ?> (<a href="<?= $this->escape($this->woma->getLink()) ?>"><?= $this->escape($this->woma->name) ?></a>)</h2>
<?= $this->partial('partials/productgrid.phtml', array('products' => $this->woma->getProductsByAttribute($this->attribute->id, 9, ($this->page > 1) ? (9 * $this->page - 9) : null, $this->onlyBio, $this->onlyDiscount))) ?>        
<?php if($this->productCount): ?>            
            <?= $this->partial('partials/pagination.phtml', array('page' => $this->page, 'productCount' => $this->productCount, 'onlyBio' => $this->onlyBio, 'onlyDiscount' => $this->onlyDiscount, 'onlyWholesale' => $this->onlyWholesale, 'customLink' => $this->woma->getLink() . 'attributes/' . $this->attribute->id . '/')); ?>
<?php endif; ?>

      
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function(){
        $('.filter').change(function(){
            var bio = ($('#i_bio').is(':checked'));
            var discount = ($('#i_discount').is(':checked'));
            var pathnameAttr = $(location).attr('pathname').split('/');
            if(!bio && !discount){
                location.href = '/' + pathnameAttr[1] + '/' + pathnameAttr[2] + '/' + pathnameAttr[3] + '/' + pathnameAttr[4] + '/';
            }
            else{
                if(!pathnameAttr[7]) pathnameAttr[7] = 'all';
                pathnameAttr[8] = 1;
                location.href = '/' + pathnameAttr[1] + '/' + pathnameAttr[2] + '/' + pathnameAttr[3] + '/' + pathnameAttr[4] + '/' + ((bio) ? 'bio' : 'all') + '/' + ((discount) ? 'discount': 'all') + '/' + pathnameAttr[7] + '/' + pathnameAttr[8] + '/';
            }
        });
    });

</script>
