<div id="register-content" class="request">
    <h1 style="margin-bottom:0px;"><?= $this->translate('login_reset_password_headline') ?></h1>
    <p class="intro-block"><?= $this->translate('login_reset_password_content') ?></p>
    <form action="/login/sendresetpasswordmail" method="post">
        <label for="email"><?= $this->translate('misc_email') ?></label>
        <input type="text" name="email" id="email" />
        <input type="submit" value="<?= $this->translate('login_reset_password') ?>" />
    </form>
</div>
