<div id="register-content" class="request">
    <h1 style="margin-bottom:0px;"><?= $this->translate('login_reset_password_headline') ?></h1>
    <p class="intro-block" style="margin-bottom:0px; padding-bottom:0px;"><?= $this->translate('login_reset_password_content') ?></p>
<?php if($this->changePasswordError):?>
            <p class="error" style="margin-left:12px;"><?= $this->changePasswordError; ?></p>
<?php endif; ?>
    <?= $this->changePasswordForm ?>
</div>
