<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <meta name="viewport" content="width=device-width">

        <?php echo $this->headTitle(); ?>

        <?php echo $this->jQuery(); ?>
        <?php echo $this->headScript(); ?>
<script type="text/javascript" src="/js/plugins/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/support/datatable.js"></script>



        <?php echo $this->headLink(); ?>

    <link href="/css/all.css" rel="stylesheet" type="text/css" />
	<link href="/css/base.css" rel='stylesheet' type='text/css' />
	<link href="/css/main.css" rel='stylesheet' type='text/css' />
	<link href="/css/jnice.css" rel='stylesheet' type='text/css' />
	<link href="/css/suggest.css" rel='stylesheet' type='text/css' />
	<link href="/css/home.css" rel='stylesheet' type='text/css' />


            </head>
    <body>
    <div id="modal_box"></div>

<div id="page_margins">

    <!-- #flexible [+] -->

    
    <div id="flexible" style="width:1000px;">

        

        <!-- #pagewrapper [+] -->
        <div id="pagewrapper">


        <div id="suggest_box"></div>

        <noscript>
            <div class="noscript">
                <div class="noscript-inner">
                    <p><strong>Wir haben festgestellt, dass in Ihrem Browser JavaScript deaktiviert ist.</strong></p>
                    <p>Sie m&uuml;ssen JavaScript in Ihrem Browser aktivieren, um den vollen Funktionsumfang dieser Website nutzen, zu können.</p>
                </div>
           </div>
        </noscript>

        

        

            <!-- header [+] -->
            <div id="header">

                <!--<h1><a id="logo" href="" title="Zur Startseite">&nbsp;</a></h1>-->

                <div id="headertop">
                    <a style="width:226px; margin-top:10px; margin-left:10px; height:80px; display:block; position:absolute; background-image:url('/resources/images/screens/logo-lefttop-small.png'); background-repeat:no-repeat;" href="/"></a>

                  <div class="cart">
<?php
$productCount = 0;
if($this->shoppingCart && $this->shoppingCart->getProducts()){
    foreach($this->shoppingCart->getProducts() as $pr){
        $productCount += $pr['quantity'];
    }
}
?>
                        <a class="icon" href="/shoppingcart/" title="Warenkorb" rel="nofollow" style="padding-left:13px;">
                            Warenkorb <strong><span id="num_products_header"><?= ($this->shoppingCart) ? $productCount : '0' ?></span></strong>
                        </a>
                        <a href="/shoppingcart/addresses/" title=">Zur Kasse" rel="nofollow">Zur Kasse</a>
<?php if(!is_null($this->user)): ?>
    <?php if($this->user->type == 'shop'): ?>
                        <a href="/business/"><?= $this->translate('misc_business') ?></a>
    <?php endif; ?>
    <?php if($this->user->type == 'agent'): ?>
                        <a href="/woma/"><?= $this->translate('misc_woma') ?></a>
    <?php endif; ?>
    <?php if($this->user->is_admin): ?>
                        <a href="/admin/"><?= $this->translate('misc_admin') ?></a>
    <?php endif; ?>
<?php endif; ?>

                    </div>

                    <ul id="headermenu_small">
                        <li><a href="/hilfe/bestellen" target="_blank" rel="nofollow" title="Hilfe">Hilfe</a></li>
                        <!--  <li><a rel="nofollow" href="/register.html" title="Mitmachen"><strong>Mitmachen</strong></a></li> -->
                        <li><a href="/hilfe/ueber-kisju" title="Über Epelia">Über Epelia</a></li>
                        <li>
                           <a href="/login/logout/" rel="nofollow" title="Logout">Logout</a>
                        </li>
                        <li>
                            <span style="color: white;"><a href="/lebensmittel-online-bestellen">Telefonisch bestellen: 0180 EINKAUF <br/> <span style="font-size:80%">(9 ct/min aus dem Festnetz der Dt. Telekom, <br />evtl. abweichend aus Mobilnetzen)</span></a></span>
                        </li>
                                            </ul>
                </div>



                <div id="headermain">
                <div class="mainmenu_pane">
                    <div class="mainmenu_content" style="width:1001px;">
                        <ul id="user-nav">

                            <li class="tab01" style="margin-top:3px;"><a class="link-nav-cat" href="/woma/">Übersicht</a></li>

                            <li class="tab02" style="margin-top:3px;"><a class="link-nav-cat">Wochenmarkt-Verwaltung</a>
                                <ul>
                                    <li><a href="/woma/woma/"><?= $this->translate('misc_woma') ?></a></li>
                                    <li><a href="/woma/woma/pictures/"><?= $this->translate('misc_pictures') ?></a></li>
                                    <li><a href="/woma/products/"><?= $this->translate('orders_products') ?></a></li>
                                    <li><a href="/woma/shippingcosts/"><?= $this->translate('orders_delivery_costs') ?></a></li>
                                </ul>
                            </li>

                       </ul>
                    </div>
                    </div>
                                            
                </div>

            </div>
            <!-- header [-] -->

            

            <div id="ie_clearing" class="clear"></div>


            <!-- content [+] -->
            <div id="contentwrapper">
                <div style="float:left; width:934px; font-size:0px;"></div>
  
                <?php echo $this->layout()->content; ?>

            </div>
                <div class="clear"></div>
            <!-- content [-] -->
            

            <!-- footer [+] -->
            <div id="footer">

                <ul>
                    <li><a href="/hilfe/ueber-kisju" title="Über Epelia">Über Epelia</a></li>                  
                    <li><a href="/hilfe/bestellen" title="Bestellen">Bestellen</a></li>
                    <li><a href="/hilfe/bezahlung" title="Zahlungsmöglichkeiten">Zahlungsmöglichkeiten</a></li>
                    <li><a href="/hilfe/versand-lieferung" title="Versand und Lieferung">Versand und Lieferung</a></li>
                    <li class="lastListElem"><a href="/kontakt.html" rel="nofollow" title="Kontakt">Kontakt</a></li>
                </ul>

                <p class="clear"></p>

                <ul>
                    <li><a href="/gesetzliche-bestimmungen" rel="nofollow" title="Gesetzliche Informationen">Gesetzliche Informationen</a></li>
                    <li><a href="/nutzungsbedingungen" rel="nofollow" title="Nutzungsbedingungen">Nutzungsbedingungen</a></li>
                    <li><a href="/datenschutz.html" rel="nofollow" title="Datenschutz">Datenschutz</a></li>
                    <li class="lastListElem"><a href="/impressum.html" rel="nofollow" title="Impressum">Impressum</a></li>
                </ul>

                <p class="clear"></p>

                <ul>
                    <li><a href="/verkaufen" title="Für Verkäufer - Verkaufen mit Epelia">Für Verkäufer - Verkaufen mit Epelia</a></li>
                    <li class="lastListElem"><a href="/wholesale/" title="Großhandel">Großhandel</a></li>
                    <li><a href="/genossenschaft/" title="<?= $this->translate('footer_collaborate') ?>"><?= $this->translate('footer_collaborate') ?></a></li>
                </ul>

                                <div class="clear">&nbsp;</div>

                 
                <p class="copyright">&copy; Epelia <?= date('Y', time()) ?></p>

            </div>

            <div class="clear">&nbsp;</div>
            <!-- footer [-] -->


        </div>
        <!-- #pagewrapper [-] -->

    </div>
    <!-- #flexible [-] -->

</div>
<!-- #page_margins [-] -->                  
                        
         
    </body>
</html>
