<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

      <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
      <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

      <style>
          body {font: 0.9rem var(--font-family-sans-serif);}
          h1 {font: 1.6rem var(--font-family-sans-serif); margin-top:5px}
          h2 {font: 1.5rem var(--font-family-sans-serif); margin-top:5px}
          h3 {font: 1.3rem var(--font-family-sans-serif); margin-top:5px}
          h4 {font: 1.2rem var(--font-family-sans-serif); margin-top:5px}
          a { color: #6cb031; }
      </style>

    <?php echo $this->headTitle(); ?>
  <?php
  $session = new Zend_Session_Namespace('Default');
  $helpPrefix = 'hilfe';
  if($session->language == 'it'):
      $helpPrefix = 'hilfeit';
      ?>

  <?php endif;
  if($session->language == 'en'):
      $helpPrefix = 'hilfeeng';
  endif;
  ?>
  </head>
  <body style="background: url('/img/layout/background.jpg') center center  no-repeat fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
    <div id="modal_box"></div>
    <div class="container" style="background-color:rgba(255,255,255,0.80); min-height:100%; height:100%">
        <nav class="navbar navbar-expand-sm">
            <a class="navbar-brand mr-auto" href="/">
              <img src="/img/layout/ofb-logo.png" style="height:50px" alt="">
            </a>
            <ul class="navbar-nav justify-content-end">
                <?php if($this->region): ?>
                <li class="nav-item border dropdown bg-light">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Region <?= $this->region->name ?>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/regions/">Region ändern</a>
                    </div>
                </li>
                <?php else: ?>
                <li class="nav-item border bg-light">
                    <a class="nav-link" href="/regions/">Region wählen</a>
                </li>
                <?php endif; ?>
                <?php
                $productCount = 0;
                if($this->shoppingCart && $this->shoppingCart->getProducts()){
                    foreach($this->shoppingCart->getProducts() as $pr){
                        $productCount += $pr['quantity'];
                    }
                }
                ?>
                <?php if($productCount > 0): ?>
                <li class="nav-item border bg-light">
                    <a id="shoppingcart-nav" class="nav-link" href="/shoppingcart/" title="<?= $this->translate('misc_shoppingcart') ?>" rel="nofollow">
                        <?= $this->translate('misc_shoppingcart') ?> <strong><span id="num_products_header"><?= ($this->shoppingCart) ? $productCount : '0' ?></span></strong></a>
                </li>
                <li class="nav-item border bg-light">
                    <a class="nav-link" href="/shoppingcart/addresses/" title="><?= $this->translate('misc_cashier') ?>" rel="nofollow"><?= $this->translate('misc_cashier') ?></a>
                </li>
                <?php endif; ?>
                <li class="nav-item border bg-light">
                <?php if(!is_null($this->user)): ?>
                    <a class="nav-link" href="/login/logout/" rel="nofollow" title="<?= $this->translate('misc_logout') ?>"><?= $this->translate('misc_logout') ?></a>
                <?php else: ?>
                    <a class="nav-link" href="/login/"  rel="nofollow" title="<?= $this->translate('misc_login') ?>"><?= $this->translate('misc_login') ?></a>
                <?php endif; ?>
                </li>
            </ul>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <?= $this->translate('misc_categories') ?>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/categories/"><?= $this->translate('misc_all_categories') ?></a>
<!--                  <a class="dropdown-item" href="/attributes/"><?= $this->translate('misc_allergy_products') ?></a> -->
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/verkaufen/"><?= $this->translate('misc_sell') ?></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/wholesale/"><?= $this->translate('misc_wholesale') ?></a>
              </li>
                <?php if(is_null($this->user)): ?>
              <li class="nav-item">
                <a class="nav-link" href="/login/"><?= $this->translate('misc_my_epelia') ?></a>
              </li>
                <?php else: ?>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?= $this->translate('misc_my_epelia') ?>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/meinepelia/" title="<?= $this->translate('misc_my_epelia') ?>"><?= $this->translate('misc_my_epelia') ?></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/meinepelia/orders/" title="<?= $this->translate('misc_orders') ?>"><?= $this->translate('misc_orders') ?></a>
                        <a class="dropdown-item" href="/meinepelia/addresses/" title="<?= $this->translate('misc_addresses') ?>"><?= $this->translate('misc_addresses') ?></a>
                        <a class="dropdown-item" href="/meinepelia/productratings/" title="<?= $this->translate('misc_ratings') ?>"><?= $this->translate('misc_ratings') ?></a>
                        <?php if($this->user->getShop()): ?>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/business/"><?= $this->translate('misc_business') ?></a>
                            <a class="dropdown-item" href="/business/sales/orders/">Mein Shop - Bestellungen</a>
                            <a class="dropdown-item" href="/business/sales/archive/">Mein Shop - Bestellarchiv</a>
                        <?php endif; ?>
                        <?php if($this->user->type == 'agent'): ?>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/woma/"><?= $this->translate('misc_woma') ?></a>
                        <?php endif; ?>
                        <?php if($this->user->is_admin): ?>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/"><?= $this->translate('misc_admin') ?></a>
                        <?php endif; ?>

                    </div>
                </li>
                <?php endif; ?>
            </ul>
          </div>
        </nav>
        <?php echo $this->layout()->content; ?>

        <!-- footer [+] -->

        <hr />
        <footer class="page-footer pt-3">
            <div class="container text-center text-md-left">
                <div class="row">
                    <div class="col-md-3 mx-auto">
                        <ul class="list-unstyled">
                            <li><a href="/<?= $helpPrefix ?>/ueber/" title="<?= $this->translate('footer_about') ?>"><?= $this->translate('footer_about') ?></a></li>
                            <li><a href="/<?= $helpPrefix ?>/bestellen/" title="<?= $this->translate('footer_order') ?>"><?= $this->translate('footer_order') ?></a></li>
                            <li><a href="/<?= $helpPrefix ?>/bezahlung/" title="<?= $this->translate('footer_payment') ?>"><?= $this->translate('footer_payment') ?></a></li>
                            <li><a href="/<?= $helpPrefix ?>/versandlieferung/" title="<?= $this->translate('footer_delivery') ?>"><?= $this->translate('footer_delivery') ?></a></li>
                            <li><a href="/<?= $helpPrefix ?>/kontakt/" rel="nofollow" title="<?= $this->translate('footer_contact') ?>"><?= $this->translate('footer_contact') ?></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 mx-auto">
                        <ul class="list-unstyled">
                            <li><a href="/<?= $helpPrefix ?>/gesetzlichebestimmungen/" rel="nofollow" title="<?= $this->translate('footer_law_info') ?>"><?= $this->translate('footer_law_info') ?></a></li>
                            <li><a href="/<?= $helpPrefix ?>/nutzungsbedingungen/" rel="nofollow" title="<?= $this->translate('footer_usage') ?>"><?= $this->translate('footer_usage') ?></a></li>
                            <li><a href="/<?= $helpPrefix ?>/datenschutz/" rel="nofollow" title="<?= $this->translate('footer_privacy') ?>"><?= $this->translate('footer_privacy') ?></a></li>
                            <li class="lastListElem"><a href="/<?= $helpPrefix ?>/impressum/" rel="nofollow" title="<?= $this->translate('footer_impress') ?>"><?= $this->translate('footer_impress') ?></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 mx-auto">
                        <ul class="list-unstyled">
                            <li><a href="/verkaufen/" title="<?= $this->translate('footer_sell') ?>"><?= $this->translate('footer_sell') ?></a></li>
                            <li><a href="/wholesale/" title="<?= $this->translate('footer_wholesale') ?>"><?= $this->translate('footer_wholesale') ?></a></li>
                            <li><a href="/genossenschaft/" title="<?= $this->translate('Genossenschaft') ?>"><?= $this->translate('Genossenschaft') ?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright text-center py-3">
                &copy; Epelia <?= date('Y', time()) ?>
            </div>
        </footer>
    </div>
  </body>
</html>