<div class="row">
    <div class="col-2 bg-light border m-3">
        <h5><?= $this->escape($this->group->name) ?> (<?= $this->escape($this->productCount) ?>)</h5>
        <ul class="categoryList">
<?php foreach($this->group->getCategories() as $cat): ?>
            <li><a href="/categories/<?= $this->escape($cat->id) ?>/" title="<?= $this->escape($cat->name) ?>"><?= $this->escape($cat->name) ?></a></li>
<?php endforeach; ?>
<!--
            <li class="filter_bio" style="padding-bottom:5px;">
                <input id="i_bio" type="checkbox" class="filter" value="bio" name="only_bio"<?php if($this->onlyBio): ?> checked="checked"<?php endif; ?> />
                <label style="display:inline" for="i_bio"><a><?= $this->translate('filter_bio') ?></a></label>
            </li>
            <li class="filter_discount" style="padding-bottom:5px;">
                <input id="i_discount" type="checkbox" class="filter" value="discount" name="only_discount"<?php if($this->onlyDiscount): ?> checked="checked"<?php endif; ?> />
                <label style="display:inline" for="i_discount"><a><?= $this->translate('filter_discount') ?></a></label>
            </li>
-->
        </ul>
    </div>
    <div class="col bg-light border m-3">
        <h2><?= $this->escape($this->group->name) ?></h2>
<?= $this->partial('partials/productgrid.phtml', array('products' => $this->group->getProducts(9, ($this->page > 1) ? (9 * $this->page - 9) : null, $this->onlyBio, $this->onlyDiscount, $this->onlyWholesale))) ?>
<?php if($this->productCount): ?>
        <br />
        <?= $this->partial('partials/pagination.phtml', array('type' => 'groups', 'id' => $this->group->id, 'page' => $this->page, 'productCount' => $this->productCount, 'onlyBio' => $this->onlyBio, 'onlyDiscount' => $this->onlyDiscount, 'onlyWholesale' => $this->onlyWholesale)); ?>
<?php endif; ?>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function(){
        $('.filter').change(function(){
            var bio = ($('#i_bio').is(':checked'));
            var discount = ($('#i_discount').is(':checked'));
            var pathnameAttr = $(location).attr('pathname').split('/');
            if(!bio && !discount){
                location.href = '/' + pathnameAttr[1] + '/' + pathnameAttr[2] + '/';
            }
            else{
                if(!pathnameAttr[5]) pathnameAttr[5] = 'all';
                pathnameAttr[6] = 1;
                location.href = '/' + pathnameAttr[1] + '/' + pathnameAttr[2] + '/' + ((bio) ? 'bio' : 'all') + '/' + ((discount) ? 'discount': 'all') + '/' + pathnameAttr[5] + '/' + pathnameAttr[6] + '/';
            }
        });
    });

</script>
