<div class="row">
    <div class="col bg-light border m-3">
        <h2><?= $this->translate('sell_headline') ?></h2>
        <h5><?= $this->translate('sell_1') ?></h5>
        <p><?= $this->translate('sell_2') ?></p>
        <h5><?= $this->translate('sell_3') ?></h5>
        <p><?= $this->translate('sell_4') ?></p>
        <h5><?= $this->translate('sell_5') ?></h5>
        <p><?= $this->translate('sell_6') ?></p>
        <h5><?= $this->translate('sell_7') ?></h5>
        <p><?= $this->translate('sell_8') ?></p>

        <h5><?= $this->translate('sell_9') ?></h5>
        <a class="btn btn-outline-secondary" href="/verkaufen/register/" title="<?= $this->translate('sell_register') ?>"><?= $this->translate('sell_register') ?></></a>
        <p><?= $this->translate('sell_phone') ?></p>
    </div>
</div>