<div class="row">
    <div class="col bg-light border m-3">
        <h1>User hinzufügen / editieren</h1>
        <?= $this->form; ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        if($('#type').val() != 'agent'){
            $('#woma_id-label').hide();
            $('#woma_id-element').hide();
            $('#woma_id').val(0);
        }
    });
    $('#type').change(function(){ 
        if($('#type').val() != 'agent'){
            $('#woma_id-label').hide();
            $('#woma_id-element').hide();
            $('#woma_id').val(0);
        }
        else{
            $('#woma_id-label').show();
            $('#woma_id-element').show();
        }                             
    });
</script>
