<h1 style="margin-bottom:5px;">Benutzer</h1>
<a href="/admin/users/edit/">Neuen Benutzer anlegen</a>
<h2>Benutzer</h2>
<table class="table" id="userTable">
    <thead>
    <tr><th>ID</th><th>E-Mail</th><th>Typ</th><th>Adresse</th><th>Großhändler?</th><th>Status</th><th>Registriert</th><th>Letzter Login</th><th>Aktionen</th></tr>
    </thead>
    <tbody>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        $('#userTable').dataTable({
            "sDom": "<'row'<'span6'l><''f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "bFilter": false,
            "bSort": false,
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "/admin/users/ajaxgetusers/",
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
           
</script>
