<div class="row">
    <div class="col bg-light border m-3">
        <h1>Benutzer</h1>
        <a href="/admin/users/edit/">Neuen Benutzer anlegen</a>
        <h2>Benutzer</h2>
        <table class="table" id="userTable">
            <thead>
            <tr><th>ID</th><th>E-Mail</th><th>Typ</th><th>Adresse</th><th>Großhändler?</th><th>Status</th><th>Registriert</th><th>Letzter Login</th><th>Aktionen</th></tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#userTable').dataTable({
            "bFilter": true,
            "bSort": false,
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "/admin/users/ajaxgetusers/",
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen (ID, E-Mail, Adresse) ",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
           
</script>
