<div class="row">
    <div class="col bg-light border m-3">
        <h1>Kategorie hinzufügen / editieren</h1>
        <?= $this->form; ?>
    </div>
</div>

<script type="text/javascript">

    $('#type').change(function(){ 
        $.ajax({ 
            url: '/ajax/getgroups/type/' + $('#type').val(), 
            datatype: 'html', 
            success: function(data){ 
                $('#product_group_id').empty().html(data); 
            } 
        }); 
    });
</script>
