<h1 style="margin-bottom:5px;">Produktvorstellungen</h1>
<a href="/admin/productshome/edit/">Neue Vorstellungsgruppe anlegen</a>
<table class="table">
    <thead>
    <tr><th>Name</th><th>Produkte</th><th>Aktionen</th></tr>
    </thead>
    <tbody>
<?php foreach($this->homegroups as $group): ?>
    <tr><td><?= $this->escape($group->name) ?></td><td><?= count($group->getProducts(null, null, false, false, false, false)) ?></td><td><a href="/admin/productshome/edit/id/<?= $this->escape($group->id) ?>">Editieren</a>&nbsp;<a href="/admin/productshome/bygroup/id/<?= $this->escape($group->id) ?>/">Produkte</a>&nbsp;<a href="/admin/productshome/delete/id/<?= $this->escape($group->id) ?>">Löschen</a></td></tr>
<?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        $('#catTable').dataTable({
            "sDom": "<'row'<'span6'l><''f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aoColumns": [
                null, 
                null, 
                { "bSortable": false } 
            ],
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "_MENU_ Einträge anzeigen",
                "sZeroRecords": "Keine Einträge vorhanden.",
                "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            }
        });
    });
          
</script>
