<h3 style="margin-top:10px;"><?= $this->escape($this->groupTitle) ?></h3>
<div class="row">
<?php
$counter = 0;
foreach($this->groups as $group):
    $counter++;
    $href = '/groups/' . $group->id . '/';
    if($this->onlyBio || $this->onlyDiscount || $this->onlyWholesale){
        $href .= ($this->onlyBio) ? 'bio' : 'all';
        $href .= '/';
        $href .= ($this->onlyDiscount) ? 'discount' : 'all';
        $href .= '/';
        $href .= ($this->onlyWholesale) ? 'wholesale' : 'all';
        $href .= '/1/';
    }
?>
    <div class="col-4">
        <div class="card bg-light m-3">
            <div class="card-header">
                <a href="<?= $this->escape($href) ?>" title="<?= $this->escape($group->name) ?>"><?= $this->escape($group->name) ?></a>
            </div>
            <div class="card-body">
                <ul class="list-group">
<?php
$group->clearCategories();
foreach($group->getCategories($this->onlyBio, $this->onlyDiscount, $this->onlyWholesale) as $cat):
    $catHref = '/categories/' . $cat->id . '/';
    if($this->onlyBio || $this->onlyDiscount || $this->onlyWholesale){
        $catHref .= ($this->onlyBio) ? 'bio' : 'all';
        $catHref .= '/';
        $catHref .= ($this->onlyDiscount) ? 'discount' : 'all';
        $catHref .= '/';
        $catHref .= ($this->onlyWholesale) ? 'wholesale' : 'all';
        $catHref .= '/1/';
    }
?>
    <li class="list-group-item d-flex justify-content-between align-items-center"><a href="<?= $this->escape($catHref) ?>" title="<?= $this->escape($cat->name) ?>"><?= $this->escape($cat->name) ?></a><span class="badge badge-success badge-pill"><?= $this->escape($cat->getProductCount($this->onlyBio, $this->onlyDiscount, $this->onlyWholesale)) ?></span></li>
<?php
endforeach;
?>
                </ul>
            </div>
        </div>
    </div>

<?php 
    if(($counter)%3 == 0 && $counter > 0): 
?>
    </div>
    <div class="row">
<?php
    endif;
endforeach;
?>

</div>
