<div id="content_static" class="">
    
    <h2>Ordering on Epelia</h2>


    <div class="relevant_content">
    
        <h3>Why should I order something on Epelia?</h3>
        
        <p>Epelia enables producers and customers to come together. Instead of investing much effort to search for the food producers by themselves, customers will find everything inone place on Epelia. For producers, Epelia makes it possible to sell directly to customers, avoiding the detour route through traders.</p>
        
        <p class="clear space"></p>
    
        <h3>How can I order on Epelia?</h3>
        
        <p>You select the products that you like, put them into the shopping cart and proceed to checkout. During the whole order process, you can modify order amounts and remove and add products. Within one single order, you can order and pay products from different producers. Shipment is organized by every producer, directly from their manufacture to you.</p>
        
        <p class="clear space"></p>
        
        <h3>What happens to my personal data?</h3>
        
        <p>When ordering, you have to provide an e-mail address and a shipment / invoice address. This is required in order to ship your purchase to you. We require your e-mail address so that we can contact you if any difficulty arises with the delivery.<br/>
You do not have to worry that your personal data might get into the wrong hands. We handle this data very carefully and adhere to the strict rules of German data privacy law.</p>
        
        <p class="clear space"></p>
        
        <h3>Is there a minimum order amount?</h3>
        
        <p>No, all sellers deliver to you without a minimum order amount.</p>
        
        <p class="clear space"></p>
        
        <h3>Can I modify or cancel my order after confirming it?</h3>
        
        <p>If ou want to modify order amounts or other information about your order, please let us know immediately. Write an e-mail to mail@epelia.com or call us at +49 1803 465283 ("+49 180 EINKAUF"; 9 ct/min from the landline network of German Telekom; different rates may apply from mobile networks). We will make an effort to modify your order according to your wishes.</p>
        
        <p class="clear space"></p>
        
        <h3>How can I report difficulties with an order?</h3>
        
        <p>You can contact our customer service anytime, either by phone at +49 1803 465283 ("+49 180 EINKAUF"; 9 ct/min from the landline network of German Telekom; different rates may apply from mobile networks) or by e-mail to mail@epelia.com.</p>
        
        <p class="clear space"></p>
        
        <h3>Can I order by e-mail, fax or phone?</h3>
        
        <p>If you cannot order online on the Epelia marketplace, you are welcome to call us, write us an e-mail or send us a fax.</p>
        
        <p class="clear space"></p>
        
        <h3>Can I order from abroad?</h3>
        
        <p>Yes, nearly all manufactures offer international shipment. You find the delivery locations and associated shipment costs in the shops of the respective producer, at “Delivery &amp; Shipment”.</p>
        
        
    </div>

    
<div style="float:right; width:235px;">

    <div class="sidebar">
        <ul>
            <li class="title">Help</li>
            <li>
                <a href="/hilfeeng/ueber-kisju" title="Über Epelia">About Epelia</a>           </li>
            <li>
                Ordering on Epelia            </li>
            <li>
                <a href="/hilfeeng/bezahlung" title="Zahlungsmöglichkeiten">Payment options</a>         
            </li>
            <li>
                <a href="/hilfeeng/versandlieferung" title="Versand und Lieferung">Shipment and Delivery</a>         </li>
        </ul>
        
        <ul style="border-top:1px solid #e3e2d0; padding-top:16px;">            
            <li>
                <a href="/verkaufen" title="Epelia für Verkäufer">Epelia for sellers</a>
            </li>
        </ul>   
        
    </div>
    
    <a href="/" title="Frau | Ich liebe Epelia | Epelia Startseite">
        <img src="/resources/images/banner/extern/de/fan_iloveepelia_f_250x250.jpg" alt="Frau | Ich liebe Epelia" width="235px" />
    </a>

</div>  

</div>
