<div id="content_static" class="">
    
    <h2>Payment options</h2>


    <div class="relevant_content">
        
        <h3>Which payment options does Epelia offer?</h3>
        
        <table class="" cellpadding="0" cellspacing="0">
            <tr>
                <td class="method">Advance payment</td>
                <td class="description">After you sent in your order, you will get an e-mail confirming that your order has been received. This e-mail contains all data about your order and the payment details. Then please pay the indicated amount with via transfer. Your order will be shipped promptly after receiving your payment.</td>
            </tr>
            <tr>
                <td class="method">Sofortüberweisung (immediate bank transfer by SOFORT AG)</td>
                <td class="description">If you have online banking access to your bank account, you can pay simply and comfortably with Sofortüberweisung. Sofortüberweisung means that you fill in the bank transfer form for your order right within the order process, and send it in online. This payment option is certified by German TÜV and offers transaction security checked by TÜV.</td>
            </tr>
            <tr>
                <td class="method">Direct debit</td>
                <td class="description">If you choose direct debit, we will deduct the invoice amount from your bank account.<br/>
This payment option is available to Epelia customers with a German bank account from their third order on.</td>
            </tr>
        </table>
        
        <p class="clear" style="padding-bottom:12px;"></p>
        
        <h3>How secure is ordering online at Epelia?</h3>
        
        <p>Very secure. When something is ordered, all data is transferred exclusively over a SSL secured connection. No third party can get access to your data. Epelia fulfills the strict German privacy laws.</p>
                
    </div>

    
<div style="float:right; width:235px;">

    <div class="sidebar">
        <ul>
            <li class="title">Help</li>
            <li>
                <a href="/hilfeeng/ueber-kisju" title="Über Epelia">About Epelia</a>           </li>
            <li>
                <a href="/hilfeeng/bestellen" title="Bestellen bei Epelia">Ordering on Epelia</a>           </li>
            <li>
                Payment options           
            </li>
            <li>
                <a href="/hilfeeng/versandlieferung" title="Versand und Lieferung">Shipment and delivery</a>         </li>
        </ul>
        
        <ul style="border-top:1px solid #e3e2d0; padding-top:16px;">            
            <li>
                <a href="/verkaufen" title="Epelia für Verkäufer">Epelia for sellers</a>
            </li>
        </ul>   
        
    </div>
    
    <a href="/" title="Frau | Ich liebe Epelia | Epelia Startseite">
        <img src="/resources/images/banner/extern/de/fan_iloveepelia_f_250x250.jpg" alt="Frau | Ich liebe Epelia" width="235px" />
    </a>

</div>  

</div>
