<div id="content_static" class="">
    
    <h2>payment options (shipping from donor)</h2>


    <div class="relevant_content">
        
        <h3>Which payment methods does Sachspendenbörse offer?</h3>
        
        <table class="" cellpadding="0" cellspacing="0">
            <tr>
                <td class="method">Advance payment</td>
                <td class="description">After completing your order with Sachspendenbörse, you will receive a confirmation email about the receipt of your order. This e-mail contains all the order data and payment information. Please then transfer the specified amount; after receipt of payment your goods will be shipped immediately.</td>
            </tr>
            <tr>
                <td class="method">Sofortüberweisung (immediate bank transfer by SOFORT AG)</td>
                <td class="description">If you have online banking access to your account, you can pay very easily and conveniently by instant bank transfer. Instant bank transfer means that you fill out the transfer form for the order value within the order process and send it online. This payment method is TÜV-certified and offers TÜV-tested transaction security.</td>
            </tr>
            <tr>
                <td class="method">Direct debit</td>
                <td class="description">If you choose direct debit, we will deduct the invoice amount from your bank account.<br/>
This payment option is available to Sachspendenbörse customers with a German bank account from their third order on.</td>
            </tr>
        </table>
        
        <p class="clear" style="padding-bottom:12px;"></p>
        
        <h3>How secure is ordering online at Sachspendenbörse?</h3>
        
        <p>Very secure. When something is ordered, all data is transferred exclusively over a SSL secured connection. No third party can get access to your data. Sachspendenbörse fulfills the strict German privacy laws.</p>
                
    </div>

    
<div style="float:right; width:235px;">

    <div class="sidebar">
        <ul>
            <li class="title">Help</li>
            <li>
                <a href="/hilfeeng/ueber-Sachspendenbörse" title="Über Sachspendenbörse">About Sachspendenbörse</a>           </li>
            <li>
                <a href="/hilfeeng/bestellen" title="FAQ">FAQ</a>           </li>
            <li>
                Payment options           
            </li>
            <li>
                <a href="/hilfeeng/versandlieferung" title="Versand und Lieferung">Shipment and delivery</a>         </li>
        </ul>
        
        <ul style="border-top:1px solid #e3e2d0; padding-top:16px;">            
            <li>
                <a href="/verkaufen" title="Epelia für Verkäufer">Epelia for sellers</a>
            </li>
        </ul>   
        
    </div>
    
    <a href="/" title="Frau | Ich liebe Epelia | Epelia Startseite">
        <img src="/resources/images/banner/extern/de/fan_iloveepelia_f_250x250.jpg" alt="Frau | Ich liebe Epelia" width="235px" />
    </a>

</div>  

</div>
