<div id="content_static">

    <h2>Datenschutzbestimmungen</h2>
    
    <div class="relevant_content">
        <p>
            <h4>Datenschutzerklärung</h4><br/>
Liebe Kundinnen und Kunden,<br/>
Das Unternehmen Epelia und alle bei Epelia vertretenen Manufakturen verpflichten sich, Ihre Privatsphäre und Ihre persönlichen Daten zu schützen und personenbezogene Daten ausschließlich nach den strengen Vorschriften des deutschen Datenschutzrechts zu erheben, zu nutzen und zu verarbeiten.<br/>
<br/>
<strong>Datenerhebung</strong><br/>
Wir erheben Daten beim Anbahnen, beim Abschluss, beim Abwickeln und beim Rückabwickeln eines Kaufvertrages. Diese Daten werden von uns erhoben, gespeichert und verarbeitet. <br/>
<br/>
Ihr Besuch auf den Webseiten von Epelia wird protokolliert. Erfasst werden im Wesentlichen die aktuell von Ihrem PC verwendete IP-Adresse, Datum und Uhrzeit, der Browsertyp und das Betriebssystem Ihres PC sowie die von Ihnen betrachteten Seiten. Ein Personenbezug ist uns im Regelfall nicht möglich und auch nicht beabsichtigt.<br/>
<br/>
Zudem werden auf den Websites zu Marketing- und Optimierungszwecken anonymisierte Daten durch eine Software der Google Inc., namentlich von GoogleAnalytics (http://www.google.de/analytics/de-DE/) gesammelt und gespeichert. Aus diesen Daten werden unter einem Pseudonym Nutzungsprofile erstellt. Hierzu können Cookies eingesetzt werden, die allerdings Daten ausschließlich in pseudonymer Form sammeln und speichern. Die Daten werden nicht dazu benutzt, den Besucher persönlich zu identifizieren und werden nicht mit Daten über den Träger des Pseudonyms zusammengeführt. <br/>
Der Datensammlung und -speicherung kann jederzeit mit Wirkung für die Zukunft widersprochen werden. Diese Daten werden nur für Zwecke der Datensicherheit und zur Optimierung unseres Webangebots erhoben. <br/>
 <br/>
<strong>Datenverwendung und -weitergabe, Bonitätsprüfung</strong><br/>
Die personenbezogenen Daten, die Sie uns z.B. bei einer Bestellung oder per E-Mail mitteilen (z.B. Ihr Name und Ihre Adresse oder Ihre E-Mail-Adresse), werden nur zur Korrespondenz mit Ihnen und nur für den Zweck verarbeitet, zu dem Sie uns die Daten zur Verfügung gestellt haben. <br/>
Wir geben Ihre Daten nur an das mit der Lieferung beauftragte Versandunternehmen weiter, soweit dies zur Lieferung der Waren notwendig ist. Zur Abwicklung von Zahlungen geben wir Ihre Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut weiter.<br/>
<br/>
Um Ihnen wiederholte Eingaben Ihrer Daten zu ersparen, speichern wir in Ihrem Account Daten wie Adressen, E-Mail-Adressen, Name, Passwort, Zahlungsarten, Bestellhistorien.<br/>
Ebenfalls speichern wir Ihre Daten um den Einkauf für Sie soweit als möglich zu personalisieren und Ihnen kompetente Fachberatung geben zu können, z.B. indem wir Ihnen Produkte vorschlagen anhand Ihrer Käufe und Besuche oder Ihre Einkaufszettel mit den früheren Bestellungen zum erneutem Kauf anbieten. Oder um Sie über neue Produkte und Dienstleistungen zu informieren.<br/>
<br/>
Wir versichern, dass wir Ihre personenbezogenen Daten im übrigen nicht an Dritte weitergeben, es sei denn, dass wir dazu gesetzlich verpflichtet wären oder Sie uns vorher Ihre Zustimmung gegeben haben. Soweit wir zur Durchführung und Abwicklung von Verarbeitungsprozessen Dienstleister in Anspruch nehmen, werden die Vertragsverhältnisse nach den Bestimmungen des Bundesdatenschutzgesetzes geregelt. <br/>
<br/>
<strong>Einwilligung und Widerruf</strong><br/>
Mit Absenden der Bestellung erklären Sie sich damit einverstanden, dass Ihre Daten wie  beschrieben von uns erhoben, verarbeitet und genutzt werden  Wenn Sie uns personenbezogene Daten überlassen haben, können Sie diese jederzeit wieder löschen. Daten für Abrechnungs- und buchhalterische Zwecke sind von einer Kündigung/einem Widerruf bzw. von einer Löschung nicht berührt. <br/>
<br/>
<strong>Speicherdauer</strong><br/>
Personenbezogene Daten, die uns über unsere Website mitgeteilt worden sind, werden nur so lange gespeichert, bis der Zweck erfüllt ist, zu dem sie uns anvertraut wurden. Soweit handels- und steuerrechtliche Aufbewahrungsfristen zu beachten sind, kann die Speicherdauer zu bestimmten Daten bis zu 10 Jahre betragen.<br/>
<br/>
<strong>Kundenkonto</strong><br/>
Wenn Sie ein Kundenkonto eröffnen, willigen Sie damit ein, dass Ihre Bestandsdaten wie Name, Adresse, E-Mailadresse, und Bankverbindung sowie Ihre Nutzungsdaten (Benutzername, Passwort) gespeichert werden. Dadurch haben Sie die Möglichkeit, mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort auf dem Internet-Marktplatz epelia.com und in den angeschlossenen Onlineshops zu bestellen. <br/>
<br/>
<strong>Newsletter</strong><br/>
Mit der Anmeldung zum Newsletter werden Ihr Vorname, Ihr Nachname und Ihre E-Mail-Adresse mit Ihrer Einwilligung für eigene Werbezwecke genutzt. Der Versand des Newsletters erfolgt durch das Unternehmen Epelia. <br/>
<br/>
Die Einwilligung zum Empfang eines Newsletters per E-Mail ist jederzeit widerrufbar. In jedem Newsletter finden Sie dazu einen Link, mit dem Sie Ihre Einwilligung widerrufen können.<br/>
<br/>
<strong>Ihre Rechte</strong><br/>
Sollten Sie mit der Speicherung Ihrer personenbezogenen Daten nicht mehr einverstanden oder diese unrichtig geworden sein, werden wir auf eine entsprechende Weisung hin die Löschung oder Sperrung Ihrer Daten veranlassen oder die notwendigen Korrekturen vornehmen (soweit dies nach dem geltendem Recht möglich ist). Auf Wunsch erhalten Sie unentgeltlich Auskunft über alle personenbezogenen Daten, die wir über Sie gespeichert haben.<br/>
<br/>
Bei Fragen zur Erhebung, Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, bei Auskünften, Berichtigung, Sperrung oder Löschung von Daten wenden Sie sich bitte an:<br/>
<br/>
Epelia, Telefon: 0180 EINKAUF (01803 465283; 9 ct/min aus dem Deutschen Festnetz; aus Mobilfunknetzen können abweichende Preise gelten), E-Mail: mail@epelia.com<br/>
<br/>
<strong>Verwendung von Cookies</strong><br/>
Eine Nutzung des Angebotes von Epelia erfolgt mit dem Einsatz eines Cookies. Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Browsereinstellungen aktiviert haben. <br/>
<br/>
In dem Cookie wird ein zufällig generierter Session-Code und gegebenenfalls Ihre Kunden-ID gespeichert. Damit ist es möglich, Sie als registrierter Kunden zu erkennen.<br/>
<br/>
Zusätzlich speichert Epelia, falls vorhanden, eine Affiliate-ID und die Seite, von der aus Sie auf unsere Seiten gekommen sind.<br/>
<br/>
Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Einstellungen aktiviert haben. <br/>
<br/>
<strong>Änderungen dieser Erklärung</strong><br/>
Soweit wir neue Produkte oder Dienstleistungen einführen, Internet-Verfahren ändern oder wenn sich die Internet- und EDV-Sicherheitstechnik weiterentwickelt, ist die Datenschutzerklärung zu aktualisieren. Wir behalten uns deshalb das Recht vor, die Erklärung nach Bedarf zu ändern oder zu ergänzen. Die Änderung werden wir an dieser Stelle veröffentlichen. Daher sollten Sie diese Website regelmäßig aufrufen, um sich über den aktuellen Stand der Datenschutzerklärung zu informieren.     </p>        
    </div>
    
</div>
