<div id="content_static">

    <h2>Data protection regulations</h2>
    
    <div class="relevant_content">
        <p>
            <h4>Data protection declaration</h4><br/>
Dear customers,<br/>
OpenFoodBank is an offer of Fairdirect registered association, Konrad Becker road 11 in 35102 Lohra. We are committed to protecting your privacy and your personal data and to collecting, using and processing personal data exclusively according to the strict regulations of the German data protection law.<br/>
<br/>
<strong>data collection</strong><br/>
We collect data during the initiation, conclusion and handling of the procurement of donations in kind via the digital marketplace www.openfoodbank.net. These data are collected, stored and processed by us. <br/>
<br/>
Your visit to the OpenFoodBank websites is logged. Essentially, the IP address currently used by your PC, the date and time, the browser type and operating system of your PC and the pages you view are recorded. As a rule, it is not possible and not intended for us to make any personal reference to you.<br/>
<br/>
The collection and storage of data can be objected to at any time with effect for the future. This data is only collected for the purpose of data security and to optimize our web offer.<br/>
 <br/>
<strong>Data use and transfer</strong><br/>
The personal data that you provide us, e.g. in the case of a donation arrangement or by e-mail (for example your name and address or your e-mail address), will only be processed for correspondence with you and only for the purpose for which you have made the data available to us. <br/>
<br/>
We only pass on your data to the transport service providers commissioned with the delivery if you use the OpenFoodBank transport exchange. For the handling of shipping costs we will pass on your payment data to the credit institute commissioned with the payment. In these cases, we will only pass on your data on condition that they commit themselves to us by contract to respect the protection of your data.<br/>
<br/>      
In order to save you from having to enter your data repeatedly, we store data such as addresses, e-mail addresses, name, password, payment methods, order histories in your account.<br/>
Ebenfalls speichern wir Ihre Daten um den Einkauf für Sie soweit als möglich zu personalisieren und Ihnen kompetente Fachberatung geben zu können, z.B. indem wir Ihnen Produkte vorschlagen anhand Ihrer Käufe und Besuche oder Ihre Einkaufszettel mit den früheren Bestellungen zum erneutem Kauf anbieten. Oder um Sie über neue Produkte und Dienstleistungen zu informieren.<br/>
<br/>
We assure you that we will not pass on your personal data to third parties unless we are legally obliged to do so or you have given us your prior consent. If we use service providers for the execution and handling of processing procedures, the contractual relationships are regulated in accordance with the provisions of the Federal Data Protection Act.<br/>
<br/>
<strong>consent and revocation </strong><br/>
By sending the donation order, you agree that your data will be collected, processed and used as described above If you have provided us with personal data, you can delete it at any time. Data for accounting and bookkeeping purposes are not affected by a cancellation/revocation or deletion.<br/>
<br/>
<strong>storage time</strong><br/>
ersonal data that has been communicated to us via our website will only be stored until the purpose for which it was entrusted to us has been fulfilled. Insofar as storage periods under commercial and tax law must be observed, the storage period for certain data can be up to 10 years.<br/>
<br/>
<strong>customer account</strong><br/>
When you open a customer account on www.openfoodbank.net, you agree that your inventory data such as name, address, e-mail address, and bank details as well as your usage data (user name, password) are stored. Thus you have the possibility to order with your e-mail address and your personal password on www.openfoodbank.net and the online donation stores connected there.<br/>
<br/>
<strong>Newsletter</strong><br/>
By registering for the newsletter, your first name, last name and e-mail address will be used with your consent for our own advertising purposes. The newsletter is sent by Fairdirect e.V.<br/>
<br/>
The consent to receive a newsletter by e-mail can be revoked at any time. In every newsletter you will find a link with which you can revoke your consent.<br/>
<br/>
<strong>your rights</strong><br/>
If you no longer agree with the storage of your personal data or if it has become incorrect, we will, upon your instruction, arrange for the deletion or blocking of your data or make the necessary corrections (as far as this is possible under the applicable law). Upon request, you will receive information free of charge about all personal data that we have stored about you.<br/>
<br/>
 If you have any questions regarding the collection, processing or use of your personal data, or if you would like information, correction, blocking or deletion of data, please contact:<br/>
<br/>
 Fairdirect e.V., Phone: +49 6426 8630364, E-Mail: mail@fairdirect.org<br/>
<br/>
<strong>use of cookies</strong><br/>
The use of the OpenFoodBank service is done with the use of a cookie. The prerequisite for this is that you have activated the cookies in your browser settings.<br/>
<br/>
A randomly generated session code and, if applicable, your customer ID is stored in the cookie. This makes it possible to recognize you as a registered customer.<br/>
<br/>
The prerequisite for this is that you have activated cookies in your settings.<br/>
<br/>
<strong>Changes to this declaration</strong><br/>
If we introduce new products or services, change Internet procedures or if the Internet and EDP security technology develops further, the data protection declaration must be updated. We therefore reserve the right to amend or supplement the declaration as required. We will publish the changes here. Therefore, you should visit this website regularly to inform yourself about the current status of the data protection declaration</p>        
    </div>
    
</div>
