<div id="content_static">

    <h2>Data protection regulations</h2>
    
    <div class="relevant_content">
        <p>
            <h4>Data protection declaration</h4><br/>
Dear customers,<br/>
OpenFoodBank is an offer of Fairdirect registered association, Konrad Becker road 11 in 35102 Lohra. We are committed to protecting your privacy and your personal data and to collecting, using and processing personal data exclusively according to the strict regulations of the German data protection law.<br/>
<br/>
<strong>data collection</strong><br/>
We collect data during the initiation, conclusion and handling of the procurement of donations in kind via the digital marketplace www.openfoodbank.net. These data are collected, stored and processed by us. <br/>
<br/>
Your visit to the OpenFoodBank websites is logged. Essentially, the IP address currently used by your PC, the date and time, the browser type and operating system of your PC and the pages you view are recorded. As a rule, it is not possible and not intended for us to make any personal reference to you.<br/>
<br/>
The collection and storage of data can be objected to at any time with effect for the future. This data is only collected for the purpose of data security and to optimize our web offer.<br/>
 <br/>
<strong>Data use and transfer</strong><br/>
The personal data that you provide us, e.g. in the case of a donation arrangement or by e-mail (for example your name and address or your e-mail address), will only be processed for correspondence with you and only for the purpose for which you have made the data available to us. <br/>
<br/>
We only pass on your data to the transport service providers commissioned with the delivery if you use the OpenFoodBank transport exchange. For the handling of shipping costs we will pass on your payment data to the credit institute commissioned with the payment. In these cases, we will only pass on your data on condition that they commit themselves to us by contract to respect the protection of your data.<br/>
<br/>      
In order to save you from having to enter your data repeatedly, we store data such as addresses, e-mail addresses, name, password, payment methods, order histories in your account.<br/>
Ebenfalls speichern wir Ihre Daten um den Einkauf für Sie soweit als möglich zu personalisieren und Ihnen kompetente Fachberatung geben zu können, z.B. indem wir Ihnen Produkte vorschlagen anhand Ihrer Käufe und Besuche oder Ihre Einkaufszettel mit den früheren Bestellungen zum erneutem Kauf anbieten. Oder um Sie über neue Produkte und Dienstleistungen zu informieren.<br/>
<br/>
We assure you that we will not pass on your personal data to third parties unless we are legally obliged to do so or you have given us your prior consent. If we use service providers for the execution and handling of processing procedures, the contractual relationships are regulated in accordance with the provisions of the Federal Data Protection Act.<br/>
<br/>
<strong>consent and revocation </strong><br/>
By sending the donation order, you agree that your data will be collected, processed and used as described above If you have provided us with personal data, you can delete it at any time. Data for accounting and bookkeeping purposes are not affected by a cancellation/revocation or deletion.<br/>
<br/>
<strong>storage time</strong><br/>
ersonal data that has been communicated to us via our website will only be stored until the purpose for which it was entrusted to us has been fulfilled. Insofar as storage periods under commercial and tax law must be observed, the storage period for certain data can be up to 10 years.<br/>
<br/>
<strong>customer account</strong><br/>
When you open a customer account on www.openfoodbank.net, you agree that your inventory data such as name, address, e-mail address, and bank details as well as your usage data (user name, password) are stored. Thus you have the possibility to order with your e-mail address and your personal password on www.openfoodbank.net and the online donation stores connected there.<br/>
<br/>
<strong>Newsletter</strong><br/>
Mit der Anmeldung zum Newsletter werden Ihr Vorname, Ihr Nachname und Ihre E-Mail-Adresse mit Ihrer Einwilligung für eigene Werbezwecke genutzt. Der Versand des Newsletters erfolgt durch Fairdirect e.V.<br/>
<br/>
Die Einwilligung zum Empfang eines Newsletters per E-Mail ist jederzeit widerrufbar. In jedem Newsletter finden Sie dazu einen Link, mit dem Sie Ihre Einwilligung widerrufen können.<br/>
<br/>
<strong>Ihre Rechte</strong><br/>
Sollten Sie mit der Speicherung Ihrer personenbezogenen Daten nicht mehr einverstanden oder diese unrichtig geworden sein, werden wir auf eine entsprechende Weisung hin die Löschung oder Sperrung Ihrer Daten veranlassen oder die notwendigen Korrekturen vornehmen (soweit dies nach dem geltendem Recht möglich ist). Auf Wunsch erhalten Sie unentgeltlich Auskunft über alle personenbezogenen Daten, die wir über Sie gespeichert haben.<br/>
<br/>
Bei Fragen zur Erhebung, Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, bei Auskünften, Berichtigung, Sperrung oder Löschung von Daten wenden Sie sich bitte an:<br/>
<br/>
Epelia, Telefon: 0180 EINKAUF (01803 465283; 9 ct/min aus dem Deutschen Festnetz; aus Mobilfunknetzen können abweichende Preise gelten), E-Mail: mail@epelia.com<br/>
<br/>
<strong>Verwendung von Cookies</strong><br/>
Eine Nutzung des Angebotes von Epelia erfolgt mit dem Einsatz eines Cookies. Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Browsereinstellungen aktiviert haben. <br/>
<br/>
In dem Cookie wird ein zufällig generierter Session-Code und gegebenenfalls Ihre Kunden-ID gespeichert. Damit ist es möglich, Sie als registrierter Kunden zu erkennen.<br/>
<br/>
Zusätzlich speichert Epelia, falls vorhanden, eine Affiliate-ID und die Seite, von der aus Sie auf unsere Seiten gekommen sind.<br/>
<br/>
Voraussetzung hierfür ist, dass Sie die Cookies in Ihren Einstellungen aktiviert haben. <br/>
<br/>
<strong>Änderungen dieser Erklärung</strong><br/>
Soweit wir neue Produkte oder Dienstleistungen einführen, Internet-Verfahren ändern oder wenn sich die Internet- und EDV-Sicherheitstechnik weiterentwickelt, ist die Datenschutzerklärung zu aktualisieren. Wir behalten uns deshalb das Recht vor, die Erklärung nach Bedarf zu ändern oder zu ergänzen. Die Änderung werden wir an dieser Stelle veröffentlichen. Daher sollten Sie diese Website regelmäßig aufrufen, um sich über den aktuellen Stand der Datenschutzerklärung zu informieren.     </p>        
    </div>
    
</div>
