<div id="content_static" class="">

    <h2>Gesetzliche Bestimmungen</h2>       
    
    <div class="relevant_content">
        <p>
<h4>Vertragsschluss und Speicherung der Bestellung</h4><br/>
Bei Bestellungen in unserem Onlineshop kommt der Vertrag zustande mit den jeweiligen Manufakturen, bei denen Sie bestellen.<br/>
<br/>
Das Unternehmen Epelia (Warenhandel Gattinge, Konrad-Becker-Str. 11, 35102 Lohra, Telefon 01803 465283, Umsatzsteuer-Ident-Nr. DE-163752546) wird nicht Vertragspartner hinsichtlich der über die Onlineshops der Manufakturen oder über das Shopping-Portal epelia.com erworbenen Artikel. Epelia nimmt im Namen der Manufakturen lediglich die Bestell- und Zahlungsabwicklung vor. <br/>
<br/>
Ihre Bestellung stellt ein Angebot an das jeweilige Unternehmen zum Abschluss eines Kaufvertrags dar. Nach Eingang der Bestellung wird Epelia Sie über den Eingang Ihrer Bestellung per E-Mail informieren (Bestellbestätigung) und nimmt Ihr Angebot namens und in Vollmacht des Verkäufers an. Die Manufaktur kann das Angebot innerhalb von zwei Wochen ab Eingang des Angebots des Bestellers bei Epelia annehmen.<br/>
<br/>
Bei der Bestellung über die Onlineshops auf dem Epelia-Shoppingportal umfasst der Bestellvorgang insgesamt 6 Schritte. Wenn Sie bereits ein Epelia-Kundenkonto angelegt haben, können Sie sich mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort anmelden. Sie können jedoch auch ohne die Registrierung eines Kundenkontos bei uns bestellen. <br/>
<br/>
Im zweiten Schritt geben Sie Ihre Kundendaten einschließlich Rechnungsanschrift und ggf. abweichender Lieferanschrift ein. Im dritten Schritt wählen Sie, wie Sie bezahlen möchten. Im Schritt 4 haben Sie unter "Prüfen und Bestellen" die Möglichkeit, sämtliche Angaben (z.B. Name, Anschrift, Zahlungsart, bestellter Artikel) nochmals zu überprüfen und ggf. zu ändern, bevor Sie Ihre Bestellung durch Betätigen des Buttons "Jetzt bestellen" an uns versenden. <br/>
<br/>
Sie haben optional die Möglichkeit, ein Kundenkonto anzumelden. Dadurch können Sie mit Ihrer E-Mailadresse und Ihrem persönlichen Passwort auf dem Shopping-Portal epelia.com und in allen angeschlossenen Online-Shops bestellen. <br/>
<br/>
Bei der telefonischen Bestellung werden die Bestelldaten mündlich bei Ihnen abgefragt und anschließend der Eingang der Bestellung per E-Mail an Ihre angegebene E-Mailadresse bestätigt. <br/>
<br/>
<h4>Zahlungsbedingungen</h4><br/>
Der Kaufpreis wird mit Abschluss des Kaufvertrages zur Zahlung fällig. <br/>
<br/>
Die Zahlung erfolgt über den Treuhandservice von Epelia, per Vorkasse durch Vorab-Überweisung, per Kreditkarte, per Sofortüberweisung oder per Lastschrifteinzug. Wir behalten uns vor, einzelne Zahlungsarten auszuschließen. Bei Wahl der Zahlungsart Vorkasse nennen wir Ihnen die Bankverbindung des Treuhandservices von Epelia in der Bestellbestätigung.<br/>
<br/>
Für den Fall der Nichteinlösung oder Rückgabe einer Lastschrift macht Epelia einen Schadenersatz in Höhe von EUR 15,00 geltend. Dem Besteller steht der Nachweis frei, dass ein Schaden nicht oder wesentlich niedriger entstanden ist. <br/>
Der Besteller ermächtigt seine Bank außerdem unwiderruflich, Epelia seinen Namen und seine aktuelle Anschrift mitzuteilen. <br/>
<br/>
Mit Eintritt des Zahlungsverzugs ist der Kaufpreis während des Verzuges in Höhe von 5% über dem Basiszinssatz zu verzinsen. Wir behalten uns vor, einen höheren Verzugsschaden nachzuweisen und geltend zu machen.<br/>
<br/>
Ein Recht zur Aufrechnung steht Ihnen nur dann zu, wenn Ihre Gegenansprüche rechtskräftig gerichtlich festgestellt oder unbestritten sind oder schriftlich durch uns anerkannt wurden.<br/>
<br/>
Sie können ein Zurückbehaltungsrecht nur ausüben, soweit die Ansprüche aus dem gleichen Vertragsverhältnis resultieren.     </p>        
    </div>
