<div id="content_static" class="">

    <h2>Imprint</h2>
    
    <div class="relevant_content">
        <p>Epelia<br/>
Warenhandel Gattinger<br/>
Konrad-Becker-Strasse 11<br/>
35102 Lohra<br/>
Germany<br/>
<br/>
Executive director: Micha Gattinger<br/>
Person responsible for content according to § 6 MDStV: Micha Gattinger<br/>
Data protection official: Matthias Ansorg<br/>
VAT ID: DE-163752546<br/>
<br/>
Contact<br/>
E-mail: mail@epelia.com<br/>
Phone: +49 1803 465283 ("+49 180 EINKAUF") (9 ct/min in the landline network of German Telekom; different rates may apply in mobile networks)<br/>
<br/>
Other notifications<br/>
The information on this website is being checked and updated regularly. Though applying due care, pieces of information may have changed. For that reason, we cannot guarantee for the up-to-dateness, correctness or completeness of the provided information. The same applies to all other websites to which this website refers by hyperlink. Epelia is not responsible for the content of websites that can be reached via such hyperlinks. Also we reserve the right to modify or complement the provided information.<br/>
<br/>
Content and structure of these websites are protected. The reproduction of information or data, esp. the use of texts, parts of texts or imagery, necessitates our prior consent.<br/>
<br/>
© 2011 Epelia. All rights reserved.</p>
    </div>
    
</div>
