<div id="content_static" class="">

    <h2>Contact</h2>    
        
    <div class="relevant_content">
        <p><b>You can reach Epelia by phone</b><br/>
Monday to Friday<br/>
from 9:00 am to 6:00 pm<br/>
under phone number +49 1803 465283 ("+49 180 EINKAUF"). (9 ct/min in the landline network of German Telekom; different rates may apply in mobile networks).<br/>
<br/>
<b>Or contact us by e-mail</b><br/>
E-Mail adress:  mail@epelia.com</p>
    </div>  

</div>
