<div id="content_static">

    <h2>Nutzungsbedingungen</h2>
    
    <div class="relevant_content">
        <p>
            <h4>Präambel</h4><br/>
Diese Nutzungsbedingungen regeln abschließend das Rechtsverhältnis zwischen dem Unternehmen Epelia, Warenhandel Gattinger (nachfolgend "Epelia") und den Käufern, die den Internet Marktplatz unter epelia.com nutzen und Artikel kaufen. <br/>
Das Vertragsverhältnis zwischen Epelia und den Verkäufern wird durch einen eigenen Vertrag geregelt. <br/>
Kaufverträge, welche über den Internet-Marktplatz epelia.com zustande kommen, gelten ausschließlich zwischen dem Verkäufer und dem Käufer. <br/>
Epelia wird nicht Partei dieser Verträge. Epelia erwachsen keinerlei Verpflichtungen im Hinblick auf die Erfüllung der zwischen den Verkäufern und Käufern zustande gekommenen Verträge<br/>
<br/>
<h4>Registrierung</h4><br/>
1. Die Nutzung von Epelia zur Suche nach Produkten, Shops und Mitgliedern ist ohne Registrierung möglich. <br/>
2. Für verschiedene Funktionen, wie das Speichern von Artikeln auf der Merkliste, das Kontaktieren von anderen Mitgliedern, die Kommentar- und Produktbewertungsfunktion sowie das Kaufen von Artikeln ist eine Registrierung als Mitglied erforderlich.<br/>
3. Die Registrierung ist nur juristischen Personen und unbeschränkt geschäftsfähigen natürlichen Personen erlaubt. Minderjährigen ist eine Anmeldung untersagt. <br/>
4. Die Anmeldung einer juristischen Person darf nur von einer vertretungsberechtigten natürlichen Person vorgenommen werden, die namentlich genannt werden muss. Bei der Anmeldung dürfen nur einzelne Personen als Inhaber des Mitgliedskontos angegeben werden.<br/>
5. Die bei der Anmeldung abgefragten Daten sind vollständig und wahrheitsgemäß anzugeben und durch den Kunden stets auf dem neuesten Stand zu halten.<br/>
6. Bei der Anmeldung wählt das Mitglied einen Benutzernamen und ein Passwort. Das Mitglied darf sein Passwort nicht an Dritte weitergeben. <br/>
7. Ein Mitgliedskonto ist nicht übertragbar.<br/>
8. Epelia behält sich das Recht vor, ein Mitgliedskonto zu löschen, insbesondere, <br/>
im Fall der Verwendung von Benutzernamen, welche gegen gesetzliche Verbote, die Rechte Dritter oder die guten Sitten verstoßen oder im Fall einer unvollständigen Anmeldung (z.B. bei nicht eingegebenem Bestätigungscode).<br/>
<br/>
<h4>Haftung</h4><br/>
1. Epelia haftet für Vorsatz und grobe Fahrlässigkeit seiner Organe, Mitarbeiter und Erfüllungsgehilfen uneingeschränkt, für leichte Fahrlässigkeit jedoch nur bei der Verletzung vertragswesentlicher Pflichten. Die Haftung bei Verletzung einer solchen vertragswesentlichen Pflicht ist auf den vertragstypischen Schaden begrenzt, mit dessen Entstehen Epelia bei Vertragsabschluss auf Grund der im Zeitpunkt des Vertragschluss bekannten Umstände rechnen musste. Unberührt hiervon ist die Haftung wegen Verzugs.<br/>
2. Epelia haftet nicht für die Richtigkeit der durch den Verkäufer eingestellten Angaben zum Kaufgegenstand.<br/>
3. Für von Epelia nicht zu vertretende Störungen innerhalb des Leitungsnetzes übernimmt Epelia keine Haftung.<br/>
4. Für den Verlust von Daten haftet Epelia nur dann, wenn ein solcher Verlust durch angemessene Datensicherungsmaßnahmen seitens des Käufers nicht vermeidbar gewesen wäre.<br/>
5. Wegen der von Zeit zu Zeit erforderlichen Wartungsarbeiten am Internet Marktplatz kann Epelia nicht gewährleisten, dass der Zugang zu epelia.com jederzeit und ohne Unterbrechungen möglich ist. Hieraus können gegen Epelia keine Ansprüche hergeleitet werde.<br/>
6. Die vorgenannten Haftungsausschlüsse und Beschränkungen gegenüber Unternehmern oder Verbrauchern gelten nicht im Fall der Übernahme ausdrücklicher Garantien durch Epelia und für Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit sowie im Fall zwingender gesetzlicher Regelungen.<br/>
<br/>
<h4>Änderung der Nutzungsbedingungen</h4><br/>
Epelia behält sich das Recht vor, diese Nutzungsbedingungen jederzeit und ohne Nennung von Gründen zu ändern. Epelia wird den Mitgliedern per E-Mail spätestens zwei Wochen vor ihrem Inkrafttreten die Änderungen mitteilen. Widerspricht ein Mitglied der Geltung der neuen Nutzungsbedingungen nicht innerhalb von zwei Wochen nach Empfang der E-Mail, gelten die geänderten Nutzungsbedingungen als angenommen. Epelia wird die Mitglieder in der E-Mail, die die geänderten Bestimmungen enthält, auf die Bedeutung dieser Zweiwochenfrist gesondert hinweisen.<br/>
<br/>
<h4>Schlussbestimmungen</h4><br/>
1. Erklärungen gegenüber Epelia bedürfen der Textform. Mündliche Willenserklärungen sind unwirksam.<br/>
2. Es gilt das Recht der Bundesrepublik Deutschland unter Ausschluss des UN-Kaufrechts. Handelt es sich beim Käufer um einen Kaufmann, ist ausschließlicher Gerichtsstand für alle Streitigkeiten aus dem Nutzungsverhältnis Berlin. In diesem Fall ist Epelia daneben berechtigt, auch am allgemeinen Gerichtsstand des Käufers zu klagen.<br/>
3. Sollten einzelne Bestimmungen dieser Nutzungsbedingungen unwirksam sein oder werden und/oder den gesetzlichen Regelungen widersprechen, so wird hierdurch die Wirksamkeit der Bedingungen im Übrigen nicht berührt. Die unwirksame Klausel gilt durch eine Regelung ersetzt, welche der unwirksamen wirtschaftlich am nächsten kommt.        </p>        
    </div>
    
</div>
