<div id="content_static" class="">

    <h2>Epelia</h2>

    <div class="relevant_content">
        
        <h3>What is Epelia?</h3>
        
        <p>Epelia is a central marketplace on which producers, manufactures and direct importers from German, Europe and the whole world sell food products directly to you. Most of the items available here are not available in usual food retail shops. All suppliers deliver their food products directly and without intermediate traders fresh to you.<br/>
<br/>
You will always get the best price in the shops on Epelia. These shops are operated by the sellers themselves, like their own webshops. When you order on Epelia, you order directly from these sellers.</p>
        
        <p class="clear space"></p>
        
        <h3>Who is behind Epelia?</h3>
        
        <p>143 producers, manufactures and direct importers. All sell on Epelia using their own webshops. Epelia offers their customers a simple possibility to order from 143 shops using just one shopping cart, one payment process and one customer account. On Epelia, you will discover new products and interesting specialties, and you can also read the product reviews created by other buyers from the Epelia community.</p>
        
        <p class="clear space"></p>
        
        <h3>Why does Epelia exist?</h3>
        
        <p>Let´s assume, you as a potential customer like buffallo mozzarella, Cretan olive oil and organically produced tea. You are trying to find where you can order these items directly from their producers. Usually, you would now have to look through numerous webshops on the Internet, select products, leave your address, and you would have to pay separately in all those shops.<br/>
<br/>
Epelia simplifies your shopping: you put all desired articles from all the different producers into one central shopping basket. You leave your order address once and pay everything together with one payment. The producers will ship your order directly to you and Epelia will forward your payment to the producers.</p>

        <p class="clear space"></p>

        <h3>What about the Epelia shipping cells?</h3>

        <p>Our <a href="/womas/musterhaeuser-wochenmarkt/">regional shipping cells</a> offer customers the option to purchase from multiple shops while paying for shipment only once. For example, shop providers who meet regularly as sellers on a farmers market can open a regional shipping cell on Epelia. This way, the new channel "online sale" can support traditional, tried and tested structures, as customers can also go online to look through offers and special offers of their regional farmers market but choose to visit and purchase in person.<br/>
<br/>
If you are interested in the details of this concept and how it may be useful to you (as, for example, a city government, a farmers market association or an administrative body for rural development), you can just send us and e-mail to <a href="mailto:mail@epelia.com">mail@epelia.com</a>.</p>
        
    </div>

    
<div style="float:right; width:235px;">

    <div class="sidebar">
        <ul>
            <li class="title">Help</li>
            <li>
                About Epelia</li>
            <li>
                <a href="/hilfeeng/bestellen" title="Bestellen bei Epelia">Ordering on Epelia</a>           </li>
            <li>
                <a href="/hilfeeng/bezahlung" title="Zahlungsmöglichkeiten">Payment options</a>         
            </li>
            <li>
                <a href="/hilfeeng/versandlieferung" title="Versand und Lieferung">Shipment and delivery</a>         </li>
        </ul>
        
        <ul style="border-top:1px solid #e3e2d0; padding-top:16px;">            
            <li>
                <a href="/verkaufen" title="Epelia für Verkäufer">Epelia for sellers</a>
            </li>
        </ul>   
        
    </div>
    
    <a href="/" title="Frau | Ich liebe Epelia | Epelia Startseite">
        <img src="/resources/images/banner/extern/de/fan_iloveepelia_f_250x250.jpg" alt="Frau | Ich liebe Epelia" width="235px" />
    </a>

</div>  

</div>

