<div id="content_static" class="">
    
    <h2>Shipment and delivery</h2>


    <div class="relevant_content">
        
        <h3>How does delivery work?</h3>
        
        <p>Your order on Epelia is immediately transferred to the producer. The producer will regularly pack and ship your parcel on the same day, but at latest on the following one. Shipment takes 1-2 days, depending on the shipment provider. Yoour products are always shipped directly from the producer to you.</p>
        
        <p class="clear space"></p>
        
        <h3>How is fresh food shipped?</h3>
        
        <p>Products that need to be refrigerated will be shipped in special cooling cardboard boxes with cooling elements. These keep your products fresh until they arrive at your location.</p>
        
        <p class="clear space"></p>
        
        <h3>How much are the shipment costs?</h3>
        
        <p>Every producer calculates their shipment costs for themselves. You can find the amount of their shipment costs indicated in their respective shop at “Delivery &amp; Shipment”.<br/>
Many producers offer free shipment from a certain order amount on. Again, you can find this information at “Delivery &amp; Shipment” of the respective producers.</p>
                
    </div>

    
<div style="float:right; width:235px;">

    <div class="sidebar">
        <ul>
            <li class="title">Help</li>
            <li>
                <a href="/hilfeeng/ueber-kisju" title="Über Epelia">About Epelia</a>           </li>
            <li>
                <a href="/hilfeeng/bestellen" title="Bestellen bei Epelia">Ordering on Epelia</a>           </li>
            <li>
                <a href="/hilfeeng/bezahlung" title="Zahlungsmöglichkeiten">Payment options</a>         
            </li>
            <li>
                Shipment and delivery           </li>
        </ul>
        
        <ul style="border-top:1px solid #e3e2d0; padding-top:16px;">            
            <li>
                <a href="/verkaufen" title="Epelia für Verkäufer">Epelia for sellers</a>
            </li>
        </ul>   
        
    </div>
    
    <a href="/" title="Frau | Ich liebe Epelia | Epelia Startseite">
        <img src="/resources/images/banner/extern/de/fan_iloveepelia_f_250x250.jpg" alt="Frau | Ich liebe Epelia" width="235px" />
    </a>

</div>  

</div>
