<div id="content_business">  
    <div id="rightcontent" class="account">        
        <p class="clear">&nbsp;</p>     
        <h1 class="business_h1">Allgemeine Geschäftsbedingungen für Verkäufer</h1>
        <p class="clear">&nbsp;</p>
        <p style="font-size:13px; line-height:21px;"><h4>0. Präambel</h4>Warenhandel Micha Gattinger (nachfolgend Epelia) betreibt das Internetportal epelia.com, auf welchem Unternehmer im Sinne des § 14 BGB und juristische Personen des privaten Rechts (nachfolgend Verkäufer) die Möglichkeit haben, gemäß den Vorgaben dieser AGB Lebensmittel über internetbasierte Webshops der Epelia-Plattform zu vertreiben. www.epelia.de ist als Internet-Marktplatz konzipiert, bei dem alle Kaufaktivitäten eines Kunden für alle beteiligten Webshops zentral über einen Warenkorb abgewickelt werden.<br/>
<br/>
2. Diese AGB enthalten abschließend die zwischen Epelia und den Verkäufern geltenden Bedingungen. Änderungen dieser AGB gelten nur dann, wenn sie von Epelia schriftlich bestätigt wurden.<br/>
<br/>
<h4>1. Leistungen von Epelia</h4>1. Epelia stellt den Verkäufern für deren Verkaufsaktivitäten auf der Epelia-Plattform einen standardisierten Webshop zur Verfügung. Epelia fungiert bei der Verkaufsabwicklung als Anbieter, der Marketingmaßnahmen durchführt, die Payment-Abwicklung übernimmt und technische und persönliche Unterstützung im Bestell-, Versand- und Retourenmanagement bietet.<br/>
<br/>
2. Auf der Epelia-Plattform werden die Artikel aller Verkäufer in verschiedenen Kategorien aufgelistet und durch unterschiedliche Maßnahmen beworben, insbesondere durch die Einbindung auf anderen Websites, Veröffentlichung in Medien und Werbung für Angebote in E-Mails an die Mitglieder der Epelia Community.<br/>
<br/>
3. Epelia behält sich das Recht vor, Inhalt und Struktur der Epelia-Plattform sowie die dazugehörigen Verkäuferoberflächen zu ändern oder zu erweitern, wenn hierdurch die Zweckerfüllung der mit den Verkäufern geschlossenen Verträge nicht oder nicht erheblich beeinträchtigt wird. Epelia wird den Verkäufer der Epelia-Plattform über die Änderungen entsprechend informieren. Epelia ist berechtigt,<br/>
seine Leistung zeitweise und in angemessenem Umfang einzuschränken, wenn dies zur Durchführung technischer Maßnahmen und Wartungsarbeiten erforderlich ist. Verkäufer werden vorab von diesen Arbeiten informiert.<br/>
<br/>
<h4>2. Zulassung zur Nutzung</h4>1. Voraussetzung für die Nutzung der Epelia–Plattform ist die Zulassung des Verkäufers durch Epelia.<br/>
<br/>
2. Das Verfahren zur Zulassung zur Nutzung regelt sich gemäß Anlage 2. Die Zulassung erfolgt durch Freischaltung des Webshops und oder die Übersendung einer Zulassungsbestätigung per E-Mail. Durch die Zulassung kommt ein Dienstvertrag zwischen Epelia und dem jeweiligen Verkäufer zustande.<br/>
<br/>
3. Bis zur Freischaltung des Epelia-Webshops besteht kein Recht auf den Vertrieb von Artikeln über die Epelia-Plattform.<br/>
<br/>
4. Der Verkäufer garantiert, dass die im Rahmen seines Antrages auf Zulassung gemachten Angaben wahr und vollständig sind. Er verpflichtet sich Epelia alle künftigen Änderungen der gemachten Angaben unverzüglich mitzuteilen. Er weist die Unternehmereigenschaft durch geeignete Belege nach.<br/>
<br/>
<h4>3. Pflichten Verkäufer</h4>1. Mit dem Antrag auf Zulassung verpflichtet sich der Verkäufer die Abwicklung des Kaufs entsprechend Anlage 2 und die Abwicklung sämtlichen Zahlungsverkehrs gemäß Anlage 3 vorzunehmen und die Regelungen dieser AGB nicht zu umgehen oder durch modifizierte oder sonstige andere Regelungen zu ergänzen.<br/>
<br/>
2. Der Verkäufer verpflichtet sich außerdem alle Aktivitäten auf der Epelia-Plattform ausschließlich mit dem zur Verfügung gestellten Webshop abzuwickeln und diesen nicht zu verändern oder zu modifizieren.<br/>
<br/>
3. Der Verkäufer verpflichtet sich über die Epelia-Plattform ausschließlich Lebensmittel und Waren des täglichen Bedarfes gemäß Anlage 1 zu veräußern.<br/>
<br/>
4. Der Verkäufer ist verpflichtet, Login und Passwort geheim zu halten und vor dem unberechtigten Zugriff Dritter zu schützen. Bei Verdacht des Missbrauchs durch einen Dritten hat der Verkäufer Epelia hierüber unverzüglich informieren. Sobald Epelia von der unberechtigten Nutzung Kenntnis erlangt, wird Epelia den Zugang des unberechtigten Verkäufers sperren. Epelia behält sich das Recht vor, Login und Passwort eines Verkäufers zu ändern; in einem solchen Fall wird Epelia den Verkäufer hierüber unverzüglich informieren.<br/>
<br/>
5. Der Verkäufer stimmt zu, dass die Zulassungsbestätigung, Hinweise über aktuelle Anpassungen der Epelia-Shopsoftware und Vertragsänderungen per E-Mail erfolgen.<br/>
<br/>
<h4>4. Verstöße gegen Pflichten Verkäufer</h4>1. Liegt ein hinreichender Verdacht für einen Verstoß des Verkäufers gegen den Vertrag und diese AGB vor, mahnt Epelia den Verkäufer ab und gibt ihm die Möglichkeit die Vertragsstörung zu beseitigen. Wird die Vertragsstörung nicht innerhalb der gesetzten Zeit beseitigt, ist Epelia berechtigt dem Verkäufer die Zulassung zu entziehen und den Zugang zur Epelia-Plattform zu sperren.<br/>
<br/>
2. Epelia behält sich das Recht vor, Angebote zu löschen und von der Epelia-Plattform zu entfernen, auch wenn das Anbieten des Artikels nicht gegen gesetzliche Vorschriften verstößt.<br/>
<br/>
<h4>5. Vergütung</h4>1. Anmeldung und Erstellung eines Webshops bei Epelia sind kostenlos.<br/>
<br/>
2. Epelia erhebt vom Verkäufer für den Abschluss eines Kaufvertrages über die Epelia-Plattform eine Provision. Die Höhe der Provision richtet sich nach den jeweils aktuellen Preiskonditionen. Für Anmeldungen bis zum 31.07.2009 gilt ein Provisionssatz von 8,5% auf den Bruttobestellwert zzgl. MwSt. Für Anmeldungen ab dem 01.08.2009 gilt der Provisionssatz von 15% auf den Bruttobestellwert zzgl. MwSt.   <br/>
<br/>
3. Der Verkäufer stimmt der Verrechnung der entstandenen Provision mit seinem Kaufpreisguthaben zu.<br/>
<br/>
4. Einwendungen gegen die Provisionsabrechnung sind innerhalb von sechs Wochen nach Zugang der Rechnung schriftlich gegenüber Epelia zu erheben. Nach Ablauf der vorgenannten Frist gilt die Abrechnung als vom Verkäufer genehmigt.<br/>
<br/>
5. Der Verkäufer ist mit der Speicherung der Abrechnungsdaten zu Beweiszwecken und/oder im Rahmen der gesetzlichen Aufbewahrungspflichten einverstanden und stimmt der Übermittlung der Rechnungen durch Epelia in elektronischer Form zu.<br/>
<br/>
<h4>6. Vertragsdauer, Kündigung</h4>1. Der diesen AGB zugrunde liegende Vertrag wird auf unbestimmte Zeit geschlossen.<br/>
<br/>
2. Der Vertrag kann durch Epelia oder den Verkäufer jederzeit mit einer Frist von zwei Wochen schriftlich gekündigt werden.<br/>
<br/>
3. 3. Das Recht zur Kündigung aus wichtigem Grund bleibt unbenommen. Ein wichtiger Grund ist für Epelia insbesondere:<br/>
- der Verstoß eines Verkäufers gegen die Bestimmungen des Vertragsverhältnisses, der auch nach Fristsetzung nicht beseitigt wird;<br/>
- die deliktische Handlung eines Verkäufers oder der Versuch einer solchen, z. B. Betrug;<br/>
- der Verzug des Verkäufers mit seiner Zahlungspflicht um mehr als sechs Wochen.<br/>
<br/>
<h4>7. Haftung</h4>1. Epelia, seine gesetzlichen Vertreter und seine Erfüllungsgehilfen haften im Falle von Vorsatz und grober Fahrlässigkeit nur soweit es sich nicht um die Verletzung einer vertragswesentlichen Pflicht oder die Verletzung des Lebens, des Körpers oder der Gesundheit handelt nur in Höhe des vorhersehbaren Schadens. In Fällen leichter Fahrlässigkeit jedoch nur aus Verletzung einer vertragswesentlichen Frist, jedoch beschränkt auf den vorhersehbaren Schaden.<br/>
<br/>
2. Die Haftung entfällt vollständig, wenn der Verkäufer ungenehmigte Änderungen und Ergänzungen am Webshop an der überlassenen Widerrufsbelehrung, Datenschutzerklärung und den Shop-AGB vornimmt.<br/>
<br/>
3. Epelia haftet für den Verlust von Daten nur dann, wenn ein solcher Verlust durch angemessene Datensicherungsmaßnahmen seitens des Verkäufers nicht vermeidbar gewesen wäre.<br/>
<br/>
4. Epelia haftet nicht für von Epelia nicht verschuldete Störungen innerhalb des Leitungsnetzes.<br/>
<br/>
5. Die Haftung von Epelia erstreckt sich nur auf den vertragsgemäßen Gebrauch der Epelia–Plattform erbrachten Leistungen.<br/>
<br/>
6. Epelia haftet nicht für Zugänglichkeit, Bestand oder Sicherheit von Datenbanken oder Diensten Dritter und für deren Inhalt. Insbesondere haftet Epelia nicht für deren Rechtmäßigkeit, inhaltliche Richtigkeit, Vollständigkeit und Aktualität.<br/>
<br/>
<h4>8. Änderung dieser Allgemeinen Geschäftsbedingungen</h4>Epelia behält sich das Recht vor, diese Allgemeinen Geschäftsbedingungen jederzeit und ohne Nennung von Gründen zu ändern. Änderungen werden dem Verkäufer per E-Mail mitgeteilt. Widerspricht der Verkäufer solchen Änderungen nicht innerhalb von zwei Wochen nach Zugang der Mitteilung, gelten die<br/>
Änderungen als vereinbart. Auf das Widerspruchsrecht und die Rechtsfolgen des Schweigens wird der Verkäufer gesondert hingewiesen.<br/>
<br/>
<h4>9. Schlussbestimmungen</h4>1. Es findet ausschließlich deutsches Recht unter Ausschluss des UN-Kaufrechts Anwendung. Erfüllungsort und ausschließlicher Gerichtsstand für alle Rechtsstreitigkeiten ist Marburg.<br/>
<br/>
2. Änderungen und Ergänzungen dieser AGB bedürfen zu ihrer Wirksamkeit der Schriftform. Dies gilt auch für Aufhebung, Änderung und Ergänzung dieser Schriftformklausel.<br/>
<br/>
3. Soweit einzelne Bestimmungen dieser AGB ganz oder teilweise unwirksam sind, wird hierdurch die Wirksamkeit dieser AGB im Übrigen nicht berührt. Die Parteien verpflichten sich die unwirksame Klausel durch eine Regelung zu ersetzen, welche der gewollten wirtschaftlich am nächsten kommt.<br/>
<br/>
<h4>10. Anlage 1: Zulässige und unzulässige Artikel</h4>1. Verkäufer dürfen auf der Epelia–Plattform ausschließlich Lebensmittel zum Verkauf anbieten, <br/>
- die nicht im überregionalen Lebensmitteleinzelhandel verfügbar sind und <br/>
- die nicht industriell als Massenware produziert werden.<br/>
<br/>
2. Der Verkäufer ist zudem verpflichtet, Artikel, die einer Altersbeschränkung unterliegen (z. B. Alkohol und alkoholhaltige Waren) nur unter Einhaltung der gesetzlichen Altersbeschränkung auszuliefern.<br/>
<br/>
3. Der Verkäufer verpflichtet sich Artikel, die nur gegen einen gesetzlich vorgeschriebenen Nachweis angeboten werden dürfen, nur dann über die Epelia–Plattform anzubieten, wenn der Nachweis in die Beschreibung der Angebote aufgenommen wurde.<br/>
<br/>
4. Es ist dem Verkäufer verboten, über die Epelia-Plattform Waren anzubieten, deren Verkauf nach der für den Vertrag maßgeblichen Rechtsordnung gegen gesetzliche Vorschriften, behördliche Anordnungen oder gegen die guten Sitten verstoßen würde. Hierzu zählen insbesondere folgende Artikel:<br/>
- Artikel, die fremde Marken- oder Urheberrechte verletzen;<br/>
- Artikel, die Drogen, Medikamente oder Arzneimittel enthalten.<br/>
<br/>
<h4>11. Anlage 2: Einrichtung und Betrieb des Webshops</h4>1. Der zur Verfügung gestellte Webshop wird unter einer Epelia-Subdomain betrieben. Die Wahl der Epelia-Subdomain hat in Abstimmung mit Epelia zu erfolgen. Epelia steht es frei, die Änderung der Subdomain zu verlangen.<br/>
<br/>
2. Der Verkäufer muss sich um Zugang zu den Leistungen von Epalia zu erlangen registrieren. Mit der Registrierung stellt der Verkäufer einen Zulassungsantrag. Er erhält einen Verifizierungsscode per Email, mit dem seine Registrierung bestätigt wird. Durch Eingabe des Verifizierungscode in die Systemmaske auf www.epelia.de wird dem Verkäufer ein vorläufiger Zugang zum System gewährt,<br/>
welche ihm die Erstellung eines eigenen Webshops ermöglicht. Nach Abschluss der Erstellung wird der Webshop auf Qualität und Eignung für das Epelia Konzept durch Epelia geprüft. Die Zulassung erfolgt durch Freischaltung des Webshops oder Übersendung einer Zulassungsbestätigung per E-Mail. Durch die Zulassung kommt ein Dienstvertrag zwischen Epelia und dem jeweiligen Verkäufer zustande.<br/>
<br/>
3. Der Verkäufer verpflichtet sich nur Artikel zum Kauf anzubieten, über die er frei verfügen und die er dem Käufer übereignen kann.<br/>
Der Preis eines auf Epelia angebotenen Artikels darf den Preis des selben Artikels im Onlineshop des Verkäufers auf seiner Webseite nicht überschreiten.<br/>
<br/>
4. Der Verkäufer verpflichtet sich zu jedem angebotenen Artikel, Produkt- und Produzentenprofile anzulegen und zu pflegen. In den Profilen müssen detaillierte Informationen zu Produkt und Produktionsbetrieb wie insbesondere Produktbeschreibungen, Inhaltsstoffe, Herstellungsverfahren in Wort und Bild anschaulich und ansprechend dargestellt werden.<br/>
<br/>
5. Der Verkäufer garantiert, dass er alle gesetzlichen Erfordernisse und Genehmigungspflichten für den Betrieb des Webshops und den Vertrieb von Lebensmitteln einhält. Er stellt Epelia von jeglicher Haftung und sonstiger Inanspruchnahme durch Dritte oder stattliche Stellen frei.<br/>
<br/>
6. Der Verkäufer verpflichtet sich, Kundenanfragen zu einem Artikel und auch sonstige Anfragen binnen zwei Werktagen zu beantworten.<br/>
<br/>
<h4>12. Anlage 3: Abwicklung des Zahlungsverkehr</h4>1. Der Verkäufer stimmt der treuhänderischen Abwicklung des Zahlungsverkehrs des Verkäufers mit den Kunden durch Epelia und deren Payment Partner zu. Hierfür anfallende Gebühren trägt Epelia.<br/>
<br/>
2. Epelia rechnet über die Zahlungseingänge für jeden Webshop zum 10. Tag des Folgemonats ab und zahlt die eingegangenen Beträge unverzüglich an den Verkäufer aus.<br/>
<br/>
3. Der Verkäufer hat Einwendungen gegen die durch Epelia vorgenommene Abrechnung innerhalb von sechs Wochen nach Zugang der Rechnung schriftlich gegenüber Epelia zu erheben. Nach Ablauf der vorgenannten Frist gilt die Abrechnung als vom Verkäufer genehmigt. Epelia wird den Verkäufer mit<br/>
Übersendung der Rechnung auf die Bedeutung seines Verhaltens besonders hinweisen.<br/>
<br/>
4. Epelia wird Vorkehrungen treffen, die Zahlungsausfälle durch z.B. Rücklastschriften äußerst gering zuhalten. Sollte es dennoch zu einem Zahlungsausfall kommen, so trägt Epelia die dafür anfallenden Gebühren (z.B. Bankgebühren und Epelia Provision). Der Verkäufer trägt lediglich den Zahlungsausfall für seine Produkte und die Versandkosten.<br/>
<br/>
5. Der Verkäufer stimmt dem Abrechnungssystem und der Übermittlung der Rechnungen durch Epelia in elektronischer Form zu.<br/>
<br/>
6. Dem Verkäufern ist es verboten, die Provisionsstruktur von Epelia zu umgehen und direkt mit dem Kunden abzurechnen.</p>
        <p class="clear">&nbsp;</p>
    </div>
</div>

