<div class="row">
    <div class="col bg-light border m-3">
        <h1>Allgemeine Geschäftsbedingungen für Spender</h1>
        <p style="font-size:13px; line-height:21px;"><h4>0. Präambel</h4>1. Fairdirect e.V.  (nachfolgend Sachspendenbörse) betreibt das Internetportal www.sachspendenbörse.org, auf welchem Unternehmer im Sinne des § 14 BGB und juristische Personen des privaten Rechts(nachfolgend Spender) die Möglichkeit haben, gemäß den Vorgaben dieser AGB Sachspenden über internetbasierte Webshops der Sachspendenbörse- Plattform kostenlos anzubieten. www.sachspendenbörse.org ist als Internet- Sachspendenmarktplatz konzipiert, bei dem Spenden zwischen Spendern und bespendeten Organisationen und Spendengesuche von registrierten Organisationen vermittelt werden<br/>
        <br/>
        2. Diese AGB enthalten abschließend die zwischen Sachspendenbörse und den Spendern geltenden Bedingungen. Änderungen dieser AGB gelten nur dann, wenn sie von Sachspendenbörse schriftlich bestätigt wurden.<br/>
        <br/>
        <h4>1. Leistungen von Sachspendenbörse</h4>1. Sachspendenbörse stellt den Spendern für deren Spendenangebote  auf der Sachspendenbörse- Plattform einen standardisierten, digitalen Spendenshop für Sachspenden zur Verfügung. Sachspendenbörse fungiert bei der Spendenabwicklung als Vermittler, der Marketingmaßnahmen durchführt, die Spendenabwicklung übernimmt und technische und persönliche Unterstützung im Bestell- und Versandmanagement bietet.<br/>
        <br/>
        2. Sachspendenbörse sorgt für registrierte Spendenempfänger bestehend aus gemeinnützigen oder mildtätigen Organisationen, welche die erhaltenen Sachspenden an ausschließlich bedürftige Menschen oder Tiere verteilen. Bei frischen und leicht verderblichen Lebensmittel kann zudem eine kostenlose Vermittlung an einen zertifizierten Secondfood*- Verarbeitungsbetrieb erfolgen.<br/>
        <br/>
        3. Auf der Sachspendenbörse- Plattform werden die Spenden aller Spender in verschiedenen Kategorien aufgelistet und durch die Werbung für Angebote in E-Mails an die zertifizierten Mitglieder des Sachspendenbörse- Netzwerkes. Dieser Bereich ist für nicht registrierte Sachspendenbörse- Nutzer gesperrt.<br/>
        <br/>
        4. Sachspendenbörse behält sich das Recht vor, Inhalt und Struktur der Sachspendenbörse-Plattform sowie die dazugehörigen Spenderoberflächen zu ändern oder zu erweitern, wenn hierdurch die Zweckerfüllung der mit den Verkäufern geschlossenen Verträge nicht oder nicht erheblich beeinträchtigt wird. Sachspendenbörse wird die Spender der Sachspendenbörse- Plattform über die Änderungen entsprechend informieren. Sachspendenbörse ist berechtigt, seine Leistung zeitweise und in angemessenem Umfang einzuschränken, wenn dies zur Durchführung technischer Maßnahmen und Wartungsarbeiten erforderlich ist. Spender werden vorab von diesen Arbeiten informiert.<br/>
        <br/>
        <h4>2. Zulassung zur Nutzung</h4>1. Voraussetzung für die Nutzung der Sachspendenbörse–Plattform ist die Zulassung des Spenders durch Sachspendenbörse.<br/>
        <br/>
        2. Die Zulassung erfolgt durch Freischaltung des Spendershops und oder die Übersendung einer Zulassungsbestätigung per E-Mail. Durch die Zulassung kommt ein Dienstvertrag zwischen Sachspendenbörse und dem jeweiligen Spender zustande.<br/>
        <br/>
        3. Bis zur Freischaltung des Sachspendenbörse- Spendershops besteht kein Recht auf die Einstellung von Artikeln auf die  Sachspendenbörse- Plattform.<br/>
        <br/>
        4. Der Spender garantiert, dass die im Rahmen seines Antrages auf Zulassung gemachten Angaben wahr und vollständig sind. Er verpflichtet sich Sachspendenbörse alle künftigen Änderungen der gemachten Angaben unverzüglich mitzuteilen. Er weist die Unternehmereigenschaft durch geeignete Belege nach.<br/>
        <br/>
        <h4>3. Pflichten Spender</h4>1. Mit dem Antrag auf Zulassung verpflichtet sich der Spender die Abwicklung der Sachspenden entsprechend Anlage 2 vorzunehmen und die Regelungen dieser AGB nicht zu umgehen oder durch modifizierte oder sonstige andere Regelungen zu ergänzen.<br/>
        <br/>
        2. Der Spender verpflichtet sich außerdem den zur Verfügung gestellten Spendenshop nicht zu verändern oder zu modifizieren.<br/>
        <br/>
        3. Der Verkäufer verpflichtet sich über die Sachspendenbörse- Plattform ausschließlich Lebensmittel und Waren des täglichen Bedarfes gemäß Anlage 1 kostenlos anzubieten.<br/>
        <br/>
        4. Der Spender ist verpflichtet, Login und Passwort geheim zu halten und vor dem unberechtigten Zugriff Dritter zu schützen. Bei Verdacht des Missbrauchs durch einen Dritten hat der Spender Sachspendenbörse hierüber unverzüglich zu informieren. Sobald Sachspendenbörse von der unberechtigten Nutzung Kenntnis erlangt, wird Sachspendenbörse den Zugang des unberechtigten Verkäufers sperren. Sachspendenbörse behält sich das Recht vor, Login und Passwort eines Spenders zu ändern; in einem solchen Fall wird Sachspendenbörse den Spender hierüber unverzüglich informieren.<br/>
        <br/>
        5. Der Spender stimmt zu, dass die Zulassungsbestätigung, Hinweise über aktuelle Anpassungen der Sachspendenbörse- Marktplatzsoftware und Vertragsänderungen per E-Mail erfolgen.<br/>
        <br/>
        <h4>4. Verstöße gegen Pflichten Verkäufer</h4>1. Liegt ein hinreichender Verdacht für einen Verstoß des Spenders gegen den Vertrag und diese AGB vor, mahnt Sachspendenbörse den Verkäufer ab und gibt ihm die Möglichkeit die Vertragsstörung zu beseitigen. Wird die Vertragsstörung nicht innerhalb der gesetzten Zeit beseitigt, ist Sachspendenbörse berechtigt dem Verkäufer die Zulassung zu entziehen und den Zugang zur Sachspendenbörse- Plattform zu sperren.<br/>
        <br/>
        2. Sachspendenbörse behält sich das Recht vor, Angebote zu löschen und von der Sachspendenbörse- Plattform zu entfernen, auch wenn das Anbieten des Artikels nicht gegen gesetzliche Vorschriften verstößt.<br/>
        <br/>
        <h4>5. Vergütung/ Datenspeicherung</h4>1. Die Nutzung der Sachspendenbörse- Plattform ist komplett kostenlos.<br/>
        <br/>
        2. Der Spender ist mit der Speicherung der Spenderdaten zu Verarbeitungs-, Beweiszwecken und/oder im Rahmen der gesetzlichen Aufbewahrungspflichten einverstanden.<br/>
        <br/>
        <h4>6. Vertragsdauer, Kündigung</h4>1. Der diesen AGB zugrunde liegende Vertrag wird auf unbestimmte Zeit geschlossen.<br/>
        <br/>
        2. Der Vertrag kann durch Sachspendenbörse jederzeit innerhalb von zwei Wochen, vom Spender jederzeit fristlos gekündigt werden.<br/>
        <br/>
        3. Das Recht zur Kündigung aus wichtigem Grund bleibt unbenommen. Ein wichtiger Grund ist für Sachspendenbörse insbesondere:<br/>
        - der Verstoß eines Spenders gegen die Bestimmungen des Vertragsverhältnisses, der auch nach Fristsetzung nicht beseitigt wird;<br/>
        - die deliktische Handlung eines Spenders oder der Versuch einer solchen, z. B. Betrug;<br/>        
        <br/>
        <h4>7. Haftung</h4>1. Sachspendenbörse, seine gesetzlichen Vertreter und seine Erfüllungsgehilfen haften im Falle von Vorsatz und grober Fahrlässigkeit nur soweit es sich nicht um die Verletzung einer vertragswesentlichen Pflicht oder die Verletzung des Lebens, des Körpers oder der Gesundheit handelt nur in Höhe des vorhersehbaren Schadens. In Fällen leichter Fahrlässigkeit jedoch nur aus Verletzung einer vertragswesentlichen Frist, jedoch beschränkt auf den vorhersehbaren Schaden.<br/>
        <br/>
        2. Die Haftung entfällt vollständig, wenn der Spender ungenehmigte Änderungen und Ergänzungen am Webshop an der überlassenen Widerrufsbelehrung, Datenschutzerklärung und den Spender-AGB vornimmt.<br/>
        <br/>
        3. Sachspendenbörse haftet für den Verlust von Daten nur dann, wenn ein solcher Verlust durch angemessene Datensicherungsmaßnahmen seitens des Spenders nicht vermeidbar gewesen wäre.<br/>
        <br/>
        4. Sachspendenbörse haftet nicht für von Sachspendenbörse nicht verschuldete Störungen innerhalb des Leitungsnetzes.<br/>
        <br/>
        5. Die Haftung von Sachspendenbörse erstreckt sich nur auf den vertragsgemäßen Gebrauch der Sachspendenbörse– Plattform erbrachten Leistungen.<br/>
        <br/>
        6. Sachspendenbörse haftet nicht für Zugänglichkeit, Bestand oder Sicherheit von Datenbanken oder Diensten Dritter und für deren Inhalt. Insbesondere haftet Sachspendenbörse nicht für deren Rechtmäßigkeit, inhaltliche Richtigkeit, Vollständigkeit und Aktualität.<br/>
        <br/>
        <h4>8. Änderung dieser Allgemeinen Geschäftsbedingungen</h4>Sachspendenbörse behält sich das Recht vor, diese Allgemeinen Geschäftsbedingungen jederzeit und ohne Nennung von Gründen zu ändern. Änderungen werden dem Spender per E-Mail mitgeteilt. Widerspricht der Spender solchen Änderungen nicht innerhalb von zwei Wochen nach Zugang der Mitteilung, gelten die<br/>
        Änderungen als vereinbart. Auf das Widerspruchsrecht und die Rechtsfolgen des Schweigens wird der Verkäufer gesondert hingewiesen.<br/>
        <br/>
        <h4>9. Schlussbestimmungen</h4>1. Es findet ausschließlich deutsches Recht unter Ausschluss des UN-Kaufrechts Anwendung. Erfüllungsort und ausschließlicher Gerichtsstand für alle Rechtsstreitigkeiten ist Marburg.<br/>
        <br/>
        2. Änderungen und Ergänzungen dieser AGB bedürfen zu ihrer Wirksamkeit der Schriftform. Dies gilt auch für Aufhebung, Änderung und Ergänzung dieser Schriftformklausel.<br/>
        <br/>
        3. Soweit einzelne Bestimmungen dieser AGB ganz oder teilweise unwirksam sind, wird hierdurch die Wirksamkeit dieser AGB im Übrigen nicht berührt. Die Parteien verpflichten sich die unwirksame Klausel durch eine Regelung zu ersetzen, welche der gewollten wirtschaftlich am nächsten kommt.<br/>
        <br/>
        <h4>10. Anlage 1: Zulässige und unzulässige Artikel</h4>1. Spender dürfen auf der Sachspendenbörse– Plattform Lebensmittel und Waren des täglichen Bedarfes ausschließlich als kostenlose Sachspende anbieten.<br/>
        <br/>
        2. Der Spender verpflichtet sich Artikel, die nur gegen einen gesetzlich vorgeschriebenen Nachweis angeboten werden dürfen, nur dann über die Sachspendenbörse– Plattform anzubieten, wenn der Nachweis in die Beschreibung der Angebote aufgenommen wurde.<br/>
        <br/>
        3. Es ist dem Spender verboten, über die Sachspendenbörse- Plattform Waren anzubieten, deren in Verkehr- bzw. in Umlaufbringung nach der für den Vertrag maßgeblichen Rechtsordnung gegen gesetzliche Vorschriften, behördliche Anordnungen oder gegen die guten Sitten verstoßen würde. Hierzu zählen insbesondere folgende Artikel:- Artikel, die fremde Marken- oder Urheberrechte verletzen;- Artikel, die Drogen, rezeptpflichtige Medikamente und Arzneimittel oder verbotene Inhaltsstoffe enthalten.<br/>
        <br/>
        <h4>11. Anlage 2: Einrichtung und Betrieb des Spendenshops</h4>1. Der zur Verfügung gestellte Spendenshop wird unter einer Sachspendenbörse-Subdomain betrieben. Die Wahl der Sachspendenbörse-Subdomain hat in Abstimmung mit Sachspendenbörse zu erfolgen. Sachspendenbörse steht es frei, die Änderung der Subdomain zu verlangen<br/>
        <br/>
        2. Der Verkäufer muss sich, um Zugang auf den Sachspendenbörse- Spendenmarktplatz zu erlangen, registrieren. Mit der Registrierung stellt der Spender einen Zulassungsantrag. Er erhält einen Verifizierungsscode per Email, mit dem seine Registrierung bestätigt wird. Durch Eingabe des Verifizierungscode in die Systemmaske auf www.sachspendenbörse.org wird dem Spender ein vorläufiger Zugang zum System gewährt,<br/>
        welche ihm die Erstellung eines eigenen Spendenshops ermöglicht. Nach Abschluss der Erstellung wird der Spendenshop auf Qualität und Eignung für das Sachspendenbörse- Konzept durch Sachspendenbörse geprüft. Die Zulassung erfolgt durch Freischaltung des Spendenshops oder Übersendung einer Zulassungsbestätigung per E-Mail. Durch die Zulassung kommt ein Dienstvertrag zwischen Sachspendenbörse und dem jeweiligen Spender zustande.<br/>
        <br/>
        3. Der Spender verpflichtet sich nur Artikel zu spenden, über die er frei verfügen und die er an den Bespendeten kostenlos spenden kann.<br/>
        <br/>
        4. Der Spender verpflichtet sich zu jedem angebotenen Artikel, Produkt- und Produzentenprofile anzulegen und zu pflegen. In den Profilen müssen detaillierte Informationen in Wort und Bild anschaulich und möglichst ansprechend dargestellt werden.<br/>
        <br/>
        5. Der Spender garantiert, dass er alle gesetzlichen Erfordernisse und Genehmigungspflichten für den Betrieb des Spendensshops und den Vertrieb von Lebensmitteln einhält. Er stellt Sachspendenbörse von jeglicher Haftung und sonstiger Inanspruchnahme durch Dritte oder stattliche Stellen frei.<br/>
        <br/>
        6. Der Spender verpflichtet sich, Anfragen zu einem Artikel binnen zwei Werktagen zu beantworten.<br/>
        <br/>
        * weitere Informationen über Secondfood finden Sie unter www.secondfood.org</p>
                <p class="clear">&nbsp;</p>
            </div>
        </div>
    </div>
</div>
